import type { Lang } from "@/lib/i18n";
import * as history from "@/lib/dict/history";
import * as settings from "@/lib/dict/settings";
import * as auth from "@/lib/dict/auth";
import * as workout from "@/lib/dict/workout";
import * as screens from "@/lib/dict/screens";
import * as server from "@/lib/dict/server";

/**
 * UI strings, keyed by area. English is the source of truth; a missing key in
 * another language falls back to English rather than rendering blank.
 *
 * Brocco-generated prose (briefings, coaching, workout names) is NOT here —
 * that arrives already written in the user's language, see coach-context.
 */

const BASE_EN = {
  // Navigation
  "nav.today": "Today",
  "nav.calendar": "Calendar",
  "nav.chat": "Chat",
  "nav.plan": "Plan",
  "nav.history": "History",
  "nav.more": "More",
  "nav.workouts": "Workouts",
  "nav.kitchen": "Kitchen",
  "nav.settings": "Settings",
  "nav.notes": "Notes",

  // Common
  "common.save": "Save",
  "common.saved": "Saved",
  "common.saving": "Saving…",
  "common.cancel": "Cancel",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.close": "Close",
  "common.start": "Start",
  "common.done": "Done",
  "common.undo": "Undo",
  "common.loading": "Loading…",
  "common.retry": "Try again",
  "common.today": "Today",
  "common.yesterday": "Yesterday",
  "common.tomorrow": "Tomorrow",
  "common.min": "min",
  "common.km": "km",
  "common.sessions": "sessions",
  "common.rest": "rest",
  "common.reps": "reps",
  "common.week": "Week",
  "common.somethingWrong": "Something went wrong.",

  // Today
  "today.title": "Today",
  "today.briefing": "Your briefing",
  "today.weekReview": "📋 Your week in review",
  "today.dismissReview": "Dismiss weekly review",
  "today.thisWeek": "This week",
  "today.nothingToday": "Nothing scheduled today.",
  "today.comingUp": "Coming up",
  "today.planDone": "is done!",
  "today.buildPlan": "Build a plan",
  "today.connectStrava": "Connect Strava",
  "today.stravaBroken": "Strava stopped syncing — access expired.",
  "today.reconnect": "Reconnect",
  "today.restUp": "Rest up, or chat with Brocco about the week.",

  // Plan
  "plan.title": "Plan",
  "plan.thisWeek": "This week",
  "plan.lastWeek": "Last week",
  "plan.theBlock": "The block",
  "plan.weekByWeek": "Week by week",
  "plan.peak": "peak",
  "plan.targetHit": "target hit",
  "plan.short": "short",
  "plan.seeSessions": "See the sessions",
  "plan.explainPlan": "Explain this plan",
  "plan.raceDay": "Race day",
  "plan.days": "days",
  "plan.day": "day",
  "plan.phaseEndsIn": "Phase ends in",
  "plan.lastWeekOf": "Last week of",
  "plan.noPlan": "No training plan yet.",
  "plan.weeksTotal": "weeks",
  "plan.weekOf": "of",

  // Calendar
  "calendar.title": "Calendar",
  "calendar.day": "day",
  "calendar.week": "week",
  "calendar.month": "month",
  "calendar.today": "Today",
  "calendar.previous": "Previous",
  "calendar.next": "Next",
  "calendar.nothingScheduled": "Nothing scheduled.",
  "calendar.allDay": "all day",
  "calendar.continues": "continues",
  "calendar.until": "until",
  "calendar.planned": "Planned",
  "calendar.actual": "Actual",
  "calendar.doneLabel": "✓ Done",
  "calendar.missed": "✗ Missed",
  "calendar.notRun": "not run",
  "calendar.unplanned": "Unplanned",
  "calendar.spontaneous": "— spontaneous",
  "calendar.newEvent": "New event",
  "calendar.deleteThis": "Delete this",
  "calendar.deleteAll": "Delete all",

  // Workouts
  "workout.title": "Workouts",
  "workout.askBrocco": "Ask Brocco for a workout",
  "workout.askBroccoSub": "Tell it your time, focus, and equipment — get a playable session",
  "workout.quickStart": "Quick start",
  "workout.customIntervals": "⏱ Custom intervals",
  "workout.work": "Work (s)",
  "workout.restSec": "Rest (s)",
  "workout.rounds": "Rounds",
  "workout.yourWorkouts": "Your workouts",
  "workout.fromPlan": "From your plan",
  "workout.nothingSaved": "Nothing saved yet — ask Brocco for a workout and it lands here.",
  "workout.showOlder": "Show older plan sessions",
  "workout.hideOlder": "Hide older plan sessions",
  "workout.building": "Brocco is building your session…",
  "workout.warmUp": "Warm-up",
  "workout.coolDown": "Cool-down",
  "workout.betweenRounds": "between rounds",
  "workout.round": "round",
  "workout.roundsPlural": "rounds",
  "workout.history": "History",
  "workout.completed": "✓ completed",
  "workout.stoppedAfter": "stopped after",
  "workout.exercise": "exercise",
  "workout.exercisesPlural": "exercises",
  "workout.adjustWithBrocco": "Adjust with Brocco",
  "workout.startAdjusted": "Start (adjusted)",
  "workout.pinToTop": "Pin to top",
  "workout.unpin": "Unpin",
  "workout.deleted": "Deleted",
  "workout.couldntDelete": "Couldn't delete — try again.",
  "workout.couldntLoad": "Couldn't load that workout.",
  "workout.couldntBuild": "Couldn't build the session — try a preset instead.",
  "workout.fewerRounds": "Fewer rounds",
  "workout.moreRounds": "More rounds",
  "workout.adjustPrompt": "Here's what I want changed: ",
  "workout.adjustIntro": "Adjust this workout for me",

  // Player
  "player.getReady": "Get ready",
  "player.rest": "Rest",
  "player.roundRest": "Round rest",
  "player.next": "Next",
  "player.complete": "Workout complete!",
  "player.logging": "Logging to training…",
  "player.logged": "✓ Logged to training",
  "player.logFailed": "Couldn't log the workout — it still counts in your heart.",
  "player.notLogged": "Not logged.",
  "player.quitTitle": "Quit this workout?",
  "player.keepGoing": "Keep going 💪",
  "player.quit": "Quit",
  "player.sessionPlan": "Session plan",
  "player.beeps": "🔔 Beeps",
  "player.voice": "🗣 Voice",
  "player.addRest": "+15s rest",
  "player.exitWorkout": "Exit workout",
  "player.showPlan": "Show session plan",
  "player.pause": "Pause",
  "player.resume": "Resume",
  "player.skip": "Skip",
  "player.previous": "Previous",
  "player.exerciseOf": "Exercise",

  // Chat
  "chat.placeholder": "Ask Brocco...",
  "chat.send": "Send",
  "chat.kitchenPlaceholder": "What's in your fridge?",
  "chat.listening": "Listening…",
  "chat.listeningNoLive": "Listening… (words appear when you stop)",
  "chat.conversations": "Conversations",
  "chat.kitchenChats": "Kitchen chats",
  "chat.newConversation": "+ New conversation",
  "chat.weekCheckin": "📊 Week check-in",
  "chat.reconnecting": "Connection dropped — waiting for Brocco's reply…",
  "chat.replyLost": "The connection dropped and the reply didn't come through. Your message is back in the box — send it again.",
  "chat.weekCheckinMsg": "Give me a quick check-in on my week: what's done, what's missed or unconfirmed, and what's next.",
  "chat.voiceInput": "Voice input",
  "chat.transcribing": "Transcribing...",
  "chat.stopRecording": "Stop recording",
  "chat.cooking": "What are we cooking?",
  "chat.cookingSub": "Tell me what's in your fridge and I'll suggest something — your saved recipes and pantry staples included.",

  // History
  "history.title": "History",
  "history.all": "All",
  "history.runs": "Runs",
  "history.rides": "Rides",
  "history.strength": "Strength",
  "history.climbs": "Climbs",
  "history.other": "Other",
  "history.noActivities": "No activities yet.",
  "history.loadMore": "Load more",
  "history.trends": "Trends",

  // Settings
  "settings.title": "Settings",
  "settings.profile": "Profile",
  "settings.name": "Name",
  "settings.email": "Email",
  "settings.timezone": "Timezone",
  "settings.language": "Language",
  "settings.languageHint": "Brocco writes in this language too — chat, briefings, workouts and plans.",
  "settings.primarySport": "Main sport",
  "settings.primarySportHint": "Brocco coaches this sport first: sessions and minutes instead of kilometres. Your current plan is not changed.",
  "sport.running": "Running",
  "sport.climbing": "Climbing",
  "sport.cycling": "Cycling",
  "sport.swimming": "Swimming",
  "sport.triathlon": "Triathlon",
  "sport.hyrox": "Hyrox",
  "settings.goalRace": "Goal race",
  "settings.goalTime": "Goal time",
  "settings.raceDate": "Race date",
  "settings.maxHr": "Max heart rate",
  "settings.features": "Features",
  "settings.notifications": "Notifications",
  "settings.strava": "Strava",
  "settings.connected": "Connected",
  "settings.syncNow": "Sync Now",
  "settings.syncing": "Syncing...",
  "settings.disconnect": "Disconnect",
  "settings.lastSynced": "Last synced",
  "settings.never": "never",
  "settings.stravaExpired": "Strava access expired or was revoked — activities have stopped syncing.",
  "settings.reconnectStrava": "Reconnect Strava",
  "settings.connectStravaHint": "Connect your Strava account to import activities.",
  "settings.connectWithStrava": "Connect with Strava",
  "settings.watchSync": "Watch sync",
  "settings.changePassword": "Change Password",
  "settings.account": "Account",
  "settings.logout": "Log out",
  "settings.deleteAccount": "Delete account",
  "settings.installApp": "Install App",
  "settings.calendarFeed": "Calendar feed",
  "settings.equipment": "Equipment",

  "more.planDesc": "Phases, weekly targets, race countdown",
  "more.historyDesc": "All past activities",
  "more.workoutsDesc": "Guided S&C sessions and interval timers",
  "more.kitchenDesc": "Recipe library, photo scans, cooking ideas",
  "more.settingsDesc": "Profile, features, Strava, notifications",
  "more.trainingPlan": "Training Plan",

  "confirm.didItHappen": "Did it happen?",
  "confirm.done": "Done",
  "confirm.skipped": "Skipped",
  "confirm.notConfirmed": "Not confirmed",
  "confirm.notConfirmedHint": "can't be detected automatically",
  "confirm.markDone": "Mark done",
  "confirm.markedDone": "Logged",
  "confirm.markedSkipped": "Marked as skipped",
  "confirm.yesterday": "Yesterday",

  // Units (plural forms; pick with plural() from i18n)
  "unit.page": "page",
  "unit.pages": "pages",
  "unit.week": "week",
  "unit.weeks": "weeks",

  // Auth
  "auth.login": "Log in",
  "auth.signup": "Sign up",
  "auth.password": "Password",
  "auth.forgotPassword": "Forgot password?",
  "auth.resetPassword": "Reset password",
  "auth.accessCode": "Access code",
  "auth.loggingIn": "Logging in…",
} as const;

const BASE_DE = {
  "nav.today": "Heute",
  "nav.calendar": "Kalender",
  "nav.chat": "Chat",
  "nav.plan": "Plan",
  "nav.history": "Verlauf",
  "nav.more": "Mehr",
  "nav.workouts": "Workouts",
  "nav.kitchen": "Küche",
  "nav.settings": "Einstellungen",
  "nav.notes": "Notizen",

  "common.save": "Speichern",
  "common.saved": "Gespeichert",
  "common.saving": "Speichern…",
  "common.cancel": "Abbrechen",
  "common.delete": "Löschen",
  "common.edit": "Bearbeiten",
  "common.close": "Schließen",
  "common.start": "Start",
  "common.done": "Fertig",
  "common.undo": "Rückgängig",
  "common.loading": "Lädt…",
  "common.retry": "Erneut versuchen",
  "common.today": "Heute",
  "common.yesterday": "Gestern",
  "common.tomorrow": "Morgen",
  "common.min": "Min",
  "common.km": "km",
  "common.sessions": "Einheiten",
  "common.rest": "Pause",
  "common.reps": "Wdh.",
  "common.week": "Woche",
  "common.somethingWrong": "Etwas ist schiefgelaufen.",

  "today.title": "Heute",
  "today.briefing": "Dein Briefing",
  "today.weekReview": "📋 Dein Wochenrückblick",
  "today.dismissReview": "Wochenrückblick ausblenden",
  "today.thisWeek": "Diese Woche",
  "today.nothingToday": "Heute steht nichts an.",
  "today.comingUp": "Demnächst",
  "today.planDone": "ist abgeschlossen!",
  "today.buildPlan": "Plan erstellen",
  "today.connectStrava": "Strava verbinden",
  "today.stravaBroken": "Strava synchronisiert nicht mehr — Zugriff abgelaufen.",
  "today.reconnect": "Neu verbinden",
  "today.restUp": "Erhol dich, oder sprich mit Brocco über die Woche.",

  "plan.title": "Plan",
  "plan.thisWeek": "Diese Woche",
  "plan.lastWeek": "Letzte Woche",
  "plan.theBlock": "Der Block",
  "plan.weekByWeek": "Woche für Woche",
  "plan.peak": "Maximum",
  "plan.targetHit": "Ziel erreicht",
  "plan.short": "fehlen",
  "plan.seeSessions": "Einheiten ansehen",
  "plan.explainPlan": "Plan erklären",
  "plan.raceDay": "Wettkampftag",
  "plan.days": "Tage",
  "plan.day": "Tag",
  "plan.phaseEndsIn": "Phase endet in",
  "plan.lastWeekOf": "Letzte Woche der Phase",
  "plan.noPlan": "Noch kein Trainingsplan.",
  "plan.weeksTotal": "Wochen",
  "plan.weekOf": "von",

  "calendar.title": "Kalender",
  "calendar.day": "Tag",
  "calendar.week": "Woche",
  "calendar.month": "Monat",
  "calendar.today": "Heute",
  "calendar.previous": "Zurück",
  "calendar.next": "Weiter",
  "calendar.nothingScheduled": "Nichts geplant.",
  "calendar.allDay": "ganztägig",
  "calendar.continues": "läuft weiter",
  "calendar.until": "bis",
  "calendar.planned": "Geplant",
  "calendar.actual": "Tatsächlich",
  "calendar.doneLabel": "✓ Erledigt",
  "calendar.missed": "✗ Verpasst",
  "calendar.notRun": "nicht gelaufen",
  "calendar.unplanned": "Ungeplant",
  "calendar.spontaneous": "— spontan",
  "calendar.newEvent": "Neuer Termin",
  "calendar.deleteThis": "Diesen löschen",
  "calendar.deleteAll": "Alle löschen",

  "workout.title": "Workouts",
  "workout.askBrocco": "Brocco um ein Workout bitten",
  "workout.askBroccoSub": "Sag ihm Zeit, Fokus und Ausrüstung — du bekommst eine abspielbare Einheit",
  "workout.quickStart": "Schnellstart",
  "workout.customIntervals": "⏱ Eigene Intervalle",
  "workout.work": "Arbeit (s)",
  "workout.restSec": "Pause (s)",
  "workout.rounds": "Runden",
  "workout.yourWorkouts": "Deine Workouts",
  "workout.fromPlan": "Aus deinem Plan",
  "workout.nothingSaved": "Noch nichts gespeichert — bitte Brocco um ein Workout, dann landet es hier.",
  "workout.showOlder": "Ältere Plan-Einheiten zeigen",
  "workout.hideOlder": "Ältere Plan-Einheiten ausblenden",
  "workout.building": "Brocco baut deine Einheit…",
  "workout.warmUp": "Aufwärmen",
  "workout.coolDown": "Abwärmen",
  "workout.betweenRounds": "zwischen den Runden",
  "workout.round": "Runde",
  "workout.roundsPlural": "Runden",
  "workout.history": "Verlauf",
  "workout.completed": "✓ abgeschlossen",
  "workout.stoppedAfter": "abgebrochen nach",
  "workout.exercise": "Übung",
  "workout.exercisesPlural": "Übungen",
  "workout.adjustWithBrocco": "Mit Brocco anpassen",
  "workout.startAdjusted": "Start (angepasst)",
  "workout.pinToTop": "Anheften",
  "workout.unpin": "Lösen",
  "workout.deleted": "Gelöscht",
  "workout.couldntDelete": "Löschen fehlgeschlagen — nochmal versuchen.",
  "workout.couldntLoad": "Workout konnte nicht geladen werden.",
  "workout.couldntBuild": "Einheit konnte nicht erstellt werden — nimm solange eine Vorlage.",
  "workout.fewerRounds": "Weniger Runden",
  "workout.moreRounds": "Mehr Runden",
  "workout.adjustPrompt": "Das möchte ich ändern: ",
  "workout.adjustIntro": "Pass dieses Workout für mich an",

  "player.getReady": "Bereit machen",
  "player.rest": "Pause",
  "player.roundRest": "Rundenpause",
  "player.next": "Als Nächstes",
  "player.complete": "Workout geschafft!",
  "player.logging": "Wird ins Training eingetragen…",
  "player.logged": "✓ Ins Training eingetragen",
  "player.logFailed": "Konnte nicht eingetragen werden — es zählt trotzdem.",
  "player.notLogged": "Nicht eingetragen.",
  "player.quitTitle": "Workout beenden?",
  "player.keepGoing": "Weitermachen 💪",
  "player.quit": "Beenden",
  "player.sessionPlan": "Ablauf",
  "player.beeps": "🔔 Töne",
  "player.voice": "🗣 Stimme",
  "player.addRest": "+15s Pause",
  "player.exitWorkout": "Workout verlassen",
  "player.showPlan": "Ablauf anzeigen",
  "player.pause": "Pause",
  "player.resume": "Weiter",
  "player.skip": "Überspringen",
  "player.previous": "Zurück",
  "player.exerciseOf": "Übung",

  "chat.placeholder": "Frag Brocco...",
  "chat.send": "Senden",
  "chat.kitchenPlaceholder": "Was ist im Kühlschrank?",
  "chat.listening": "Hört zu…",
  "chat.listeningNoLive": "Hört zu… (Wörter erscheinen beim Stoppen)",
  "chat.conversations": "Unterhaltungen",
  "chat.kitchenChats": "Küchen-Chats",
  "chat.newConversation": "+ Neue Unterhaltung",
  "chat.weekCheckin": "📊 Wochen-Check",
  "chat.reconnecting": "Verbindung unterbrochen — warte auf Broccos Antwort…",
  "chat.replyLost": "Die Verbindung ist abgebrochen und die Antwort kam nicht an. Deine Nachricht steht wieder im Eingabefeld — schick sie noch einmal.",
  "chat.weekCheckinMsg": "Gib mir einen kurzen Überblick über meine Woche: was erledigt ist, was verpasst oder unbestätigt ist, und was als Nächstes kommt.",
  "chat.voiceInput": "Spracheingabe",
  "chat.transcribing": "Wird transkribiert...",
  "chat.stopRecording": "Aufnahme stoppen",
  "chat.cooking": "Was kochen wir?",
  "chat.cookingSub": "Sag mir, was im Kühlschrank ist, und ich schlage etwas vor — deine gespeicherten Rezepte und Vorräte inklusive.",

  "history.title": "Verlauf",
  "history.all": "Alle",
  "history.runs": "Läufe",
  "history.rides": "Radfahrten",
  "history.strength": "Kraft",
  "history.climbs": "Klettern",
  "history.other": "Sonstiges",
  "history.noActivities": "Noch keine Aktivitäten.",
  "history.loadMore": "Mehr laden",
  "history.trends": "Trends",

  "settings.title": "Einstellungen",
  "settings.profile": "Profil",
  "settings.name": "Name",
  "settings.email": "E-Mail",
  "settings.timezone": "Zeitzone",
  "settings.language": "Sprache",
  "settings.languageHint": "Brocco schreibt ebenfalls in dieser Sprache — Chat, Briefings, Workouts und Pläne.",
  "settings.primarySport": "Hauptsportart",
  "settings.primarySportHint": "Brocco coacht diese Sportart zuerst: Einheiten und Minuten statt Kilometer. Dein aktueller Plan bleibt unverändert.",
  "sport.running": "Laufen",
  "sport.climbing": "Klettern",
  "sport.cycling": "Radfahren",
  "sport.swimming": "Schwimmen",
  "sport.triathlon": "Triathlon",
  "sport.hyrox": "Hyrox",
  "settings.goalRace": "Zielwettkampf",
  "settings.goalTime": "Zielzeit",
  "settings.raceDate": "Wettkampfdatum",
  "settings.maxHr": "Maximale Herzfrequenz",
  "settings.features": "Funktionen",
  "settings.notifications": "Benachrichtigungen",
  "settings.strava": "Strava",
  "settings.connected": "Verbunden",
  "settings.syncNow": "Jetzt synchronisieren",
  "settings.syncing": "Synchronisiert...",
  "settings.disconnect": "Trennen",
  "settings.lastSynced": "Zuletzt synchronisiert",
  "settings.never": "nie",
  "settings.stravaExpired": "Strava-Zugriff abgelaufen oder entzogen — es kommen keine Aktivitäten mehr an.",
  "settings.reconnectStrava": "Strava neu verbinden",
  "settings.connectStravaHint": "Verbinde dein Strava-Konto, um Aktivitäten zu importieren.",
  "settings.connectWithStrava": "Mit Strava verbinden",
  "settings.watchSync": "Uhren-Sync",
  "settings.changePassword": "Passwort ändern",
  "settings.account": "Konto",
  "settings.logout": "Abmelden",
  "settings.deleteAccount": "Konto löschen",
  "settings.installApp": "App installieren",
  "settings.calendarFeed": "Kalender-Feed",
  "settings.equipment": "Ausrüstung",

  "more.planDesc": "Phasen, Wochenziele, Countdown zum Wettkampf",
  "more.historyDesc": "Alle vergangenen Aktivitäten",
  "more.workoutsDesc": "Angeleitete Kraft-Einheiten und Intervall-Timer",
  "more.kitchenDesc": "Rezeptsammlung, Foto-Scans, Kochideen",
  "more.settingsDesc": "Profil, Funktionen, Strava, Benachrichtigungen",
  "more.trainingPlan": "Trainingsplan",
  "confirm.didItHappen": "Hat es stattgefunden?",
  "confirm.done": "Gemacht",
  "confirm.skipped": "Ausgelassen",
  "confirm.notConfirmed": "Nicht bestätigt",
  "confirm.notConfirmedHint": "kann nicht automatisch erkannt werden",
  "confirm.markDone": "Als gemacht markieren",
  "confirm.markedDone": "Eingetragen",
  "confirm.markedSkipped": "Als ausgelassen markiert",
  "confirm.yesterday": "Gestern",
  "unit.page": "Seite",
  "unit.pages": "Seiten",
  "unit.week": "Woche",
  "unit.weeks": "Wochen",
  "auth.login": "Anmelden",
  "auth.signup": "Registrieren",
  "auth.password": "Passwort",
  "auth.forgotPassword": "Passwort vergessen?",
  "auth.resetPassword": "Passwort zurücksetzen",
  "auth.accessCode": "Zugangscode",
  "auth.loggingIn": "Anmeldung…",
};

const BASE_ES = {
  "nav.today": "Hoy",
  "nav.calendar": "Calendario",
  "nav.chat": "Chat",
  "nav.plan": "Plan",
  "nav.history": "Historial",
  "nav.more": "Más",
  "nav.workouts": "Entrenos",
  "nav.kitchen": "Cocina",
  "nav.settings": "Ajustes",
  "nav.notes": "Notas",

  "common.save": "Guardar",
  "common.saved": "Guardado",
  "common.saving": "Guardando…",
  "common.cancel": "Cancelar",
  "common.delete": "Eliminar",
  "common.edit": "Editar",
  "common.close": "Cerrar",
  "common.start": "Empezar",
  "common.done": "Hecho",
  "common.undo": "Deshacer",
  "common.loading": "Cargando…",
  "common.retry": "Reintentar",
  "common.today": "Hoy",
  "common.yesterday": "Ayer",
  "common.tomorrow": "Mañana",
  "common.min": "min",
  "common.km": "km",
  "common.sessions": "sesiones",
  "common.rest": "descanso",
  "common.reps": "reps",
  "common.week": "Semana",
  "common.somethingWrong": "Algo salió mal.",

  "today.title": "Hoy",
  "today.briefing": "Tu resumen",
  "today.weekReview": "📋 Tu semana en resumen",
  "today.dismissReview": "Ocultar resumen semanal",
  "today.thisWeek": "Esta semana",
  "today.nothingToday": "Nada programado hoy.",
  "today.comingUp": "Próximamente",
  "today.planDone": "¡está terminado!",
  "today.buildPlan": "Crear un plan",
  "today.connectStrava": "Conectar Strava",
  "today.stravaBroken": "Strava dejó de sincronizar — acceso caducado.",
  "today.reconnect": "Reconectar",
  "today.restUp": "Descansa, o habla con Brocco sobre la semana.",

  "plan.title": "Plan",
  "plan.thisWeek": "Esta semana",
  "plan.lastWeek": "Semana pasada",
  "plan.theBlock": "El bloque",
  "plan.weekByWeek": "Semana a semana",
  "plan.peak": "pico",
  "plan.targetHit": "objetivo cumplido",
  "plan.short": "faltan",
  "plan.seeSessions": "Ver las sesiones",
  "plan.explainPlan": "Explicar este plan",
  "plan.raceDay": "Día de carrera",
  "plan.days": "días",
  "plan.day": "día",
  "plan.phaseEndsIn": "La fase termina en",
  "plan.lastWeekOf": "Última semana de",
  "plan.noPlan": "Aún no hay plan de entrenamiento.",
  "plan.weeksTotal": "semanas",
  "plan.weekOf": "de",

  "calendar.title": "Calendario",
  "calendar.day": "día",
  "calendar.week": "semana",
  "calendar.month": "mes",
  "calendar.today": "Hoy",
  "calendar.previous": "Anterior",
  "calendar.next": "Siguiente",
  "calendar.nothingScheduled": "Nada programado.",
  "calendar.allDay": "todo el día",
  "calendar.continues": "continúa",
  "calendar.until": "hasta",
  "calendar.planned": "Planeado",
  "calendar.actual": "Real",
  "calendar.doneLabel": "✓ Hecho",
  "calendar.missed": "✗ Perdido",
  "calendar.notRun": "no corrido",
  "calendar.unplanned": "Sin planear",
  "calendar.spontaneous": "— espontáneo",
  "calendar.newEvent": "Nuevo evento",
  "calendar.deleteThis": "Eliminar este",
  "calendar.deleteAll": "Eliminar todos",

  "workout.title": "Entrenos",
  "workout.askBrocco": "Pídele un entreno a Brocco",
  "workout.askBroccoSub": "Dile tu tiempo, enfoque y equipo — recibes una sesión reproducible",
  "workout.quickStart": "Inicio rápido",
  "workout.customIntervals": "⏱ Intervalos propios",
  "workout.work": "Trabajo (s)",
  "workout.restSec": "Descanso (s)",
  "workout.rounds": "Rondas",
  "workout.yourWorkouts": "Tus entrenos",
  "workout.fromPlan": "De tu plan",
  "workout.nothingSaved": "Nada guardado aún — pídele un entreno a Brocco y aparecerá aquí.",
  "workout.showOlder": "Ver sesiones antiguas del plan",
  "workout.hideOlder": "Ocultar sesiones antiguas",
  "workout.building": "Brocco está creando tu sesión…",
  "workout.warmUp": "Calentamiento",
  "workout.coolDown": "Vuelta a la calma",
  "workout.betweenRounds": "entre rondas",
  "workout.round": "ronda",
  "workout.roundsPlural": "rondas",
  "workout.history": "Historial",
  "workout.completed": "✓ completado",
  "workout.stoppedAfter": "parado tras",
  "workout.exercise": "ejercicio",
  "workout.exercisesPlural": "ejercicios",
  "workout.adjustWithBrocco": "Ajustar con Brocco",
  "workout.startAdjusted": "Empezar (ajustado)",
  "workout.pinToTop": "Fijar arriba",
  "workout.unpin": "Desfijar",
  "workout.deleted": "Eliminado",
  "workout.couldntDelete": "No se pudo eliminar — inténtalo de nuevo.",
  "workout.couldntLoad": "No se pudo cargar ese entreno.",
  "workout.couldntBuild": "No se pudo crear la sesión — prueba una plantilla.",
  "workout.fewerRounds": "Menos rondas",
  "workout.moreRounds": "Más rondas",
  "workout.adjustPrompt": "Esto es lo que quiero cambiar: ",
  "workout.adjustIntro": "Ajústame este entreno",

  "player.getReady": "Prepárate",
  "player.rest": "Descanso",
  "player.roundRest": "Descanso de ronda",
  "player.next": "Siguiente",
  "player.complete": "¡Entreno completado!",
  "player.logging": "Registrando en el entrenamiento…",
  "player.logged": "✓ Registrado en el entrenamiento",
  "player.logFailed": "No se pudo registrar — cuenta igualmente.",
  "player.notLogged": "No registrado.",
  "player.quitTitle": "¿Salir del entreno?",
  "player.keepGoing": "Seguir 💪",
  "player.quit": "Salir",
  "player.sessionPlan": "Plan de la sesión",
  "player.beeps": "🔔 Pitidos",
  "player.voice": "🗣 Voz",
  "player.addRest": "+15s descanso",
  "player.exitWorkout": "Salir del entreno",
  "player.showPlan": "Ver plan de la sesión",
  "player.pause": "Pausa",
  "player.resume": "Continuar",
  "player.skip": "Saltar",
  "player.previous": "Anterior",
  "player.exerciseOf": "Ejercicio",

  "chat.placeholder": "Pregunta a Brocco...",
  "chat.send": "Enviar",
  "chat.kitchenPlaceholder": "¿Qué tienes en la nevera?",
  "chat.listening": "Escuchando…",
  "chat.listeningNoLive": "Escuchando… (las palabras aparecen al parar)",
  "chat.conversations": "Conversaciones",
  "chat.kitchenChats": "Chats de cocina",
  "chat.newConversation": "+ Nueva conversación",
  "chat.weekCheckin": "📊 Resumen semanal",
  "chat.reconnecting": "Conexión perdida — esperando la respuesta de Brocco…",
  "chat.replyLost": "Se perdió la conexión y la respuesta no llegó. Tu mensaje vuelve a estar en el cuadro — envíalo de nuevo.",
  "chat.weekCheckinMsg": "Dame un resumen rápido de mi semana: qué está hecho, qué se ha perdido o está sin confirmar, y qué viene después.",
  "chat.voiceInput": "Entrada de voz",
  "chat.transcribing": "Transcribiendo...",
  "chat.stopRecording": "Detener grabación",
  "chat.cooking": "¿Qué cocinamos?",
  "chat.cookingSub": "Dime qué hay en la nevera y te sugiero algo — incluyendo tus recetas guardadas y tu despensa.",

  "history.title": "Historial",
  "history.all": "Todo",
  "history.runs": "Carreras",
  "history.rides": "Ciclismo",
  "history.strength": "Fuerza",
  "history.climbs": "Escalada",
  "history.other": "Otros",
  "history.noActivities": "Aún no hay actividades.",
  "history.loadMore": "Cargar más",
  "history.trends": "Tendencias",

  "settings.title": "Ajustes",
  "settings.profile": "Perfil",
  "settings.name": "Nombre",
  "settings.email": "Correo",
  "settings.timezone": "Zona horaria",
  "settings.language": "Idioma",
  "settings.languageHint": "Brocco también escribe en este idioma — chat, resúmenes, entrenos y planes.",
  "settings.primarySport": "Deporte principal",
  "settings.primarySportHint": "Brocco entrena este deporte primero: sesiones y minutos en vez de kilómetros. Tu plan actual no cambia.",
  "sport.running": "Correr",
  "sport.climbing": "Escalada",
  "sport.cycling": "Ciclismo",
  "sport.swimming": "Natación",
  "sport.triathlon": "Triatlón",
  "sport.hyrox": "Hyrox",
  "settings.goalRace": "Carrera objetivo",
  "settings.goalTime": "Tiempo objetivo",
  "settings.raceDate": "Fecha de la carrera",
  "settings.maxHr": "Frecuencia cardíaca máxima",
  "settings.features": "Funciones",
  "settings.notifications": "Notificaciones",
  "settings.strava": "Strava",
  "settings.connected": "Conectado",
  "settings.syncNow": "Sincronizar ahora",
  "settings.syncing": "Sincronizando...",
  "settings.disconnect": "Desconectar",
  "settings.lastSynced": "Última sincronización",
  "settings.never": "nunca",
  "settings.stravaExpired": "El acceso a Strava caducó o fue revocado — las actividades ya no se sincronizan.",
  "settings.reconnectStrava": "Reconectar Strava",
  "settings.connectStravaHint": "Conecta tu cuenta de Strava para importar actividades.",
  "settings.connectWithStrava": "Conectar con Strava",
  "settings.watchSync": "Sincronización con reloj",
  "settings.changePassword": "Cambiar contraseña",
  "settings.account": "Cuenta",
  "settings.logout": "Cerrar sesión",
  "settings.deleteAccount": "Eliminar cuenta",
  "settings.installApp": "Instalar app",
  "settings.calendarFeed": "Feed de calendario",
  "settings.equipment": "Equipo",

  "more.planDesc": "Fases, objetivos semanales, cuenta atrás de la carrera",
  "more.historyDesc": "Todas las actividades pasadas",
  "more.workoutsDesc": "Sesiones guiadas de fuerza y temporizadores",
  "more.kitchenDesc": "Recetario, escaneo de fotos, ideas de cocina",
  "more.settingsDesc": "Perfil, funciones, Strava, notificaciones",
  "more.trainingPlan": "Plan de entrenamiento",
  "confirm.didItHappen": "¿La hiciste?",
  "confirm.done": "Hecha",
  "confirm.skipped": "Saltada",
  "confirm.notConfirmed": "Sin confirmar",
  "confirm.notConfirmedHint": "no se puede detectar automáticamente",
  "confirm.markDone": "Marcar como hecha",
  "confirm.markedDone": "Registrada",
  "confirm.markedSkipped": "Marcada como saltada",
  "confirm.yesterday": "Ayer",
  "unit.page": "página",
  "unit.pages": "páginas",
  "unit.week": "semana",
  "unit.weeks": "semanas",
  "auth.login": "Iniciar sesión",
  "auth.signup": "Registrarse",
  "auth.password": "Contraseña",
  "auth.forgotPassword": "¿Olvidaste tu contraseña?",
  "auth.resetPassword": "Restablecer contraseña",
  "auth.accessCode": "Código de acceso",
  "auth.loggingIn": "Iniciando sesión…",
};

// One merged map per language. Areas live in src/lib/dict/*.ts so several
// people (or agents) can extend the dictionary without editing one file.
export const EN = { ...BASE_EN, ...history.en, ...settings.en, ...auth.en, ...workout.en, ...screens.en, ...server.en };
export type DictKey = keyof typeof EN;
const DE: Partial<Record<DictKey, string>> = { ...BASE_DE, ...history.de, ...settings.de, ...auth.de, ...workout.de, ...screens.de, ...server.de };
const ES: Partial<Record<DictKey, string>> = { ...BASE_ES, ...history.es, ...settings.es, ...auth.es, ...workout.es, ...screens.es, ...server.es };

export const DICTS: Record<Lang, Partial<Record<DictKey, string>>> = { en: EN, de: DE, es: ES };

/** Translator for a language. Missing keys fall back to English. */
export function translator(lang: Lang) {
  const d = DICTS[lang] || EN;
  return (key: DictKey): string => d[key] ?? EN[key];
}
