/**
 * Dictionary partial — "history" area (History list + Activity detail).
 * Merged into src/lib/dict.ts.
 * Every key needs all three languages; scripts/check-i18n.ts enforces it.
 */
export const en = {
  // History list
  "history.activityHistory": "Activity History",
  "history.activityOne": "activity",
  "history.activityMany": "activities",
  "history.manual": "(manual)",
  "history.distance": "Distance",
  "history.duration": "Duration",
  "history.pace": "Pace",
  "history.avgHr": "Avg HR",
  "history.bpm": "bpm",
  "history.elevation": "Elevation",
  "history.hoursShort": "h",
  "history.minutesShort": "m",
  "history.hikeWalk": "Hike & Walk",
  "history.swim": "Swim",
  "history.connectStravaPrefix": "Connect Strava in",
  "history.connectStravaSuffix": "to import your activities.",
  // Trends cards
  "history.sessionsPerWeek": "Sessions per week · minutes by sport",
  "history.sessionOne": "session",
  "history.sessionMany": "sessions",
  "history.kindClimb": "climb",
  "history.kindStrength": "strength",
  "history.kindRun": "run",
  "history.kindRide": "ride",
  "history.kindOther": "other",
  "history.numberIsSessions": "number = sessions that week",
  "history.bestEfforts90": "Best efforts · last 90 days",
  "history.oneMile": "1 mile",
  "history.vsPrev90": "vs. the 90 days before — ▼ faster, ▲ slower",
  "history.weeklyIntensity": "Weekly intensity mix (Z1–Z5)",
  "history.hard": "hard",
  "history.hardShare": "Hard share (Z4+Z5)",

  // Activity detail
  "activity.notFound": "Activity not found.",
  "activity.backToHistory": "Back to history",
  "activity.viewOnStrava": "View on Strava",
  "activity.dateAtTime": "{date} at {time}",
  "activity.matched": "Matched:",
  "activity.planned": "Planned:",
  "activity.actual": "Actual:",
  "activity.avg": "avg",
  "activity.movingTime": "Moving time",
  "activity.avgPace": "Avg pace",
  "activity.maxHr": "Max HR",
  "activity.cadence": "Cadence",
  "activity.spm": "spm",
  "activity.avgPower": "Avg power",
  "activity.calories": "Calories",
  "activity.effort": "Effort",
  "activity.laps": "Laps",
  "activity.splits": "Splits",
  // Tables
  "activity.lap": "Lap",
  "activity.dist": "Dist",
  "activity.time": "Time",
  "activity.pace": "Pace",
  "activity.hr": "HR",
  "activity.power": "Power",
  "activity.kmHeader": "KM",
  "activity.rep": "Rep",
  "activity.recovery": "Recovery",
  "activity.bestEffortsInRun": "Best efforts in this run",
  // Zones & intensity
  "activity.z1": "Z1 · Very light",
  "activity.z2": "Z2 · Easy",
  "activity.z3": "Z3 · Moderate",
  "activity.z4": "Z4 · Hard",
  "activity.z5": "Z5 · Max",
  "activity.harderThanPlanned": "Harder than planned",
  "activity.easierThanPlanned": "Easier than planned",
  "activity.intensity": "Intensity",
  "activity.analyzing": "Analyzing…",
  "activity.reanalyze": "Re-analyze",
  "activity.analyzeRun": "Analyze this run",
  "activity.analysisFailed": "Analysis failed",
  "activity.noAnalysis":
    "No intensity analysis yet — pulls second-by-second heart rate and pace from Strava to break down effort by zone.",
  "activity.cardiacDrift": "Cardiac drift",
  "activity.negativeSplit": "Negative split",
  "activity.paceFade": "Pace fade",
  "activity.effortReps": "Effort reps",
  "activity.hardEffortBlock": "Hard effort block",
  "activity.moreActions": "More actions",
  "activity.editSession": "Edit session",
  "activity.nameLabel": "Name",
  "activity.typeLabel": "Type",
  "activity.distanceKmLabel": "Distance (km)",
  "activity.durationMinLabel": "Duration (min)",
  "activity.rpeLabel": "Effort (RPE)",
  "activity.rpeHint": "1 = very easy · 10 = all-out",
  "activity.rpeClear": "No rating",
  "activity.notesLabel": "Notes",
  "activity.notesPlaceholder": "How did it go? Legs, sleep, shoes, weather…",
  "activity.deleteTitle": "Delete this session?",
  "activity.deleteBody": "This removes the session from your history. A Strava activity will not be re-imported.",
  "activity.deleting": "Deleting…",
  "activity.deleted": "Session deleted",
  "activity.saveFailed": "Couldn't save the changes",
  "activity.deleteFailed": "Couldn't delete the session",
} as const;

export const de: Partial<Record<keyof typeof en, string>> = {
  "history.activityHistory": "Aktivitätsverlauf",
  "history.activityOne": "Aktivität",
  "history.activityMany": "Aktivitäten",
  "history.manual": "(manuell)",
  "history.distance": "Distanz",
  "history.duration": "Dauer",
  "history.pace": "Tempo",
  "history.avgHr": "Ø Puls",
  "history.bpm": "bpm",
  "history.elevation": "Höhenmeter",
  "history.hoursShort": "h",
  "history.minutesShort": "min",
  "history.hikeWalk": "Wandern & Gehen",
  "history.swim": "Schwimmen",
  "history.connectStravaPrefix": "Verbinde Strava in den",
  "history.connectStravaSuffix": "um deine Aktivitäten zu importieren.",
  "history.sessionsPerWeek": "Einheiten pro Woche · Minuten je Sportart",
  "history.sessionOne": "Einheit",
  "history.sessionMany": "Einheiten",
  "history.kindClimb": "Klettern",
  "history.kindStrength": "Kraft",
  "history.kindRun": "Laufen",
  "history.kindRide": "Rad",
  "history.kindOther": "Sonstiges",
  "history.numberIsSessions": "Zahl = Einheiten in dieser Woche",
  "history.bestEfforts90": "Bestleistungen · letzte 90 Tage",
  "history.oneMile": "1 Meile",
  "history.vsPrev90": "vs. die 90 Tage davor — ▼ schneller, ▲ langsamer",
  "history.weeklyIntensity": "Wöchentlicher Intensitätsmix (Z1–Z5)",
  "history.hard": "hart",
  "history.hardShare": "Harter Anteil (Z4+Z5)",

  "activity.notFound": "Aktivität nicht gefunden.",
  "activity.backToHistory": "Zurück zum Verlauf",
  "activity.viewOnStrava": "Auf Strava ansehen",
  "activity.dateAtTime": "{date} um {time}",
  "activity.matched": "Zugeordnet:",
  "activity.planned": "Geplant:",
  "activity.actual": "Tatsächlich:",
  "activity.avg": "Ø",
  "activity.movingTime": "Bewegungszeit",
  "activity.avgPace": "Ø Tempo",
  "activity.maxHr": "Max. Puls",
  "activity.cadence": "Kadenz",
  "activity.spm": "Schritte/min",
  "activity.avgPower": "Ø Leistung",
  "activity.calories": "Kalorien",
  "activity.effort": "Anstrengung",
  "activity.laps": "Runden",
  "activity.splits": "Splits",
  "activity.lap": "Runde",
  "activity.dist": "Dist.",
  "activity.time": "Zeit",
  "activity.pace": "Tempo",
  "activity.hr": "Puls",
  "activity.power": "Leistung",
  "activity.kmHeader": "KM",
  "activity.rep": "Wdh.",
  "activity.recovery": "Erholung",
  "activity.bestEffortsInRun": "Bestleistungen in diesem Lauf",
  "activity.z1": "Z1 · Sehr leicht",
  "activity.z2": "Z2 · Locker",
  "activity.z3": "Z3 · Moderat",
  "activity.z4": "Z4 · Hart",
  "activity.z5": "Z5 · Maximal",
  "activity.harderThanPlanned": "Härter als geplant",
  "activity.easierThanPlanned": "Leichter als geplant",
  "activity.intensity": "Intensität",
  "activity.analyzing": "Analysiere…",
  "activity.reanalyze": "Neu analysieren",
  "activity.analyzeRun": "Diesen Lauf analysieren",
  "activity.analysisFailed": "Analyse fehlgeschlagen",
  "activity.noAnalysis":
    "Noch keine Intensitätsanalyse — holt Puls und Tempo sekundengenau von Strava und schlüsselt die Belastung nach Zonen auf.",
  "activity.cardiacDrift": "Pulsdrift",
  "activity.negativeSplit": "Negativer Split",
  "activity.paceFade": "Tempoabfall",
  "activity.effortReps": "Belastungsintervalle",
  "activity.hardEffortBlock": "Harter Belastungsblock",
  "activity.moreActions": "Weitere Aktionen",
  "activity.editSession": "Einheit bearbeiten",
  "activity.nameLabel": "Name",
  "activity.typeLabel": "Sportart",
  "activity.distanceKmLabel": "Distanz (km)",
  "activity.durationMinLabel": "Dauer (min)",
  "activity.rpeLabel": "Anstrengung (RPE)",
  "activity.rpeHint": "1 = sehr leicht · 10 = alles gegeben",
  "activity.rpeClear": "Keine Bewertung",
  "activity.notesLabel": "Notizen",
  "activity.notesPlaceholder": "Wie lief es? Beine, Schlaf, Schuhe, Wetter…",
  "activity.deleteTitle": "Diese Einheit löschen?",
  "activity.deleteBody": "Das entfernt die Einheit aus deinem Verlauf. Eine Strava-Aktivität wird nicht erneut importiert.",
  "activity.deleting": "Wird gelöscht…",
  "activity.deleted": "Einheit gelöscht",
  "activity.saveFailed": "Änderungen konnten nicht gespeichert werden",
  "activity.deleteFailed": "Einheit konnte nicht gelöscht werden",
};

export const es: Partial<Record<keyof typeof en, string>> = {
  "history.activityHistory": "Historial de actividades",
  "history.activityOne": "actividad",
  "history.activityMany": "actividades",
  "history.manual": "(manual)",
  "history.distance": "Distancia",
  "history.duration": "Duración",
  "history.pace": "Ritmo",
  "history.avgHr": "FC media",
  "history.bpm": "ppm",
  "history.elevation": "Desnivel",
  "history.hoursShort": "h",
  "history.minutesShort": "min",
  "history.hikeWalk": "Senderismo y caminata",
  "history.swim": "Natación",
  "history.connectStravaPrefix": "Conecta Strava en",
  "history.connectStravaSuffix": "para importar tus actividades.",
  "history.sessionsPerWeek": "Sesiones por semana · minutos por deporte",
  "history.sessionOne": "sesión",
  "history.sessionMany": "sesiones",
  "history.kindClimb": "escalada",
  "history.kindStrength": "fuerza",
  "history.kindRun": "carrera",
  "history.kindRide": "bici",
  "history.kindOther": "otros",
  "history.numberIsSessions": "número = sesiones de esa semana",
  "history.bestEfforts90": "Mejores marcas · últimos 90 días",
  "history.oneMile": "1 milla",
  "history.vsPrev90": "vs. los 90 días anteriores — ▼ más rápido, ▲ más lento",
  "history.weeklyIntensity": "Mezcla de intensidad semanal (Z1–Z5)",
  "history.hard": "duro",
  "history.hardShare": "Parte dura (Z4+Z5)",

  "activity.notFound": "Actividad no encontrada.",
  "activity.backToHistory": "Volver al historial",
  "activity.viewOnStrava": "Ver en Strava",
  "activity.dateAtTime": "{date} a las {time}",
  "activity.matched": "Emparejado:",
  "activity.planned": "Planificado:",
  "activity.actual": "Real:",
  "activity.avg": "media",
  "activity.movingTime": "Tiempo en movimiento",
  "activity.avgPace": "Ritmo medio",
  "activity.maxHr": "FC máx.",
  "activity.cadence": "Cadencia",
  "activity.spm": "pasos/min",
  "activity.avgPower": "Potencia media",
  "activity.calories": "Calorías",
  "activity.effort": "Esfuerzo",
  "activity.laps": "Vueltas",
  "activity.splits": "Parciales",
  "activity.lap": "Vuelta",
  "activity.dist": "Dist.",
  "activity.time": "Tiempo",
  "activity.pace": "Ritmo",
  "activity.hr": "FC",
  "activity.power": "Potencia",
  "activity.kmHeader": "KM",
  "activity.rep": "Rep.",
  "activity.recovery": "Recuperación",
  "activity.bestEffortsInRun": "Mejores marcas de esta carrera",
  "activity.z1": "Z1 · Muy suave",
  "activity.z2": "Z2 · Suave",
  "activity.z3": "Z3 · Moderado",
  "activity.z4": "Z4 · Duro",
  "activity.z5": "Z5 · Máximo",
  "activity.harderThanPlanned": "Más duro de lo planeado",
  "activity.easierThanPlanned": "Más suave de lo planeado",
  "activity.intensity": "Intensidad",
  "activity.analyzing": "Analizando…",
  "activity.reanalyze": "Volver a analizar",
  "activity.analyzeRun": "Analizar esta carrera",
  "activity.analysisFailed": "El análisis falló",
  "activity.noAnalysis":
    "Aún no hay análisis de intensidad — obtiene el pulso y el ritmo segundo a segundo de Strava para desglosar el esfuerzo por zonas.",
  "activity.cardiacDrift": "Deriva cardíaca",
  "activity.negativeSplit": "Split negativo",
  "activity.paceFade": "Caída de ritmo",
  "activity.effortReps": "Repeticiones de esfuerzo",
  "activity.hardEffortBlock": "Bloque de esfuerzo duro",
  "activity.moreActions": "Más acciones",
  "activity.editSession": "Editar sesión",
  "activity.nameLabel": "Nombre",
  "activity.typeLabel": "Tipo",
  "activity.distanceKmLabel": "Distancia (km)",
  "activity.durationMinLabel": "Duración (min)",
  "activity.rpeLabel": "Esfuerzo (RPE)",
  "activity.rpeHint": "1 = muy fácil · 10 = al máximo",
  "activity.rpeClear": "Sin valoración",
  "activity.notesLabel": "Notas",
  "activity.notesPlaceholder": "¿Cómo fue? Piernas, sueño, zapatillas, tiempo…",
  "activity.deleteTitle": "¿Eliminar esta sesión?",
  "activity.deleteBody": "Esto quita la sesión de tu historial. Una actividad de Strava no se volverá a importar.",
  "activity.deleting": "Eliminando…",
  "activity.deleted": "Sesión eliminada",
  "activity.saveFailed": "No se pudieron guardar los cambios",
  "activity.deleteFailed": "No se pudo eliminar la sesión",
};
