/**
 * Dictionary partial — "screens" area. Merged into src/lib/dict.ts.
 * Every key needs all three languages; scripts/check-i18n.ts enforces it.
 */
export const en = {
  "today.continuesFrom": "Continues from an earlier day",
  "today.allDay": "all day",
  "today.endsAt": "ends {t}",
  "today.continuesAllDay": "continues all day",
  "today.until": "until {t}",
  "today.recurring": "Recurring",
  "today.restDay": "Rest day — recovery is training too.",
  "today.planned": "Planned",
  "today.guidedSession": "guided session",
  "today.trainingPlan": "training plan",
  "today.completed": "completed",
  "today.bpm": "bpm",
  "today.unplanned": "Unplanned",
  "today.spontaneous": "spontaneous",
  "today.briefingFallback": "Have a good one. Open the chat if you want to talk anything through.",
  "today.more": "more",
  "today.less": "less",
  "today.failedLoad": "Failed to load.",
  "today.yourPlan": "Your plan",
  "today.connectStravaFirst": "Connect Strava first",
  "today.connectStravaFirstSub": "Brocco reads your history and builds the plan around it",
  "today.buildWithout": "Or build a plan without it",
  "today.buildWithoutSub": "Brocco will ask you a few questions instead",
  "today.buildMyPlan": "Build my training plan",
  "today.buildMyPlanSub": "Chat with Brocco to create one",
  "today.clearDay": "Clear day ahead",
  "today.noTraining": "No training today",
  "today.nothingScheduledAsk": "Nothing scheduled. Ask Brocco if you want to add something.",
  "today.openChat": "Open chat with Brocco",
  "today.msgBuildPlan": "I'd like to build a training plan",
  "plan.weekAbbr": "W",
  "plan.race": "race",
  "plan.newPlan": "+ New plan",
  "plan.starting": "Starting...",
  "plan.noPlanSub": "Let Brocco build you a personalized plan.",
  "plan.notStarted": "This block hasn't started yet",
  "plan.finished": "This block is finished",
  "plan.week1Begins": "Week 1 begins {date}.",
  "plan.askNext": "Ask Brocco for the next one when you're ready.",
  "plan.barTooltip": "Week {n}: {v} target",
  "plan.msgNewPlan": "I'd like to build a new training plan",
  "plan.msgExplain": "Explain my training plan to me — what's the thinking behind the phases and the weekly volumes, and how should I approach the block?",
  "chat.errorPrefix": "Error:",
  "chat.kitchenTitle": "Brocco's kitchen 🍳",
  "calendar.trainingPlan": "training plan",
  "calendar.noTarget": "no target set — run it by feel",
  "calendar.workoutType.easy": "easy run",
  "calendar.workoutType.long": "long run",
  "calendar.workoutType.tempo": "tempo run",
  "calendar.workoutType.interval": "interval session",
  "calendar.workoutType.race_pace": "race-pace session",
  "calendar.workoutType.recovery": "recovery run",
  "calendar.workoutType.rest": "rest day",
  "calendar.workoutType.cross_training": "cross-training session",
  "calendar.workoutType.strength": "strength session",
  "calendar.workoutType.race": "race",
  "calendar.workoutType.climbing": "climbing session",
  "calendar.completed": "completed",
  "calendar.logged": "logged",
  "calendar.todayPlaceholder": "— today",
  "calendar.step.steady": "Steady",
  "calendar.step.work": "Work",
  "calendar.step.recovery": "Recovery",
  "calendar.theSession": "The session",
  "calendar.hr": "HR",
  "calendar.target": "Target",
  "calendar.whyThisSession": "Why this session",
  "calendar.changed": "Changed {date}",
  "calendar.loadingDetail": "Loading the rest of this session…",
  "calendar.detailFailed": "Couldn't load the rest of this session.",
  "calendar.lastOf": "Last {type}",
  "calendar.similarSession": "similar session",
  "calendar.lastSimilar": "Last similar session",
  "calendar.nothingComparable": "Nothing comparable in the last six months.",
  "calendar.tapForActivity": "tap for the full activity",
  "calendar.markedComplete": "marked complete",
  "calendar.nothingMatching": "Nothing matching was logged this day.",
  "calendar.notLoggedOpenPlan": "Not logged yet — open in the plan →",
  "calendar.openInPlan": "Open in the plan →",
  "calendar.nothingWasPlanned": "Nothing was planned for this day.",
  "calendar.nothingPlanned": "Nothing planned for this day.",
  "calendar.alsoDone": "Also done",
  "calendar.doneAnyway": "Done anyway",
  "calendar.moreItems": "+{n} more",
  "calendar.legendDone": "Done",
  "calendar.legendMissed": "Missed",
  "calendar.legendPlanned": "Planned — colour by session type",
  "calendar.legendEvent": "Event — colour by category",
  "calendar.repeats": "repeats",
  "event.edit": "Edit event",
  "event.add": "Add event",
  "event.title": "Title",
  "event.allDay": "All-day",
  "event.to": "to",
  "event.endsOn": "Ends on",
  "event.endsOnHint": "Leave empty for a single-day event",
  "event.clear": "clear",
  "event.location": "Location (optional)",
  "event.notes": "Notes (optional)",
  "event.noRepeat": "Does not repeat",
  "event.daily": "Daily",
  "event.weekly": "Weekly",
  "event.monthly": "Monthly",
  "event.yearly": "Yearly",
  "event.repeatUntil": "Repeat until (optional)",
  "event.noReminder": "No reminder",
  "event.atStart": "At start",
  "event.min15Before": "15 min before",
  "event.hourBefore": "1 hour before",
  "event.dayBefore": "1 day before",
  "event.saveChanges": "Save changes",
  "event.category.work": "Work",
  "event.category.family": "Family",
  "event.category.training": "Training",
  "event.category.social": "Social",
  "event.category.health": "Health",
  "event.category.birthday": "Birthday",
  "event.category.other": "Other",
  "recipe.saveFailed": "Couldn't save — check the fields.",
  "recipe.saved": "Saved: {title}",
  "recipe.deleted": "Deleted: {title}",
  "recipe.cookedToast": "Enjoy! 🥦 Logged: {title}",
  "recipe.scannedCheck": "📸 Scanned — check it over",
  "recipe.edit": "Edit recipe",
  "recipe.title": "Title",
  "recipe.servings": "Servings",
  "recipe.timeMin": "Time (min)",
  "recipe.tagsHint": "Tags, comma-separated",
  "recipe.ingredientsPerLine": "Ingredients — one per line",
  "recipe.stepsPerLine": "Steps — one per line",
  "recipe.discard": "Discard",
  "recipe.looksRight": "Looks right — save",
  "recipe.serving": "serving",
  "recipe.servingsUnit": "servings",
  "recipe.cookedTimes": "cooked {n}×",
  "recipe.ingredients": "Ingredients",
  "recipe.steps": "Steps",
  "recipe.iCookedThis": "I cooked this 🥦",
  "recipe.ingredient": "ingredient",
  "recipe.ingredientsUnit": "ingredients",
  "kitchen.staplesSaveFailed": "Couldn't save staples — try again.",
  "kitchen.alwaysInStock": "🧂 Always in stock",
  "kitchen.staplesHint": "Brocco assumes these in every recipe idea — no need to list them each time.",
  "kitchen.remove": "Remove {item}",
  "kitchen.staplesPlaceholder": "curry paste, chickpeas…",
  "kitchen.add": "Add",
  "kitchen.maxPages": "Max {n} pages per recipe.",
  "kitchen.scanFailed": "Scan failed — try again.",
  "kitchen.photosFailed": "Couldn't read those photos — try again.",
  "kitchen.scanRecipe": "Scan a recipe",
  "kitchen.scanRecipeSub": "Photo a cookbook page — multi-page works too",
  "kitchen.cookWithBrocco": "Cook with Brocco",
  "kitchen.cookWithBroccoSub": "Tell Brocco your ingredients, pick a recipe",
  "kitchen.scanPhotos": "Scan recipe photos",
  "kitchen.uploadImages": "Upload recipe images",
  "kitchen.orUpload": "or upload images from your device",
  "kitchen.recipePages": "📄 Recipe pages ({n}/{max})",
  "kitchen.pageN": "Page {n}",
  "kitchen.removePage": "Remove page {n}",
  "kitchen.addPage": "+ Add\npage",
  "kitchen.readingPages": "Reading pages…",
  "kitchen.scanButton": "Scan recipe",
  "kitchen.searchPlaceholder": "Search recipes, ingredients, tags…",
  "kitchen.noMatch": "No recipes match.",
  "kitchen.empty": "Your recipe library is empty.",
  "kitchen.emptyHint": "Photograph a recipe from a cookbook, or ask Brocco to save one from chat.",
  "shell.metaTitle": "brocco.run — Run like a broccoli",
  "shell.metaDescription": "Your personal AI running coach",
  "shell.installBanner": "Add brocco.run to your home screen for the best experience",
  "shell.showMe": "Show me",
  "shell.installTitle": "Install brocco.run",
  "shell.switchToSafari": "Switch to Safari first",
  "shell.safariOnly": "Only Safari can install web apps on iPhone. Open brocco.run in Safari, then follow these steps.",
  "shell.tapThe": "Tap the",
  "shell.share": "Share",
  "shell.iosStep1b": "button at the bottom of Safari",
  "shell.iosStep2a": "Scroll down and tap",
  "shell.addToHomeScreen": "Add to Home Screen",
  "shell.tap": "Tap",
  "shell.addButton": "Add",
  "shell.topRight": "in the top right",
  "shell.openFromHome": "Open brocco.run from your home screen — it works like a regular app!",
  "shell.tapTheMenu": "Tap the",
  "shell.menu": "⋮ menu",
  "shell.androidStep1b": "in the top right of Chrome",
  "shell.or": "or",
  "shell.installApp": "Install App",
  "shell.install": "Install",
  "shell.otherDevice": "On mobile, use your browser menu to add this site to your home screen for the best experience.",
  "shell.openIn": "Open brocco.run in",
  "shell.notChrome": "(not Chrome)",
  "shell.instIos2": "Tap the Share button at the bottom",
  "shell.instAndroid2": "Tap the three-dot menu (top right)",
  "shell.doneBang": "done!",
  "shell.useMenu": "Use your mobile browser menu to add this site to your home screen.",
  "shell.poweredBy": "Powered by",
  "shell.legal": "Legal",
  "chat.untitled": "New conversation",
  "chat.kitchenUntitled": "Kitchen chat",
  "calendar.workoutType.yoga": "yoga session",
  "calendar.preparing": "Preparing…",
  "calendar.startFailed": "Couldn't prepare the session. Try again in a moment.",
  "calendar.guidedSession": "Guided session — ready when you are",
} as const;

export const de: Partial<Record<keyof typeof en, string>> = {
  "today.continuesFrom": "Geht von einem früheren Tag weiter",
  "today.allDay": "ganztägig",
  "today.endsAt": "endet {t}",
  "today.continuesAllDay": "geht den ganzen Tag weiter",
  "today.until": "bis {t}",
  "today.recurring": "Wiederkehrend",
  "today.restDay": "Ruhetag — Erholung ist auch Training.",
  "today.planned": "Geplant",
  "today.guidedSession": "geführte Einheit",
  "today.trainingPlan": "Trainingsplan",
  "today.completed": "erledigt",
  "today.bpm": "bpm",
  "today.unplanned": "Ungeplant",
  "today.spontaneous": "spontan",
  "today.briefingFallback": "Hab einen guten Tag. Öffne den Chat, wenn du etwas besprechen willst.",
  "today.more": "mehr",
  "today.less": "weniger",
  "today.failedLoad": "Laden fehlgeschlagen.",
  "today.yourPlan": "Dein Plan",
  "today.connectStravaFirst": "Zuerst Strava verbinden",
  "today.connectStravaFirstSub": "Brocco liest deine Historie und baut den Plan darauf auf",
  "today.buildWithout": "Oder einen Plan ohne Strava erstellen",
  "today.buildWithoutSub": "Brocco stellt dir stattdessen ein paar Fragen",
  "today.buildMyPlan": "Meinen Trainingsplan erstellen",
  "today.buildMyPlanSub": "Erstell ihn im Chat mit Brocco",
  "today.clearDay": "Freier Tag",
  "today.noTraining": "Heute kein Training",
  "today.nothingScheduledAsk": "Nichts geplant. Frag Brocco, wenn du etwas hinzufügen willst.",
  "today.openChat": "Chat mit Brocco öffnen",
  "today.msgBuildPlan": "Ich möchte einen Trainingsplan erstellen",
  "plan.weekAbbr": "W",
  "plan.race": "Wettkampf",
  "plan.newPlan": "+ Neuer Plan",
  "plan.starting": "Startet...",
  "plan.noPlanSub": "Lass dir von Brocco einen persönlichen Plan erstellen.",
  "plan.notStarted": "Dieser Block hat noch nicht begonnen",
  "plan.finished": "Dieser Block ist abgeschlossen",
  "plan.week1Begins": "Woche 1 beginnt am {date}.",
  "plan.askNext": "Frag Brocco nach dem nächsten, wenn du bereit bist.",
  "plan.barTooltip": "Woche {n}: Ziel {v}",
  "plan.msgNewPlan": "Ich möchte einen neuen Trainingsplan erstellen",
  "plan.msgExplain": "Erklär mir meinen Trainingsplan — was steckt hinter den Phasen und den Wochenumfängen, und wie sollte ich den Block angehen?",
  "chat.errorPrefix": "Fehler:",
  "chat.kitchenTitle": "Broccos Küche 🍳",
  "calendar.trainingPlan": "Trainingsplan",
  "calendar.noTarget": "kein Ziel gesetzt — nach Gefühl laufen",
  "calendar.workoutType.easy": "lockerer Lauf",
  "calendar.workoutType.long": "langer Lauf",
  "calendar.workoutType.tempo": "Tempolauf",
  "calendar.workoutType.interval": "Intervalleinheit",
  "calendar.workoutType.race_pace": "Einheit im Wettkampftempo",
  "calendar.workoutType.recovery": "Regenerationslauf",
  "calendar.workoutType.rest": "Ruhetag",
  "calendar.workoutType.cross_training": "Alternativtraining",
  "calendar.workoutType.strength": "Krafteinheit",
  "calendar.workoutType.race": "Wettkampf",
  "calendar.workoutType.climbing": "Klettereinheit",
  "calendar.completed": "abgeschlossen",
  "calendar.logged": "eingetragen",
  "calendar.todayPlaceholder": "— heute",
  "calendar.step.steady": "Gleichmäßig",
  "calendar.step.work": "Belastung",
  "calendar.step.recovery": "Erholung",
  "calendar.theSession": "Die Einheit",
  "calendar.hr": "HF",
  "calendar.target": "Ziel",
  "calendar.whyThisSession": "Warum diese Einheit",
  "calendar.changed": "Geändert am {date}",
  "calendar.loadingDetail": "Der Rest der Einheit lädt…",
  "calendar.detailFailed": "Der Rest der Einheit konnte nicht geladen werden.",
  "calendar.lastOf": "Zuletzt: {type}",
  "calendar.similarSession": "ähnliche Einheit",
  "calendar.lastSimilar": "Letzte ähnliche Einheit",
  "calendar.nothingComparable": "Nichts Vergleichbares in den letzten sechs Monaten.",
  "calendar.tapForActivity": "antippen für die ganze Aktivität",
  "calendar.markedComplete": "als erledigt markiert",
  "calendar.nothingMatching": "An diesem Tag wurde nichts Passendes eingetragen.",
  "calendar.notLoggedOpenPlan": "Noch nicht eingetragen — im Plan öffnen →",
  "calendar.openInPlan": "Im Plan öffnen →",
  "calendar.nothingWasPlanned": "Für diesen Tag war nichts geplant.",
  "calendar.nothingPlanned": "Für diesen Tag ist nichts geplant.",
  "calendar.alsoDone": "Außerdem gemacht",
  "calendar.doneAnyway": "Trotzdem gemacht",
  "calendar.moreItems": "+{n} weitere",
  "calendar.legendDone": "Erledigt",
  "calendar.legendMissed": "Verpasst",
  "calendar.legendPlanned": "Geplant — Farbe nach Einheitstyp",
  "calendar.legendEvent": "Termin — Farbe nach Kategorie",
  "calendar.repeats": "wiederholt sich",
  "event.edit": "Termin bearbeiten",
  "event.add": "Termin hinzufügen",
  "event.title": "Titel",
  "event.allDay": "Ganztägig",
  "event.to": "bis",
  "event.endsOn": "Endet am",
  "event.endsOnHint": "Leer lassen für einen eintägigen Termin",
  "event.clear": "löschen",
  "event.location": "Ort (optional)",
  "event.notes": "Notizen (optional)",
  "event.noRepeat": "Wiederholt sich nicht",
  "event.daily": "Täglich",
  "event.weekly": "Wöchentlich",
  "event.monthly": "Monatlich",
  "event.yearly": "Jährlich",
  "event.repeatUntil": "Wiederholen bis (optional)",
  "event.noReminder": "Keine Erinnerung",
  "event.atStart": "Zu Beginn",
  "event.min15Before": "15 Min vorher",
  "event.hourBefore": "1 Stunde vorher",
  "event.dayBefore": "1 Tag vorher",
  "event.saveChanges": "Änderungen speichern",
  "event.category.work": "Arbeit",
  "event.category.family": "Familie",
  "event.category.training": "Training",
  "event.category.social": "Soziales",
  "event.category.health": "Gesundheit",
  "event.category.birthday": "Geburtstag",
  "event.category.other": "Sonstiges",
  "recipe.saveFailed": "Speichern fehlgeschlagen — prüf die Felder.",
  "recipe.saved": "Gespeichert: {title}",
  "recipe.deleted": "Gelöscht: {title}",
  "recipe.cookedToast": "Guten Appetit! 🥦 Eingetragen: {title}",
  "recipe.scannedCheck": "📸 Gescannt — schau es dir an",
  "recipe.edit": "Rezept bearbeiten",
  "recipe.title": "Titel",
  "recipe.servings": "Portionen",
  "recipe.timeMin": "Zeit (Min)",
  "recipe.tagsHint": "Tags, mit Komma getrennt",
  "recipe.ingredientsPerLine": "Zutaten — eine pro Zeile",
  "recipe.stepsPerLine": "Schritte — einer pro Zeile",
  "recipe.discard": "Verwerfen",
  "recipe.looksRight": "Passt — speichern",
  "recipe.serving": "Portion",
  "recipe.servingsUnit": "Portionen",
  "recipe.cookedTimes": "{n}× gekocht",
  "recipe.ingredients": "Zutaten",
  "recipe.steps": "Schritte",
  "recipe.iCookedThis": "Hab ich gekocht 🥦",
  "recipe.ingredient": "Zutat",
  "recipe.ingredientsUnit": "Zutaten",
  "kitchen.staplesSaveFailed": "Vorräte konnten nicht gespeichert werden — nochmal versuchen.",
  "kitchen.alwaysInStock": "🧂 Immer da",
  "kitchen.staplesHint": "Brocco setzt diese bei jeder Rezeptidee voraus — du musst sie nicht jedes Mal aufzählen.",
  "kitchen.remove": "{item} entfernen",
  "kitchen.staplesPlaceholder": "Currypaste, Kichererbsen…",
  "kitchen.add": "Hinzufügen",
  "kitchen.maxPages": "Maximal {n} Seiten pro Rezept.",
  "kitchen.scanFailed": "Scan fehlgeschlagen — nochmal versuchen.",
  "kitchen.photosFailed": "Die Fotos konnten nicht gelesen werden — nochmal versuchen.",
  "kitchen.scanRecipe": "Rezept scannen",
  "kitchen.scanRecipeSub": "Fotografiere eine Kochbuchseite — auch mehrere Seiten",
  "kitchen.cookWithBrocco": "Mit Brocco kochen",
  "kitchen.cookWithBroccoSub": "Sag Brocco deine Zutaten, such dir ein Rezept aus",
  "kitchen.scanPhotos": "Rezeptfotos scannen",
  "kitchen.uploadImages": "Rezeptbilder hochladen",
  "kitchen.orUpload": "oder Bilder vom Gerät hochladen",
  "kitchen.recipePages": "📄 Rezeptseiten ({n}/{max})",
  "kitchen.pageN": "Seite {n}",
  "kitchen.removePage": "Seite {n} entfernen",
  "kitchen.addPage": "+ Seite\nhinzufügen",
  "kitchen.readingPages": "Seiten werden gelesen…",
  "kitchen.scanButton": "Rezept scannen",
  "kitchen.searchPlaceholder": "Rezepte, Zutaten, Tags suchen…",
  "kitchen.noMatch": "Keine passenden Rezepte.",
  "kitchen.empty": "Deine Rezeptsammlung ist leer.",
  "kitchen.emptyHint": "Fotografiere ein Rezept aus einem Kochbuch oder bitte Brocco im Chat, eins zu speichern.",
  "shell.metaTitle": "brocco.run — Lauf wie ein Brokkoli",
  "shell.metaDescription": "Dein persönlicher KI-Laufcoach",
  "shell.installBanner": "Füge brocco.run zum Startbildschirm hinzu — so läuft es am besten",
  "shell.showMe": "Zeig mir wie",
  "shell.installTitle": "brocco.run installieren",
  "shell.switchToSafari": "Wechsle zuerst zu Safari",
  "shell.safariOnly": "Auf dem iPhone kann nur Safari Web-Apps installieren. Öffne brocco.run in Safari und folge dann diesen Schritten.",
  "shell.tapThe": "Tippe auf die Schaltfläche",
  "shell.share": "Teilen",
  "shell.iosStep1b": "unten in Safari",
  "shell.iosStep2a": "Scrolle nach unten und tippe auf",
  "shell.addToHomeScreen": "Zum Home-Bildschirm",
  "shell.tap": "Tippe auf",
  "shell.addButton": "Hinzufügen",
  "shell.topRight": "oben rechts",
  "shell.openFromHome": "Öffne brocco.run vom Startbildschirm — es funktioniert wie eine normale App!",
  "shell.tapTheMenu": "Tippe auf das",
  "shell.menu": "⋮ Menü",
  "shell.androidStep1b": "oben rechts in Chrome",
  "shell.or": "oder",
  "shell.installApp": "App installieren",
  "shell.install": "Installieren",
  "shell.otherDevice": "Auf dem Handy: Füge diese Seite über das Browsermenü zum Startbildschirm hinzu.",
  "shell.openIn": "Öffne brocco.run in",
  "shell.notChrome": "(nicht Chrome)",
  "shell.instIos2": "Tippe unten auf die Teilen-Schaltfläche",
  "shell.instAndroid2": "Tippe auf das Drei-Punkte-Menü (oben rechts)",
  "shell.doneBang": "fertig!",
  "shell.useMenu": "Füge diese Seite über das Menü deines mobilen Browsers zum Startbildschirm hinzu.",
  "shell.poweredBy": "Powered by",
  "shell.legal": "Rechtliches",
  "chat.untitled": "Neue Unterhaltung",
  "chat.kitchenUntitled": "Küchen-Chat",
  "calendar.workoutType.yoga": "Yoga-Einheit",
  "calendar.preparing": "Wird vorbereitet…",
  "calendar.startFailed": "Die Einheit konnte nicht vorbereitet werden. Versuch es gleich noch mal.",
  "calendar.guidedSession": "Geführte Einheit — starte, wenn du bereit bist",
};

export const es: Partial<Record<keyof typeof en, string>> = {
  "today.continuesFrom": "Continúa de un día anterior",
  "today.allDay": "todo el día",
  "today.endsAt": "termina {t}",
  "today.continuesAllDay": "continúa todo el día",
  "today.until": "hasta {t}",
  "today.recurring": "Recurrente",
  "today.restDay": "Día de descanso — recuperarse también es entrenar.",
  "today.planned": "Planificado",
  "today.guidedSession": "sesión guiada",
  "today.trainingPlan": "plan de entrenamiento",
  "today.completed": "completada",
  "today.bpm": "ppm",
  "today.unplanned": "No planificado",
  "today.spontaneous": "espontáneo",
  "today.briefingFallback": "Que tengas un buen día. Abre el chat si quieres comentar algo.",
  "today.more": "más",
  "today.less": "menos",
  "today.failedLoad": "No se pudo cargar.",
  "today.yourPlan": "Tu plan",
  "today.connectStravaFirst": "Conecta Strava primero",
  "today.connectStravaFirstSub": "Brocco lee tu historial y construye el plan a partir de él",
  "today.buildWithout": "O crea un plan sin Strava",
  "today.buildWithoutSub": "Brocco te hará unas preguntas en su lugar",
  "today.buildMyPlan": "Crear mi plan de entrenamiento",
  "today.buildMyPlanSub": "Habla con Brocco para crearlo",
  "today.clearDay": "Día despejado",
  "today.noTraining": "Hoy no hay entrenamiento",
  "today.nothingScheduledAsk": "Nada programado. Pregunta a Brocco si quieres añadir algo.",
  "today.openChat": "Abrir el chat con Brocco",
  "today.msgBuildPlan": "Quiero crear un plan de entrenamiento",
  "plan.weekAbbr": "S",
  "plan.race": "carrera",
  "plan.newPlan": "+ Nuevo plan",
  "plan.starting": "Empezando...",
  "plan.noPlanSub": "Deja que Brocco te cree un plan personalizado.",
  "plan.notStarted": "Este bloque aún no ha empezado",
  "plan.finished": "Este bloque ha terminado",
  "plan.week1Begins": "La semana 1 empieza el {date}.",
  "plan.askNext": "Pídele a Brocco el siguiente cuando estés listo.",
  "plan.barTooltip": "Semana {n}: objetivo {v}",
  "plan.msgNewPlan": "Quiero crear un nuevo plan de entrenamiento",
  "plan.msgExplain": "Explícame mi plan de entrenamiento: ¿qué hay detrás de las fases y los volúmenes semanales, y cómo debería afrontar el bloque?",
  "chat.errorPrefix": "Error:",
  "chat.kitchenTitle": "La cocina de Brocco 🍳",
  "calendar.trainingPlan": "plan de entrenamiento",
  "calendar.noTarget": "sin objetivo — corre por sensaciones",
  "calendar.workoutType.easy": "rodaje suave",
  "calendar.workoutType.long": "tirada larga",
  "calendar.workoutType.tempo": "rodaje tempo",
  "calendar.workoutType.interval": "sesión de series",
  "calendar.workoutType.race_pace": "sesión a ritmo de carrera",
  "calendar.workoutType.recovery": "rodaje de recuperación",
  "calendar.workoutType.rest": "día de descanso",
  "calendar.workoutType.cross_training": "sesión de entrenamiento cruzado",
  "calendar.workoutType.strength": "sesión de fuerza",
  "calendar.workoutType.race": "carrera",
  "calendar.workoutType.climbing": "sesión de escalada",
  "calendar.completed": "completada",
  "calendar.logged": "registrada",
  "calendar.todayPlaceholder": "— hoy",
  "calendar.step.steady": "Constante",
  "calendar.step.work": "Trabajo",
  "calendar.step.recovery": "Recuperación",
  "calendar.theSession": "La sesión",
  "calendar.hr": "FC",
  "calendar.target": "Objetivo",
  "calendar.whyThisSession": "Por qué esta sesión",
  "calendar.changed": "Cambiado el {date}",
  "calendar.loadingDetail": "Cargando el resto de la sesión…",
  "calendar.detailFailed": "No se pudo cargar el resto de la sesión.",
  "calendar.lastOf": "Última vez: {type}",
  "calendar.similarSession": "sesión similar",
  "calendar.lastSimilar": "Última sesión similar",
  "calendar.nothingComparable": "Nada comparable en los últimos seis meses.",
  "calendar.tapForActivity": "toca para ver la actividad completa",
  "calendar.markedComplete": "marcada como hecha",
  "calendar.nothingMatching": "Ese día no se registró nada que coincida.",
  "calendar.notLoggedOpenPlan": "Aún sin registrar — abrir en el plan →",
  "calendar.openInPlan": "Abrir en el plan →",
  "calendar.nothingWasPlanned": "No había nada planeado para este día.",
  "calendar.nothingPlanned": "Nada planeado para este día.",
  "calendar.alsoDone": "También hecho",
  "calendar.doneAnyway": "Hecho igualmente",
  "calendar.moreItems": "+{n} más",
  "calendar.legendDone": "Hecho",
  "calendar.legendMissed": "Perdida",
  "calendar.legendPlanned": "Planeado — color según tipo de sesión",
  "calendar.legendEvent": "Evento — color según categoría",
  "calendar.repeats": "se repite",
  "event.edit": "Editar evento",
  "event.add": "Añadir evento",
  "event.title": "Título",
  "event.allDay": "Todo el día",
  "event.to": "a",
  "event.endsOn": "Termina el",
  "event.endsOnHint": "Déjalo vacío para un evento de un solo día",
  "event.clear": "quitar",
  "event.location": "Lugar (opcional)",
  "event.notes": "Notas (opcional)",
  "event.noRepeat": "No se repite",
  "event.daily": "Diario",
  "event.weekly": "Semanal",
  "event.monthly": "Mensual",
  "event.yearly": "Anual",
  "event.repeatUntil": "Repetir hasta (opcional)",
  "event.noReminder": "Sin recordatorio",
  "event.atStart": "Al empezar",
  "event.min15Before": "15 min antes",
  "event.hourBefore": "1 hora antes",
  "event.dayBefore": "1 día antes",
  "event.saveChanges": "Guardar cambios",
  "event.category.work": "Trabajo",
  "event.category.family": "Familia",
  "event.category.training": "Entrenamiento",
  "event.category.social": "Social",
  "event.category.health": "Salud",
  "event.category.birthday": "Cumpleaños",
  "event.category.other": "Otro",
  "recipe.saveFailed": "No se pudo guardar — revisa los campos.",
  "recipe.saved": "Guardado: {title}",
  "recipe.deleted": "Eliminado: {title}",
  "recipe.cookedToast": "¡Que aproveche! 🥦 Registrado: {title}",
  "recipe.scannedCheck": "📸 Escaneada — revísala",
  "recipe.edit": "Editar receta",
  "recipe.title": "Título",
  "recipe.servings": "Raciones",
  "recipe.timeMin": "Tiempo (min)",
  "recipe.tagsHint": "Etiquetas, separadas por comas",
  "recipe.ingredientsPerLine": "Ingredientes — uno por línea",
  "recipe.stepsPerLine": "Pasos — uno por línea",
  "recipe.discard": "Descartar",
  "recipe.looksRight": "Está bien — guardar",
  "recipe.serving": "ración",
  "recipe.servingsUnit": "raciones",
  "recipe.cookedTimes": "cocinada {n}×",
  "recipe.ingredients": "Ingredientes",
  "recipe.steps": "Pasos",
  "recipe.iCookedThis": "Lo he cocinado 🥦",
  "recipe.ingredient": "ingrediente",
  "recipe.ingredientsUnit": "ingredientes",
  "kitchen.staplesSaveFailed": "No se pudieron guardar los básicos — inténtalo de nuevo.",
  "kitchen.alwaysInStock": "🧂 Siempre en casa",
  "kitchen.staplesHint": "Brocco da por hecho que los tienes en cada idea de receta — no hace falta listarlos cada vez.",
  "kitchen.remove": "Quitar {item}",
  "kitchen.staplesPlaceholder": "pasta de curry, garbanzos…",
  "kitchen.add": "Añadir",
  "kitchen.maxPages": "Máximo {n} páginas por receta.",
  "kitchen.scanFailed": "El escaneo falló — inténtalo de nuevo.",
  "kitchen.photosFailed": "No se pudieron leer esas fotos — inténtalo de nuevo.",
  "kitchen.scanRecipe": "Escanear una receta",
  "kitchen.scanRecipeSub": "Fotografía una página de un libro de cocina — varias páginas también valen",
  "kitchen.cookWithBrocco": "Cocina con Brocco",
  "kitchen.cookWithBroccoSub": "Dile a Brocco tus ingredientes y elige una receta",
  "kitchen.scanPhotos": "Escanear fotos de recetas",
  "kitchen.uploadImages": "Subir imágenes de recetas",
  "kitchen.orUpload": "o sube imágenes desde tu dispositivo",
  "kitchen.recipePages": "📄 Páginas de la receta ({n}/{max})",
  "kitchen.pageN": "Página {n}",
  "kitchen.removePage": "Quitar página {n}",
  "kitchen.addPage": "+ Añadir\npágina",
  "kitchen.readingPages": "Leyendo páginas…",
  "kitchen.scanButton": "Escanear receta",
  "kitchen.searchPlaceholder": "Buscar recetas, ingredientes, etiquetas…",
  "kitchen.noMatch": "Ninguna receta coincide.",
  "kitchen.empty": "Tu recetario está vacío.",
  "kitchen.emptyHint": "Fotografía una receta de un libro de cocina o pídele a Brocco que guarde una desde el chat.",
  "shell.metaTitle": "brocco.run — Corre como un brócoli",
  "shell.metaDescription": "Tu entrenador personal de running con IA",
  "shell.installBanner": "Añade brocco.run a tu pantalla de inicio para la mejor experiencia",
  "shell.showMe": "Enséñame",
  "shell.installTitle": "Instalar brocco.run",
  "shell.switchToSafari": "Cambia primero a Safari",
  "shell.safariOnly": "En iPhone solo Safari puede instalar apps web. Abre brocco.run en Safari y sigue estos pasos.",
  "shell.tapThe": "Toca el botón",
  "shell.share": "Compartir",
  "shell.iosStep1b": "en la parte inferior de Safari",
  "shell.iosStep2a": "Desplázate hacia abajo y toca",
  "shell.addToHomeScreen": "Añadir a pantalla de inicio",
  "shell.tap": "Toca",
  "shell.addButton": "Añadir",
  "shell.topRight": "arriba a la derecha",
  "shell.openFromHome": "Abre brocco.run desde tu pantalla de inicio — ¡funciona como una app normal!",
  "shell.tapTheMenu": "Toca el",
  "shell.menu": "⋮ menú",
  "shell.androidStep1b": "arriba a la derecha en Chrome",
  "shell.or": "o",
  "shell.installApp": "Instalar app",
  "shell.install": "Instalar",
  "shell.otherDevice": "En el móvil, usa el menú del navegador para añadir este sitio a tu pantalla de inicio.",
  "shell.openIn": "Abre brocco.run en",
  "shell.notChrome": "(no Chrome)",
  "shell.instIos2": "Toca el botón Compartir abajo",
  "shell.instAndroid2": "Toca el menú de tres puntos (arriba a la derecha)",
  "shell.doneBang": "¡listo!",
  "shell.useMenu": "Usa el menú de tu navegador móvil para añadir este sitio a tu pantalla de inicio.",
  "shell.poweredBy": "Con tecnología de",
  "shell.legal": "Legal",
  "chat.untitled": "Nueva conversación",
  "chat.kitchenUntitled": "Chat de cocina",
  "calendar.workoutType.yoga": "sesión de yoga",
  "calendar.preparing": "Preparando…",
  "calendar.startFailed": "No se pudo preparar la sesión. Inténtalo de nuevo en un momento.",
  "calendar.guidedSession": "Sesión guiada — cuando quieras",
};
