/**
 * Dictionary partial — "server" area. Merged into src/lib/dict.ts.
 * Every key needs all three languages; scripts/check-i18n.ts enforces it.
 *
 * Strings that API routes and background jobs produce for the USER: error
 * messages the client displays verbatim (`data.error`), fallback prose that
 * gets persisted when Brocco can't write it himself, push notification text,
 * and sync-health lines shown in Settings. `{name}` placeholders are filled
 * by the translator in src/lib/i18n-server.ts. Nothing here goes into a
 * model prompt — those stay English by design.
 *
 * Prefixes: "api." (route responses), "fallback." (persisted stand-in
 * prose), "push." (notifications).
 */
export const en = {
  // Generic
  "api.internalError": "Internal server error",
  "api.notFound": "Not found",
  "api.profileNotFound": "Profile not found",
  "api.userNotFound": "User not found",

  // Auth (login / signup / reset are unauthenticated — language comes from
  // the request, see requestTranslator)
  "api.auth.emailPasswordRequired": "Email and password are required",
  "api.auth.tooManyAttemptsMinutes": "Too many attempts. Try again in a few minutes.",
  "api.auth.tooManyAttemptsLater": "Too many attempts. Try again later.",
  "api.auth.invalidCredentials": "Invalid email or password",
  "api.auth.allFieldsRequired": "All fields are required",
  "api.auth.passwordMin": "Password must be at least 8 characters",
  "api.auth.wrongAccessCode": "Wrong access code — ask the person who invited you",
  "api.auth.emailRegistered": "Email already registered",
  "api.auth.emailRequired": "Email is required",
  "api.auth.tooManyRequests": "Too many requests. Try again in a few minutes.",
  "api.auth.resetSent": "If that address has an account, a reset link is on its way.",
  "api.auth.resetTokenMissing": "Reset token missing",
  "api.auth.resetLinkInvalid": "This reset link is invalid or has expired. Request a new one.",
  "api.auth.validEmail": "Enter a valid email address",
  "api.auth.currentPasswordRequired": "Current password is required",
  "api.auth.currentPasswordIncorrect": "Current password is incorrect",
  "api.auth.emailInUse": "That email is already in use",
  "api.auth.currentAndNewRequired": "Current and new password required",
  "api.auth.newPasswordMin": "New password must be at least 8 characters",
  "api.auth.passwordConfirmRequired": "Password required for confirmation",
  "api.auth.incorrectPassword": "Incorrect password",

  // Chat
  "api.chat.tooMany": "Too many messages — give Brocco a minute.",
  "api.chat.sessionNotFound": "Session not found",
  "api.chat.failed": "Something went wrong on my side — try that again.",
  "api.chat.done": "Done ✓",

  // Briefing / weekly review / opener
  "api.briefing.tooManyRefreshes": "Too many refreshes — the briefing is fresh enough.",
  "api.weeklyReview.tooManyForced": "Too many forced reviews.",
  "fallback.briefing.none": "Nothing on the calendar today.",
  "fallback.briefing.one": "1 thing on the calendar today.",
  "fallback.briefing.many": "{count} things on the calendar today.",
  "fallback.weeklyReview.sessions": "Week done: {completed}/{planned} sessions completed, {minutes} minutes trained.",
  "fallback.weeklyReview.km": "Week done: {km} km of {plannedKm} km planned, {completed}/{planned} sessions completed.",
  "fallback.opener": "Week check-in: {km} km of {plannedKm} km planned so far. What's on your mind?",

  // Guided workout generation
  "api.workoutGen.tooMany": "Too many workouts generated — take one of them and go train!",
  "api.workoutGen.plannedNotFound": "Planned workout not found",
  "api.workoutGen.failed": "Couldn't generate a workout — try again or use a preset.",

  // Activity analysis
  "api.analyze.nothing": "Nothing to analyze — no heart rate data, or no max HR set in Settings.",
  "api.analyze.failed": "Analysis failed",

  // Recipe scan
  "api.scan.limit": "Scan limit reached — try again in an hour.",
  "api.scan.imageRequired": "At least one image is required",
  "api.scan.imageInvalid": "Each image needs base64 data and a mediaType (jpeg/png/webp)",
  "api.scan.imageTooLarge": "Image too large — max ~3.5MB each",
  "api.scan.noRecipe": "Couldn't read a recipe from that photo — try a sharper shot.",
  "api.scan.noRecipeReason": "No recipe found: {reason}",
  "api.scan.incomplete": "Couldn't read a complete recipe — try a sharper photo.",
  "api.scan.failed": "Scan failed — try again.",

  // Voice
  "api.voice.tooMany": "Too many transcriptions — take a breath.",
  "api.voice.notConfigured": "Voice transcription not configured",
  "api.voice.noAudio": "No audio file provided",
  "api.voice.tooLarge": "Recording too large",
  "api.voice.failed": "Transcription failed",

  // Push
  "api.push.notConfigured": "Push is not configured on the server",
  "push.testTitle": "🥦 Brocco",
  "push.testBody": "Notifications are working on this device. Run like a broccoli!",
  "push.reminderBody": "at {time} (in {min} min)",

  // Strava (Settings shows the stored sync-health line verbatim)
  "api.strava.notConnected": "Strava not connected",
  "api.strava.syncRecently": "Sync already ran recently — give it an hour.",
  "api.strava.syncFailed": "Sync failed",
  "api.strava.revoked": "Strava access revoked or expired ({status}) — reconnect needed",
  "api.strava.webhookSyncFailed": "Webhook sync failed: {reason}",
  "api.strava.manualSyncFailed": "Manual sync failed: {reason}",
  "api.strava.autoSyncFailed": "Sync failed: {reason}",
  "api.strava.unknownError": "unknown error",

  // intervals.icu watch sync
  "api.intervals.credentialsRequired": "Athlete ID and API key are required",
  "api.intervals.rejectedKey": "intervals.icu rejected the API key — copy it again from intervals.icu Settings → Developer",
  "api.intervals.badStatus": "intervals.icu returned {status} — check the athlete ID (the number in your intervals.icu profile URL, e.g. i1234567 or just 1234567)",
  "api.intervals.unreachable": "Couldn't reach intervals.icu — try again",
  "api.intervals.notConnected": "Watch sync isn't connected",
  "api.intervals.syncFailed": "Sync failed — try again",

  // Brocco's tool notifications (chips/toasts in the chat)
  "notify.logged": "Logged: {detail}",
  "notify.severity.minor": "minor",
  "notify.severity.moderate": "moderate",
  "notify.severity.severe": "severe",
  "notify.activityLogged": "Logged: {description}",
  "notify.activityLoggedKm": "Logged: {description} ({km} km)",
  "notify.partlyApplied": "Partly applied — {failed} of {total} change(s) failed: {errors}",
  "notify.planChangesApplied": "Plan changes applied by Brocco",
  "notify.planCreated": "Plan created: {name}",
  "notify.tasksAdded.one": "Added 1 weekly task to your plan",
  "notify.tasksAdded.many": "Added {count} weekly tasks to your plan",
  "notify.eventRemovedOn": "{title} removed on {date}",
  "notify.eventDeleted": "{title} deleted",
  "notify.recipeSaved": "Recipe saved: {title}",
  "notify.recipeCooked": "Enjoy! Logged: {title}",
  "notify.recipeDeleted": "Recipe deleted: {title}",
  "notify.staplesAdded": "Pantry staples added: {items}",
  "notify.staplesRemoved": "Pantry staples removed: {items}",
  "notify.profileUpdated": "Profile updated: {fields}",
  "notify.field.name": "name",
  "notify.field.years_running": "years running",
  "notify.field.weekly_km_baseline": "weekly km baseline",
  "notify.field.goal_race": "goal race",
  "notify.field.goal_race_date": "goal race date",
  "notify.field.goal_time": "goal time",
  "notify.field.timezone": "timezone",
  "notify.field.primary_sport": "primary sport",
  "notify.field.equipment": "equipment ({count})",
  "notify.goalSet": "Weekly goal: {label} {target}× this week",
  "notify.goalSetDone": "Weekly goal: {label} {target}× this week ({done} already done)",
  "notify.goalRemoved": "Removed weekly goal: {label}",
  "notify.goalAttributed": "Session attributed to the right goal",
  "notify.goalDetached": "Session no longer counts towards a goal",

  // Validation (kitchen / workout screens display these verbatim)
  "api.validation.recipe.titleRequired": "A title is required (max {max} characters)",
  "api.validation.recipe.ingredientsRequired": "Add at least one ingredient",
  "api.validation.recipe.stepsRequired": "Add at least one step",
  "api.validation.recipe.servingsRange": "Servings must be a whole number {min}–{max}",
  "api.validation.recipe.timeMinRange": "Time must be {min}–{max} minutes",
  "api.validation.workout.titleRequired": "A title is required (max {max} characters)",
  "api.validation.workout.notObject": "The workout definition is invalid",
  "api.validation.workout.warmupRange": "Warm-up must be 0–{max} seconds",
  "api.validation.workout.cooldownRange": "Cool-down must be 0–{max} seconds",
  "api.validation.workout.blocksRange": "A workout needs 1–{max} blocks",
  "api.validation.workout.blockNotObject": "Block {block} is invalid",
  "api.validation.workout.roundsRange": "Block {block}: rounds must be a whole number 1–{max}",
  "api.validation.workout.restBetweenRoundsRange": "Block {block}: rest between rounds must be 0–{max} seconds",
  "api.validation.workout.exercisesRange": "Block {block} needs 1–{max} exercises",
  "api.validation.workout.exerciseNotObject": "Block {block}, exercise {exercise} is invalid",
  "api.validation.workout.nameRequired": "Block {block}, exercise {exercise}: a name is required (max {max} characters)",
  "api.validation.workout.modeInvalid": "Block {block}, exercise {exercise}: mode must be time or reps",
  "api.validation.workout.workSecRange": "Block {block}, exercise {exercise}: work time must be {min}–{max} seconds",
  "api.validation.workout.repsRange": "Block {block}, exercise {exercise}: reps must be a whole number {min}–{max}",
  "api.validation.workout.restSecRange": "Block {block}, exercise {exercise}: rest must be 0–{max} seconds",
} as const;

export const de: Partial<Record<keyof typeof en, string>> = {
  "api.internalError": "Interner Serverfehler",
  "api.notFound": "Nicht gefunden",
  "api.profileNotFound": "Profil nicht gefunden",
  "api.userNotFound": "Nutzer nicht gefunden",

  "api.auth.emailPasswordRequired": "E-Mail und Passwort sind erforderlich",
  "api.auth.tooManyAttemptsMinutes": "Zu viele Versuche. Versuch es in ein paar Minuten noch mal.",
  "api.auth.tooManyAttemptsLater": "Zu viele Versuche. Versuch es später noch mal.",
  "api.auth.invalidCredentials": "E-Mail oder Passwort falsch",
  "api.auth.allFieldsRequired": "Alle Felder sind Pflichtfelder",
  "api.auth.passwordMin": "Das Passwort muss mindestens 8 Zeichen haben",
  "api.auth.wrongAccessCode": "Falscher Zugangscode — frag die Person, die dich eingeladen hat",
  "api.auth.emailRegistered": "Diese E-Mail ist bereits registriert",
  "api.auth.emailRequired": "E-Mail ist erforderlich",
  "api.auth.tooManyRequests": "Zu viele Anfragen. Versuch es in ein paar Minuten noch mal.",
  "api.auth.resetSent": "Falls zu dieser Adresse ein Konto existiert, ist ein Link zum Zurücksetzen unterwegs.",
  "api.auth.resetTokenMissing": "Reset-Token fehlt",
  "api.auth.resetLinkInvalid": "Dieser Link ist ungültig oder abgelaufen. Fordere einen neuen an.",
  "api.auth.validEmail": "Gib eine gültige E-Mail-Adresse ein",
  "api.auth.currentPasswordRequired": "Das aktuelle Passwort ist erforderlich",
  "api.auth.currentPasswordIncorrect": "Das aktuelle Passwort ist falsch",
  "api.auth.emailInUse": "Diese E-Mail wird bereits verwendet",
  "api.auth.currentAndNewRequired": "Aktuelles und neues Passwort erforderlich",
  "api.auth.newPasswordMin": "Das neue Passwort muss mindestens 8 Zeichen haben",
  "api.auth.passwordConfirmRequired": "Zur Bestätigung ist das Passwort erforderlich",
  "api.auth.incorrectPassword": "Falsches Passwort",

  "api.chat.tooMany": "Zu viele Nachrichten — gib Brocco eine Minute.",
  "api.chat.sessionNotFound": "Unterhaltung nicht gefunden",
  "api.chat.failed": "Bei mir ist etwas schiefgelaufen — versuch es noch mal.",
  "api.chat.done": "Erledigt ✓",

  "api.briefing.tooManyRefreshes": "Zu oft aktualisiert — das Briefing ist frisch genug.",
  "api.weeklyReview.tooManyForced": "Zu viele erzwungene Wochenrückblicke.",
  "fallback.briefing.none": "Heute steht nichts im Kalender.",
  "fallback.briefing.one": "Heute steht 1 Termin im Kalender.",
  "fallback.briefing.many": "Heute stehen {count} Termine im Kalender.",
  "fallback.weeklyReview.sessions": "Woche geschafft: {completed}/{planned} Einheiten absolviert, {minutes} Minuten trainiert.",
  "fallback.weeklyReview.km": "Woche geschafft: {km} von {plannedKm} km geplant, {completed}/{planned} Einheiten absolviert.",
  "fallback.opener": "Wochen-Check-in: bisher {km} von {plannedKm} km geplant. Was beschäftigt dich?",

  "api.workoutGen.tooMany": "Zu viele Workouts erstellt — nimm eins davon und geh trainieren!",
  "api.workoutGen.plannedNotFound": "Geplantes Workout nicht gefunden",
  "api.workoutGen.failed": "Workout konnte nicht erstellt werden — versuch es noch mal oder nimm eine Vorlage.",

  "api.analyze.nothing": "Nichts zu analysieren — keine Herzfrequenzdaten oder keine max. HF in den Einstellungen.",
  "api.analyze.failed": "Analyse fehlgeschlagen",

  "api.scan.limit": "Scan-Limit erreicht — versuch es in einer Stunde noch mal.",
  "api.scan.imageRequired": "Mindestens ein Bild ist erforderlich",
  "api.scan.imageInvalid": "Jedes Bild braucht Base64-Daten und einen mediaType (jpeg/png/webp)",
  "api.scan.imageTooLarge": "Bild zu groß — max. ~3,5 MB pro Bild",
  "api.scan.noRecipe": "Auf dem Foto war kein Rezept zu erkennen — versuch ein schärferes Bild.",
  "api.scan.noRecipeReason": "Kein Rezept gefunden: {reason}",
  "api.scan.incomplete": "Das Rezept war nicht vollständig lesbar — versuch ein schärferes Foto.",
  "api.scan.failed": "Scan fehlgeschlagen — versuch es noch mal.",

  "api.voice.tooMany": "Zu viele Transkriptionen — hol kurz Luft.",
  "api.voice.notConfigured": "Sprachtranskription ist nicht eingerichtet",
  "api.voice.noAudio": "Keine Audiodatei übermittelt",
  "api.voice.tooLarge": "Aufnahme zu groß",
  "api.voice.failed": "Transkription fehlgeschlagen",

  "api.push.notConfigured": "Push ist auf dem Server nicht eingerichtet",
  "push.testTitle": "🥦 Brocco",
  "push.testBody": "Benachrichtigungen funktionieren auf diesem Gerät. Lauf wie ein Brokkoli!",
  "push.reminderBody": "um {time} (in {min} Min.)",

  "api.strava.notConnected": "Strava ist nicht verbunden",
  "api.strava.syncRecently": "Die Synchronisierung lief gerade erst — gib ihr eine Stunde.",
  "api.strava.syncFailed": "Synchronisierung fehlgeschlagen",
  "api.strava.revoked": "Strava-Zugriff widerrufen oder abgelaufen ({status}) — neu verbinden nötig",
  "api.strava.webhookSyncFailed": "Webhook-Synchronisierung fehlgeschlagen: {reason}",
  "api.strava.manualSyncFailed": "Manuelle Synchronisierung fehlgeschlagen: {reason}",
  "api.strava.autoSyncFailed": "Synchronisierung fehlgeschlagen: {reason}",
  "api.strava.unknownError": "unbekannter Fehler",

  "api.intervals.credentialsRequired": "Athleten-ID und API-Key sind erforderlich",
  "api.intervals.rejectedKey": "intervals.icu hat den API-Key abgelehnt — kopiere ihn erneut aus intervals.icu Settings → Developer",
  "api.intervals.badStatus": "intervals.icu hat {status} zurückgegeben — prüfe die Athleten-ID (die Nummer in deiner intervals.icu-Profil-URL, z. B. i1234567 oder nur 1234567)",
  "api.intervals.unreachable": "intervals.icu ist nicht erreichbar — versuch es noch mal",
  "api.intervals.notConnected": "Uhren-Sync ist nicht verbunden",
  "api.intervals.syncFailed": "Synchronisierung fehlgeschlagen — versuch es noch mal",

  // Brocco's tool notifications (chips/toasts in the chat)
  "notify.logged": "Notiert: {detail}",
  "notify.severity.minor": "leicht",
  "notify.severity.moderate": "mittel",
  "notify.severity.severe": "schwer",
  "notify.activityLogged": "Eingetragen: {description}",
  "notify.activityLoggedKm": "Eingetragen: {description} ({km} km)",
  "notify.partlyApplied": "Teilweise übernommen — {failed} von {total} Änderung(en) fehlgeschlagen: {errors}",
  "notify.planChangesApplied": "Planänderungen von Brocco übernommen",
  "notify.planCreated": "Plan erstellt: {name}",
  "notify.tasksAdded.one": "1 Wochenaufgabe zu deinem Plan hinzugefügt",
  "notify.tasksAdded.many": "{count} Wochenaufgaben zu deinem Plan hinzugefügt",
  "notify.eventRemovedOn": "{title} am {date} entfernt",
  "notify.eventDeleted": "{title} gelöscht",
  "notify.recipeSaved": "Rezept gespeichert: {title}",
  "notify.recipeCooked": "Guten Appetit! Eingetragen: {title}",
  "notify.recipeDeleted": "Rezept gelöscht: {title}",
  "notify.staplesAdded": "Vorräte hinzugefügt: {items}",
  "notify.staplesRemoved": "Vorräte entfernt: {items}",
  "notify.profileUpdated": "Profil aktualisiert: {fields}",
  "notify.field.name": "Name",
  "notify.field.years_running": "Laufjahre",
  "notify.field.weekly_km_baseline": "Wochenkilometer-Basis",
  "notify.field.goal_race": "Zielwettkampf",
  "notify.field.goal_race_date": "Wettkampfdatum",
  "notify.field.goal_time": "Zielzeit",
  "notify.field.timezone": "Zeitzone",
  "notify.field.primary_sport": "Hauptsportart",
  "notify.field.equipment": "Ausrüstung ({count})",
  "notify.goalSet": "Wochenziel: {label} {target}× diese Woche",
  "notify.goalSetDone": "Wochenziel: {label} {target}× diese Woche ({done} schon geschafft)",
  "notify.goalRemoved": "Wochenziel entfernt: {label}",
  "notify.goalAttributed": "Einheit dem richtigen Ziel zugeordnet",
  "notify.goalDetached": "Einheit zählt nicht mehr für ein Ziel",

  // Validation (kitchen / workout screens display these verbatim)
  "api.validation.recipe.titleRequired": "Ein Titel ist erforderlich (max. {max} Zeichen)",
  "api.validation.recipe.ingredientsRequired": "Füge mindestens eine Zutat hinzu",
  "api.validation.recipe.stepsRequired": "Füge mindestens einen Schritt hinzu",
  "api.validation.recipe.servingsRange": "Portionen müssen eine ganze Zahl von {min}–{max} sein",
  "api.validation.recipe.timeMinRange": "Die Zeit muss {min}–{max} Minuten betragen",
  "api.validation.workout.titleRequired": "Ein Titel ist erforderlich (max. {max} Zeichen)",
  "api.validation.workout.notObject": "Die Workout-Definition ist ungültig",
  "api.validation.workout.warmupRange": "Das Aufwärmen muss 0–{max} Sekunden dauern",
  "api.validation.workout.cooldownRange": "Das Abwärmen muss 0–{max} Sekunden dauern",
  "api.validation.workout.blocksRange": "Ein Workout braucht 1–{max} Blöcke",
  "api.validation.workout.blockNotObject": "Block {block} ist ungültig",
  "api.validation.workout.roundsRange": "Block {block}: Runden müssen eine ganze Zahl von 1–{max} sein",
  "api.validation.workout.restBetweenRoundsRange": "Block {block}: Pause zwischen den Runden muss 0–{max} Sekunden betragen",
  "api.validation.workout.exercisesRange": "Block {block} braucht 1–{max} Übungen",
  "api.validation.workout.exerciseNotObject": "Block {block}, Übung {exercise} ist ungültig",
  "api.validation.workout.nameRequired": "Block {block}, Übung {exercise}: ein Name ist erforderlich (max. {max} Zeichen)",
  "api.validation.workout.modeInvalid": "Block {block}, Übung {exercise}: Modus muss Zeit oder Wiederholungen sein",
  "api.validation.workout.workSecRange": "Block {block}, Übung {exercise}: Belastungszeit muss {min}–{max} Sekunden betragen",
  "api.validation.workout.repsRange": "Block {block}, Übung {exercise}: Wiederholungen müssen eine ganze Zahl von {min}–{max} sein",
  "api.validation.workout.restSecRange": "Block {block}, Übung {exercise}: Pause muss 0–{max} Sekunden betragen",

};

export const es: Partial<Record<keyof typeof en, string>> = {
  "api.internalError": "Error interno del servidor",
  "api.notFound": "No encontrado",
  "api.profileNotFound": "Perfil no encontrado",
  "api.userNotFound": "Usuario no encontrado",

  "api.auth.emailPasswordRequired": "El correo y la contraseña son obligatorios",
  "api.auth.tooManyAttemptsMinutes": "Demasiados intentos. Inténtalo de nuevo en unos minutos.",
  "api.auth.tooManyAttemptsLater": "Demasiados intentos. Inténtalo más tarde.",
  "api.auth.invalidCredentials": "Correo o contraseña incorrectos",
  "api.auth.allFieldsRequired": "Todos los campos son obligatorios",
  "api.auth.passwordMin": "La contraseña debe tener al menos 8 caracteres",
  "api.auth.wrongAccessCode": "Código de acceso incorrecto — pregunta a quien te invitó",
  "api.auth.emailRegistered": "Este correo ya está registrado",
  "api.auth.emailRequired": "El correo es obligatorio",
  "api.auth.tooManyRequests": "Demasiadas solicitudes. Inténtalo de nuevo en unos minutos.",
  "api.auth.resetSent": "Si esa dirección tiene una cuenta, el enlace para restablecer va en camino.",
  "api.auth.resetTokenMissing": "Falta el token de restablecimiento",
  "api.auth.resetLinkInvalid": "Este enlace no es válido o ha caducado. Solicita uno nuevo.",
  "api.auth.validEmail": "Introduce una dirección de correo válida",
  "api.auth.currentPasswordRequired": "La contraseña actual es obligatoria",
  "api.auth.currentPasswordIncorrect": "La contraseña actual es incorrecta",
  "api.auth.emailInUse": "Ese correo ya está en uso",
  "api.auth.currentAndNewRequired": "Se requieren la contraseña actual y la nueva",
  "api.auth.newPasswordMin": "La nueva contraseña debe tener al menos 8 caracteres",
  "api.auth.passwordConfirmRequired": "Se requiere la contraseña para confirmar",
  "api.auth.incorrectPassword": "Contraseña incorrecta",

  "api.chat.tooMany": "Demasiados mensajes — dale un minuto a Brocco.",
  "api.chat.sessionNotFound": "Conversación no encontrada",
  "api.chat.failed": "Algo salió mal de mi lado — inténtalo otra vez.",
  "api.chat.done": "Hecho ✓",

  "api.briefing.tooManyRefreshes": "Demasiadas actualizaciones — el briefing ya está bastante fresco.",
  "api.weeklyReview.tooManyForced": "Demasiadas revisiones forzadas.",
  "fallback.briefing.none": "Hoy no hay nada en el calendario.",
  "fallback.briefing.one": "Hoy hay 1 cosa en el calendario.",
  "fallback.briefing.many": "Hoy hay {count} cosas en el calendario.",
  "fallback.weeklyReview.sessions": "Semana hecha: {completed}/{planned} sesiones completadas, {minutes} minutos entrenados.",
  "fallback.weeklyReview.km": "Semana hecha: {km} de {plannedKm} km planificados, {completed}/{planned} sesiones completadas.",
  "fallback.opener": "Chequeo semanal: {km} de {plannedKm} km planificados hasta ahora. ¿Qué tienes en mente?",

  "api.workoutGen.tooMany": "Demasiados entrenamientos generados — ¡elige uno y a entrenar!",
  "api.workoutGen.plannedNotFound": "Entrenamiento planificado no encontrado",
  "api.workoutGen.failed": "No se pudo generar el entrenamiento — inténtalo de nuevo o usa una plantilla.",

  "api.analyze.nothing": "Nada que analizar — sin datos de frecuencia cardíaca o sin FC máxima en Ajustes.",
  "api.analyze.failed": "El análisis falló",

  "api.scan.limit": "Límite de escaneos alcanzado — inténtalo en una hora.",
  "api.scan.imageRequired": "Se necesita al menos una imagen",
  "api.scan.imageInvalid": "Cada imagen necesita datos base64 y un mediaType (jpeg/png/webp)",
  "api.scan.imageTooLarge": "Imagen demasiado grande — máx. ~3,5 MB cada una",
  "api.scan.noRecipe": "No se pudo leer una receta en esa foto — prueba con una más nítida.",
  "api.scan.noRecipeReason": "No se encontró receta: {reason}",
  "api.scan.incomplete": "No se pudo leer la receta completa — prueba con una foto más nítida.",
  "api.scan.failed": "El escaneo falló — inténtalo de nuevo.",

  "api.voice.tooMany": "Demasiadas transcripciones — respira un momento.",
  "api.voice.notConfigured": "La transcripción de voz no está configurada",
  "api.voice.noAudio": "No se envió ningún archivo de audio",
  "api.voice.tooLarge": "Grabación demasiado grande",
  "api.voice.failed": "La transcripción falló",

  "api.push.notConfigured": "Las notificaciones push no están configuradas en el servidor",
  "push.testTitle": "🥦 Brocco",
  "push.testBody": "Las notificaciones funcionan en este dispositivo. ¡Corre como un brócoli!",
  "push.reminderBody": "a las {time} (en {min} min)",

  "api.strava.notConnected": "Strava no está conectado",
  "api.strava.syncRecently": "La sincronización se ejecutó hace poco — dale una hora.",
  "api.strava.syncFailed": "La sincronización falló",
  "api.strava.revoked": "Acceso a Strava revocado o caducado ({status}) — hay que reconectar",
  "api.strava.webhookSyncFailed": "La sincronización por webhook falló: {reason}",
  "api.strava.manualSyncFailed": "La sincronización manual falló: {reason}",
  "api.strava.autoSyncFailed": "La sincronización falló: {reason}",
  "api.strava.unknownError": "error desconocido",

  "api.intervals.credentialsRequired": "Se requieren el ID de atleta y la clave API",
  "api.intervals.rejectedKey": "intervals.icu rechazó la clave API — cópiala de nuevo desde intervals.icu Settings → Developer",
  "api.intervals.badStatus": "intervals.icu devolvió {status} — revisa el ID de atleta (el número en la URL de tu perfil de intervals.icu, p. ej. i1234567 o solo 1234567)",
  "api.intervals.unreachable": "No se pudo conectar con intervals.icu — inténtalo de nuevo",
  "api.intervals.notConnected": "La sincronización con el reloj no está conectada",
  "api.intervals.syncFailed": "La sincronización falló — inténtalo de nuevo",

  // Brocco's tool notifications (chips/toasts in the chat)
  "notify.logged": "Anotado: {detail}",
  "notify.severity.minor": "leve",
  "notify.severity.moderate": "moderada",
  "notify.severity.severe": "grave",
  "notify.activityLogged": "Registrado: {description}",
  "notify.activityLoggedKm": "Registrado: {description} ({km} km)",
  "notify.partlyApplied": "Aplicado en parte — {failed} de {total} cambio(s) fallaron: {errors}",
  "notify.planChangesApplied": "Cambios del plan aplicados por Brocco",
  "notify.planCreated": "Plan creado: {name}",
  "notify.tasksAdded.one": "1 tarea semanal añadida a tu plan",
  "notify.tasksAdded.many": "{count} tareas semanales añadidas a tu plan",
  "notify.eventRemovedOn": "{title} eliminado el {date}",
  "notify.eventDeleted": "{title} eliminado",
  "notify.recipeSaved": "Receta guardada: {title}",
  "notify.recipeCooked": "¡Que aproveche! Registrado: {title}",
  "notify.recipeDeleted": "Receta eliminada: {title}",
  "notify.staplesAdded": "Básicos de despensa añadidos: {items}",
  "notify.staplesRemoved": "Básicos de despensa eliminados: {items}",
  "notify.profileUpdated": "Perfil actualizado: {fields}",
  "notify.field.name": "nombre",
  "notify.field.years_running": "años corriendo",
  "notify.field.weekly_km_baseline": "km semanales de base",
  "notify.field.goal_race": "carrera objetivo",
  "notify.field.goal_race_date": "fecha de la carrera objetivo",
  "notify.field.goal_time": "tiempo objetivo",
  "notify.field.timezone": "zona horaria",
  "notify.field.primary_sport": "deporte principal",
  "notify.field.equipment": "equipamiento ({count})",
  "notify.goalSet": "Objetivo semanal: {label} {target}× esta semana",
  "notify.goalSetDone": "Objetivo semanal: {label} {target}× esta semana ({done} ya hechos)",
  "notify.goalRemoved": "Objetivo semanal eliminado: {label}",
  "notify.goalAttributed": "Sesión asignada al objetivo correcto",
  "notify.goalDetached": "La sesión ya no cuenta para ningún objetivo",

  // Validation (kitchen / workout screens display these verbatim)
  "api.validation.recipe.titleRequired": "Se requiere un título (máx. {max} caracteres)",
  "api.validation.recipe.ingredientsRequired": "Añade al menos un ingrediente",
  "api.validation.recipe.stepsRequired": "Añade al menos un paso",
  "api.validation.recipe.servingsRange": "Las raciones deben ser un número entero de {min}–{max}",
  "api.validation.recipe.timeMinRange": "El tiempo debe ser de {min}–{max} minutos",
  "api.validation.workout.titleRequired": "Se requiere un título (máx. {max} caracteres)",
  "api.validation.workout.notObject": "La definición del entrenamiento no es válida",
  "api.validation.workout.warmupRange": "El calentamiento debe durar 0–{max} segundos",
  "api.validation.workout.cooldownRange": "La vuelta a la calma debe durar 0–{max} segundos",
  "api.validation.workout.blocksRange": "Un entrenamiento necesita 1–{max} bloques",
  "api.validation.workout.blockNotObject": "El bloque {block} no es válido",
  "api.validation.workout.roundsRange": "Bloque {block}: las rondas deben ser un número entero de 1–{max}",
  "api.validation.workout.restBetweenRoundsRange": "Bloque {block}: el descanso entre rondas debe ser de 0–{max} segundos",
  "api.validation.workout.exercisesRange": "El bloque {block} necesita 1–{max} ejercicios",
  "api.validation.workout.exerciseNotObject": "Bloque {block}, ejercicio {exercise} no es válido",
  "api.validation.workout.nameRequired": "Bloque {block}, ejercicio {exercise}: se requiere un nombre (máx. {max} caracteres)",
  "api.validation.workout.modeInvalid": "Bloque {block}, ejercicio {exercise}: el modo debe ser tiempo o repeticiones",
  "api.validation.workout.workSecRange": "Bloque {block}, ejercicio {exercise}: el tiempo de trabajo debe ser de {min}–{max} segundos",
  "api.validation.workout.repsRange": "Bloque {block}, ejercicio {exercise}: las repeticiones deben ser un número entero de {min}–{max}",
  "api.validation.workout.restSecRange": "Bloque {block}, ejercicio {exercise}: el descanso debe ser de 0–{max} segundos",

};
