/**
 * Dictionary partial — "settings" area. Merged into src/lib/dict.ts.
 * Every key needs all three languages; scripts/check-i18n.ts enforces it.
 */
export const en = {
  // Profile
  "settings.change": "Change",
  "settings.newEmailPlaceholder": "new@email.com",
  "settings.currentPasswordConfirm": "Current password (to confirm)",
  "settings.emailNote": "This is your login and where password-reset links go — make sure it's an inbox you can read.",
  "settings.saveEmail": "Save email",
  "settings.emailUpdated": "Email updated",
  "settings.failed": "Failed",
  "settings.timezonePlaceholder": "e.g. Europe/Berlin",
  "settings.useDeviceTimezone": "Use device timezone ({tz})",
  "settings.goalRacePlaceholder": "e.g. Valencia Marathon",
  "settings.goalTimePlaceholder": "e.g. Sub 3:00",
  "settings.maxHrUnit": "(bpm)",
  "settings.maxHrPlaceholder": "e.g. 188",
  "settings.maxHrHint": "Used to compute heart rate zones for intensity analysis. If left blank, Brocco estimates it from your highest recorded heart rate.",
  "settings.saveChanges": "Save changes",

  // Features
  "settings.featuresBlurb": "Switch off what you don't use — navigation, the Today screen, and Brocco adapt. With everything off you get the classic running-coach experience. Your data is kept, just hidden.",
  "settings.calendarFeatureDesc": "Events, birthdays, and reminders",
  "settings.enabled": "enabled",
  "settings.disabled": "disabled",

  // Calendar feed
  "settings.calendarFeedBlurb": "Subscribe from Google or Apple Calendar to see your brocco events and workouts there (read-only).",
  "settings.copy": "Copy",
  "settings.copied": "Copied ✓",
  "settings.calendarFeedHowTo": "Google Calendar: Other calendars → + → From URL. Apple Calendar: File → New Calendar Subscription.",
  "settings.feedLeakBefore": "Anyone with this link can read your calendar —",
  "settings.regenerateIt": "regenerate it",
  "settings.feedLeakAfter": "if it ever leaks (the old link stops working).",
  "settings.creating": "Creating...",
  "settings.createSubscribeLink": "Create subscribe link",

  // Notifications
  "settings.notificationsBlurb": "Event reminders on this device — even when the app is closed.",
  "settings.checking": "Checking…",
  "settings.pushUnsupported": "This browser doesn't support push notifications. On iPhone, add brocco.run to your home screen first.",
  "settings.pushUnconfigured": "Push isn't configured on the server yet.",
  "settings.pushDenied": "Notifications are blocked for brocco.run — allow them in your browser's site settings, then reload.",
  "settings.enabling": "Enabling...",
  "settings.enableOnDevice": "Enable on this device",
  "settings.enabledOnDevice": "Enabled on this device",
  "settings.sendTestNotification": "Send test notification",
  "settings.disable": "Disable",
  "settings.enableFailed": "Couldn't enable notifications — try again.",
  "settings.disableFailed": "Couldn't disable — try again.",
  "settings.testFailed": "Test failed",
  "settings.testSentOne": "Sent to 1 device — check your notifications.",
  "settings.testSentMany": "Sent to {n} devices — check your notifications.",

  // Strava
  "settings.stravaConnectedBanner": "Strava connected successfully.",
  "settings.stravaDeniedBanner": "Strava authorization was denied.",
  "settings.stravaAthlete": "Athlete {id}",
  "settings.lastAttemptFailed": "last attempt failed",
  "settings.stravaSyncNewOne": "1 new activity added ({checked} checked)",
  "settings.stravaSyncNewMany": "{n} new activities added ({checked} checked)",
  "settings.stravaSyncUpToDate": "All up to date ({checked} checked)",
  "settings.syncFailed": "Sync failed",
  "settings.syncFailedRetry": "Sync failed — try again.",
  "settings.stravaDisconnectConfirm": "Disconnect Strava? Your imported activities are kept — new ones just stop arriving.",
  "settings.disconnectFailed": "Couldn't disconnect — try again.",

  // Watch sync (intervals.icu)
  "settings.watchSyncBlurb": "Your planned workouts on your COROS or Garmin — intervals, paces, and all — via a free intervals.icu account. Only runs and rides go to the watch; strength, climbing and other sessions stay in the app.",
  "settings.intervalsAthlete": "intervals.icu athlete {id}",
  "settings.watchConnectedHint": "Upcoming workouts (next 2 weeks) sync automatically whenever your plan changes. Your watch picks them up from intervals.icu — make sure your watch is connected there with “Upload planned workouts” on.",
  "settings.working": "Working…",
  "settings.hideSetupSteps": "Hide setup steps",
  "settings.howToSetUp": "How do I set this up? (one-time, ~3 minutes)",
  "settings.setupStep1": "Create a free account at {link}",
  "settings.setupStep2": "In intervals.icu **Settings**, scroll to your watch brand (COROS / Garmin / …), connect it, and tick **“Upload planned workouts”**",
  "settings.setupStep3": "Still in Settings, open **Developer Settings** and generate an **API key**",
  "settings.setupStep4": "Your **Athlete ID** is shown right there (looks like `i1234567`)",
  "settings.setupStep5": "Paste both below",
  "settings.athleteIdPlaceholder": "Athlete ID (e.g. i1234567)",
  "settings.apiKeyPlaceholder": "API key",
  "settings.connectAndSync": "Connect & sync",
  "settings.connectionFailed": "Connection failed",
  "settings.connectionFailedRetry": "Connection failed — try again.",
  "settings.connectedAs": "as {name}",
  "settings.syncChanged": "Synced: {created} new, {updated} updated, {deleted} removed.",
  "settings.syncNoPlan": "No active training plan yet — build one with Brocco, then its upcoming workouts sync here.",
  "settings.syncUpToDateOne": "Already up to date — your 1 upcoming workout is on your intervals.icu calendar. If it's not on your watch, open intervals.icu → your COROS/Garmin connection and turn on “Upload planned workouts”.",
  "settings.syncUpToDateMany": "Already up to date — all {n} upcoming workouts are on your intervals.icu calendar. If they're not on your watch, open intervals.icu → your COROS/Garmin connection and turn on “Upload planned workouts”.",
  "settings.syncNothingScheduled": "No runs scheduled in the next 2 weeks, so there's nothing to push. Watch sync only sends the upcoming 14 days.",
  "settings.syncSkippedType": "{n} aren't run/ride (strength & co. stay in the app)",
  "settings.syncSkippedNoTarget": "{n} have no distance or pace target",
  "settings.syncNoneSyncableOne": "Found 1 workout in the next 2 weeks but it couldn't go to your watch{why}.",
  "settings.syncNoneSyncableMany": "Found {n} workouts in the next 2 weeks but none could go to your watch{why}.",

  // Password
  "settings.currentPassword": "Current password",
  "settings.newPasswordPlaceholder": "New password (min. 8 chars)",
  "settings.confirmNewPassword": "Confirm new password",
  "settings.updating": "Updating...",
  "settings.updatePassword": "Update Password",
  "settings.passwordsDontMatch": "Passwords don't match",
  "settings.minChars": "Minimum 8 characters",
  "settings.passwordUpdated": "Password updated",

  // Account
  "settings.deleteWarning": "This will permanently delete all your data including activities, plans, and chat history. This cannot be undone.",
  "settings.enterPasswordToConfirm": "Enter your password to confirm",
  "settings.deleting": "Deleting...",
  "settings.deleteMyAccount": "Delete my account",

  // Install
  "settings.installBlurb": "Add brocco.run to your home screen for the best experience — it works like a regular app.",

  // Equipment
  "equipment.title": "Equipment you have",
  "equipment.blurb": "Brocco builds strength and rehab work around this instead of guessing. Leave it empty and it assumes bodyweight only.",
  "equipment.remove": "Remove {item}",
  "equipment.placeholder": "resistance bands, 16kg kettlebell…",
  "equipment.addAria": "Add equipment",
  "equipment.add": "Add",
  "equipment.saveFailed": "Couldn't save — try again.",
  "equipment.commonKit": "Common kit",
} as const;

export const de: Partial<Record<keyof typeof en, string>> = {
  // Profile
  "settings.change": "Ändern",
  "settings.newEmailPlaceholder": "neue@email.de",
  "settings.currentPasswordConfirm": "Aktuelles Passwort (zur Bestätigung)",
  "settings.emailNote": "Das ist dein Login und hier landen Links zum Zurücksetzen des Passworts — nimm ein Postfach, das du auch liest.",
  "settings.saveEmail": "E-Mail speichern",
  "settings.emailUpdated": "E-Mail aktualisiert",
  "settings.failed": "Fehlgeschlagen",
  "settings.timezonePlaceholder": "z. B. Europe/Berlin",
  "settings.useDeviceTimezone": "Zeitzone des Geräts verwenden ({tz})",
  "settings.goalRacePlaceholder": "z. B. Valencia-Marathon",
  "settings.goalTimePlaceholder": "z. B. unter 3:00",
  "settings.maxHrUnit": "(bpm)",
  "settings.maxHrPlaceholder": "z. B. 188",
  "settings.maxHrHint": "Wird für die Herzfrequenzzonen in der Intensitätsanalyse verwendet. Bleibt das Feld leer, schätzt Brocco den Wert aus deiner höchsten aufgezeichneten Herzfrequenz.",
  "settings.saveChanges": "Änderungen speichern",

  // Features
  "settings.featuresBlurb": "Schalte ab, was du nicht nutzt — Navigation, der Heute-Bildschirm und Brocco passen sich an. Mit allem aus bekommst du den klassischen Lauf-Coach. Deine Daten bleiben erhalten, nur ausgeblendet.",
  "settings.calendarFeatureDesc": "Termine, Geburtstage und Erinnerungen",
  "settings.enabled": "an",
  "settings.disabled": "aus",

  // Calendar feed
  "settings.calendarFeedBlurb": "Abonniere den Feed in Google oder Apple Kalender, um deine brocco-Termine und Workouts dort zu sehen (nur lesend).",
  "settings.copy": "Kopieren",
  "settings.copied": "Kopiert ✓",
  "settings.calendarFeedHowTo": "Google Kalender: Weitere Kalender → + → Per URL. Apple Kalender: Ablage → Neues Kalenderabonnement.",
  "settings.feedLeakBefore": "Wer diesen Link hat, kann deinen Kalender lesen —",
  "settings.regenerateIt": "erneuere ihn",
  "settings.feedLeakAfter": "falls er jemals nach außen gerät (der alte Link funktioniert dann nicht mehr).",
  "settings.creating": "Wird erstellt...",
  "settings.createSubscribeLink": "Abo-Link erstellen",

  // Notifications
  "settings.notificationsBlurb": "Terminerinnerungen auf diesem Gerät — auch bei geschlossener App.",
  "settings.checking": "Wird geprüft…",
  "settings.pushUnsupported": "Dieser Browser unterstützt keine Push-Benachrichtigungen. Auf dem iPhone füge brocco.run zuerst zum Home-Bildschirm hinzu.",
  "settings.pushUnconfigured": "Push ist auf dem Server noch nicht eingerichtet.",
  "settings.pushDenied": "Benachrichtigungen sind für brocco.run blockiert — erlaube sie in den Website-Einstellungen deines Browsers und lade die Seite neu.",
  "settings.enabling": "Wird aktiviert...",
  "settings.enableOnDevice": "Auf diesem Gerät aktivieren",
  "settings.enabledOnDevice": "Auf diesem Gerät aktiviert",
  "settings.sendTestNotification": "Test-Benachrichtigung senden",
  "settings.disable": "Deaktivieren",
  "settings.enableFailed": "Benachrichtigungen konnten nicht aktiviert werden — versuch es noch einmal.",
  "settings.disableFailed": "Konnte nicht deaktiviert werden — versuch es noch einmal.",
  "settings.testFailed": "Test fehlgeschlagen",
  "settings.testSentOne": "An 1 Gerät gesendet — schau in deine Benachrichtigungen.",
  "settings.testSentMany": "An {n} Geräte gesendet — schau in deine Benachrichtigungen.",

  // Strava
  "settings.stravaConnectedBanner": "Strava erfolgreich verbunden.",
  "settings.stravaDeniedBanner": "Die Strava-Freigabe wurde abgelehnt.",
  "settings.stravaAthlete": "Athlet {id}",
  "settings.lastAttemptFailed": "letzter Versuch fehlgeschlagen",
  "settings.stravaSyncNewOne": "1 neue Aktivität hinzugefügt ({checked} geprüft)",
  "settings.stravaSyncNewMany": "{n} neue Aktivitäten hinzugefügt ({checked} geprüft)",
  "settings.stravaSyncUpToDate": "Alles aktuell ({checked} geprüft)",
  "settings.syncFailed": "Synchronisierung fehlgeschlagen",
  "settings.syncFailedRetry": "Synchronisierung fehlgeschlagen — versuch es noch einmal.",
  "settings.stravaDisconnectConfirm": "Strava trennen? Deine importierten Aktivitäten bleiben erhalten — es kommen nur keine neuen mehr an.",
  "settings.disconnectFailed": "Trennen fehlgeschlagen — versuch es noch einmal.",

  // Watch sync (intervals.icu)
  "settings.watchSyncBlurb": "Deine geplanten Workouts auf deiner COROS oder Garmin — mit Intervallen, Tempo und allem — über ein kostenloses intervals.icu-Konto. Nur Läufe und Radfahrten gehen auf die Uhr; Kraft, Klettern und andere Einheiten bleiben in der App.",
  "settings.intervalsAthlete": "intervals.icu-Athlet {id}",
  "settings.watchConnectedHint": "Anstehende Workouts (nächste 2 Wochen) werden automatisch synchronisiert, sobald sich dein Plan ändert. Deine Uhr holt sie sich von intervals.icu — stelle sicher, dass sie dort verbunden ist und „Upload planned workouts“ aktiviert ist.",
  "settings.working": "Läuft…",
  "settings.hideSetupSteps": "Einrichtungsschritte ausblenden",
  "settings.howToSetUp": "Wie richte ich das ein? (einmalig, ca. 3 Minuten)",
  "settings.setupStep1": "Erstelle ein kostenloses Konto bei {link}",
  "settings.setupStep2": "Scrolle in den intervals.icu-**Einstellungen** zu deiner Uhrenmarke (COROS / Garmin / …), verbinde sie und setze den Haken bei **„Upload planned workouts“**",
  "settings.setupStep3": "Öffne ebenfalls in den Einstellungen die **Developer Settings** und erzeuge einen **API key**",
  "settings.setupStep4": "Deine **Athlete ID** steht direkt daneben (sieht aus wie `i1234567`)",
  "settings.setupStep5": "Trag beides unten ein",
  "settings.athleteIdPlaceholder": "Athlete ID (z. B. i1234567)",
  "settings.apiKeyPlaceholder": "API key",
  "settings.connectAndSync": "Verbinden & synchronisieren",
  "settings.connectionFailed": "Verbindung fehlgeschlagen",
  "settings.connectionFailedRetry": "Verbindung fehlgeschlagen — versuch es noch einmal.",
  "settings.connectedAs": "als {name}",
  "settings.syncChanged": "Synchronisiert: {created} neu, {updated} aktualisiert, {deleted} entfernt.",
  "settings.syncNoPlan": "Noch kein aktiver Trainingsplan — erstelle einen mit Brocco, dann landen seine anstehenden Workouts hier.",
  "settings.syncUpToDateOne": "Schon aktuell — dein 1 anstehendes Workout ist in deinem intervals.icu-Kalender. Falls es nicht auf der Uhr ist, öffne intervals.icu → deine COROS/Garmin-Verbindung und aktiviere „Upload planned workouts“.",
  "settings.syncUpToDateMany": "Schon aktuell — alle {n} anstehenden Workouts sind in deinem intervals.icu-Kalender. Falls sie nicht auf der Uhr sind, öffne intervals.icu → deine COROS/Garmin-Verbindung und aktiviere „Upload planned workouts“.",
  "settings.syncNothingScheduled": "In den nächsten 2 Wochen sind keine Läufe geplant, also gibt es nichts zu senden. Der Uhren-Sync überträgt nur die kommenden 14 Tage.",
  "settings.syncSkippedType": "{n} sind kein Lauf/keine Radfahrt (Kraft & Co. bleiben in der App)",
  "settings.syncSkippedNoTarget": "{n} haben keine Distanz- oder Tempovorgabe",
  "settings.syncNoneSyncableOne": "1 Workout in den nächsten 2 Wochen gefunden, aber es konnte nicht auf deine Uhr{why}.",
  "settings.syncNoneSyncableMany": "{n} Workouts in den nächsten 2 Wochen gefunden, aber keines konnte auf deine Uhr{why}.",

  // Password
  "settings.currentPassword": "Aktuelles Passwort",
  "settings.newPasswordPlaceholder": "Neues Passwort (mind. 8 Zeichen)",
  "settings.confirmNewPassword": "Neues Passwort bestätigen",
  "settings.updating": "Wird aktualisiert...",
  "settings.updatePassword": "Passwort aktualisieren",
  "settings.passwordsDontMatch": "Passwörter stimmen nicht überein",
  "settings.minChars": "Mindestens 8 Zeichen",
  "settings.passwordUpdated": "Passwort aktualisiert",

  // Account
  "settings.deleteWarning": "Damit werden alle deine Daten dauerhaft gelöscht — Aktivitäten, Pläne und Chatverlauf. Das lässt sich nicht rückgängig machen.",
  "settings.enterPasswordToConfirm": "Gib zur Bestätigung dein Passwort ein",
  "settings.deleting": "Wird gelöscht...",
  "settings.deleteMyAccount": "Mein Konto löschen",

  // Install
  "settings.installBlurb": "Füge brocco.run zum Home-Bildschirm hinzu — so läuft es wie eine normale App.",

  // Equipment
  "equipment.title": "Deine Ausrüstung",
  "equipment.blurb": "Brocco plant Kraft- und Reha-Arbeit damit, statt zu raten. Lässt du die Liste leer, geht er von reinem Körpergewicht aus.",
  "equipment.remove": "{item} entfernen",
  "equipment.placeholder": "Widerstandsbänder, 16kg Kettlebell…",
  "equipment.addAria": "Ausrüstung hinzufügen",
  "equipment.add": "Hinzufügen",
  "equipment.saveFailed": "Speichern fehlgeschlagen — versuch es noch einmal.",
  "equipment.commonKit": "Übliche Ausrüstung",
};

export const es: Partial<Record<keyof typeof en, string>> = {
  // Profile
  "settings.change": "Cambiar",
  "settings.newEmailPlaceholder": "nuevo@email.com",
  "settings.currentPasswordConfirm": "Contraseña actual (para confirmar)",
  "settings.emailNote": "Es tu acceso y adonde llegan los enlaces para restablecer la contraseña — asegúrate de que sea un buzón que leas.",
  "settings.saveEmail": "Guardar correo",
  "settings.emailUpdated": "Correo actualizado",
  "settings.failed": "Error",
  "settings.timezonePlaceholder": "p. ej. Europe/Madrid",
  "settings.useDeviceTimezone": "Usar la zona horaria del dispositivo ({tz})",
  "settings.goalRacePlaceholder": "p. ej. Maratón de Valencia",
  "settings.goalTimePlaceholder": "p. ej. menos de 3:00",
  "settings.maxHrUnit": "(ppm)",
  "settings.maxHrPlaceholder": "p. ej. 188",
  "settings.maxHrHint": "Se usa para calcular las zonas de frecuencia cardíaca en el análisis de intensidad. Si lo dejas vacío, Brocco lo estima a partir de tu frecuencia cardíaca más alta registrada.",
  "settings.saveChanges": "Guardar cambios",

  // Features
  "settings.featuresBlurb": "Desactiva lo que no uses — la navegación, la pantalla de Hoy y Brocco se adaptan. Con todo apagado tienes la experiencia clásica de entrenador de running. Tus datos se conservan, solo se ocultan.",
  "settings.calendarFeatureDesc": "Eventos, cumpleaños y recordatorios",
  "settings.enabled": "activado",
  "settings.disabled": "desactivado",

  // Calendar feed
  "settings.calendarFeedBlurb": "Suscríbete desde Google Calendar o el Calendario de Apple para ver allí tus eventos y entrenos de brocco (solo lectura).",
  "settings.copy": "Copiar",
  "settings.copied": "Copiado ✓",
  "settings.calendarFeedHowTo": "Google Calendar: Otros calendarios → + → Desde URL. Calendario de Apple: Archivo → Nueva suscripción a calendario.",
  "settings.feedLeakBefore": "Cualquiera con este enlace puede leer tu calendario —",
  "settings.regenerateIt": "regenéralo",
  "settings.feedLeakAfter": "si alguna vez se filtra (el enlace antiguo deja de funcionar).",
  "settings.creating": "Creando...",
  "settings.createSubscribeLink": "Crear enlace de suscripción",

  // Notifications
  "settings.notificationsBlurb": "Recordatorios de eventos en este dispositivo — incluso con la app cerrada.",
  "settings.checking": "Comprobando…",
  "settings.pushUnsupported": "Este navegador no admite notificaciones push. En iPhone, añade primero brocco.run a tu pantalla de inicio.",
  "settings.pushUnconfigured": "Las notificaciones push aún no están configuradas en el servidor.",
  "settings.pushDenied": "Las notificaciones están bloqueadas para brocco.run — permítelas en los ajustes del sitio de tu navegador y recarga.",
  "settings.enabling": "Activando...",
  "settings.enableOnDevice": "Activar en este dispositivo",
  "settings.enabledOnDevice": "Activadas en este dispositivo",
  "settings.sendTestNotification": "Enviar notificación de prueba",
  "settings.disable": "Desactivar",
  "settings.enableFailed": "No se pudieron activar las notificaciones — inténtalo de nuevo.",
  "settings.disableFailed": "No se pudo desactivar — inténtalo de nuevo.",
  "settings.testFailed": "La prueba falló",
  "settings.testSentOne": "Enviada a 1 dispositivo — revisa tus notificaciones.",
  "settings.testSentMany": "Enviada a {n} dispositivos — revisa tus notificaciones.",

  // Strava
  "settings.stravaConnectedBanner": "Strava conectado correctamente.",
  "settings.stravaDeniedBanner": "La autorización de Strava fue denegada.",
  "settings.stravaAthlete": "Atleta {id}",
  "settings.lastAttemptFailed": "el último intento falló",
  "settings.stravaSyncNewOne": "1 actividad nueva añadida ({checked} revisadas)",
  "settings.stravaSyncNewMany": "{n} actividades nuevas añadidas ({checked} revisadas)",
  "settings.stravaSyncUpToDate": "Todo al día ({checked} revisadas)",
  "settings.syncFailed": "Error de sincronización",
  "settings.syncFailedRetry": "Error de sincronización — inténtalo de nuevo.",
  "settings.stravaDisconnectConfirm": "¿Desconectar Strava? Tus actividades importadas se conservan — solo dejan de llegar nuevas.",
  "settings.disconnectFailed": "No se pudo desconectar — inténtalo de nuevo.",

  // Watch sync (intervals.icu)
  "settings.watchSyncBlurb": "Tus entrenos planificados en tu COROS o Garmin — con intervalos, ritmos y todo — a través de una cuenta gratuita de intervals.icu. Solo las carreras y salidas en bici van al reloj; la fuerza, la escalada y otras sesiones se quedan en la app.",
  "settings.intervalsAthlete": "atleta de intervals.icu {id}",
  "settings.watchConnectedHint": "Los próximos entrenos (2 semanas) se sincronizan automáticamente cada vez que cambia tu plan. Tu reloj los recoge de intervals.icu — asegúrate de tenerlo conectado allí con “Upload planned workouts” activado.",
  "settings.working": "Trabajando…",
  "settings.hideSetupSteps": "Ocultar pasos de configuración",
  "settings.howToSetUp": "¿Cómo lo configuro? (una sola vez, ~3 minutos)",
  "settings.setupStep1": "Crea una cuenta gratuita en {link}",
  "settings.setupStep2": "En los **Ajustes** de intervals.icu, baja hasta la marca de tu reloj (COROS / Garmin / …), conéctalo y marca **“Upload planned workouts”**",
  "settings.setupStep3": "Sin salir de Ajustes, abre **Developer Settings** y genera una **API key**",
  "settings.setupStep4": "Tu **Athlete ID** aparece justo ahí (tiene la forma `i1234567`)",
  "settings.setupStep5": "Pega ambos abajo",
  "settings.athleteIdPlaceholder": "Athlete ID (p. ej. i1234567)",
  "settings.apiKeyPlaceholder": "API key",
  "settings.connectAndSync": "Conectar y sincronizar",
  "settings.connectionFailed": "Error de conexión",
  "settings.connectionFailedRetry": "Error de conexión — inténtalo de nuevo.",
  "settings.connectedAs": "como {name}",
  "settings.syncChanged": "Sincronizado: {created} nuevos, {updated} actualizados, {deleted} eliminados.",
  "settings.syncNoPlan": "Aún no hay un plan de entrenamiento activo — crea uno con Brocco y sus próximos entrenos se sincronizarán aquí.",
  "settings.syncUpToDateOne": "Ya está al día — tu 1 próximo entreno está en tu calendario de intervals.icu. Si no aparece en el reloj, abre intervals.icu → tu conexión COROS/Garmin y activa “Upload planned workouts”.",
  "settings.syncUpToDateMany": "Ya está al día — los {n} próximos entrenos están en tu calendario de intervals.icu. Si no aparecen en el reloj, abre intervals.icu → tu conexión COROS/Garmin y activa “Upload planned workouts”.",
  "settings.syncNothingScheduled": "No hay carreras programadas en las próximas 2 semanas, así que no hay nada que enviar. La sincronización con el reloj solo envía los próximos 14 días.",
  "settings.syncSkippedType": "{n} no son carrera/bici (la fuerza y compañía se quedan en la app)",
  "settings.syncSkippedNoTarget": "{n} no tienen objetivo de distancia ni de ritmo",
  "settings.syncNoneSyncableOne": "Se encontró 1 entreno en las próximas 2 semanas, pero no pudo ir a tu reloj{why}.",
  "settings.syncNoneSyncableMany": "Se encontraron {n} entrenos en las próximas 2 semanas, pero ninguno pudo ir a tu reloj{why}.",

  // Password
  "settings.currentPassword": "Contraseña actual",
  "settings.newPasswordPlaceholder": "Nueva contraseña (mín. 8 caracteres)",
  "settings.confirmNewPassword": "Confirmar nueva contraseña",
  "settings.updating": "Actualizando...",
  "settings.updatePassword": "Actualizar contraseña",
  "settings.passwordsDontMatch": "Las contraseñas no coinciden",
  "settings.minChars": "Mínimo 8 caracteres",
  "settings.passwordUpdated": "Contraseña actualizada",

  // Account
  "settings.deleteWarning": "Esto eliminará permanentemente todos tus datos, incluidas actividades, planes e historial de chat. No se puede deshacer.",
  "settings.enterPasswordToConfirm": "Introduce tu contraseña para confirmar",
  "settings.deleting": "Eliminando...",
  "settings.deleteMyAccount": "Eliminar mi cuenta",

  // Install
  "settings.installBlurb": "Añade brocco.run a tu pantalla de inicio para la mejor experiencia — funciona como una app normal.",

  // Equipment
  "equipment.title": "Tu equipo",
  "equipment.blurb": "Brocco diseña el trabajo de fuerza y rehabilitación con esto en vez de adivinar. Si lo dejas vacío, asume solo peso corporal.",
  "equipment.remove": "Quitar {item}",
  "equipment.placeholder": "bandas elásticas, kettlebell de 16kg…",
  "equipment.addAria": "Añadir equipo",
  "equipment.add": "Añadir",
  "equipment.saveFailed": "No se pudo guardar — inténtalo de nuevo.",
  "equipment.commonKit": "Equipo habitual",
};
