/**
 * Dictionary partial — "workout" area. Merged into src/lib/dict.ts.
 * Every key needs all three languages; scripts/check-i18n.ts enforces it.
 *
 * "workout.*" / "player.*" — the Workouts screen and the player.
 * "preset.*" — the built-in workout library (titles, focus, block labels,
 *   exercise names, form cues); resolved in guided-workout.ts.
 * "equipment.*" — the suggested-kit chips (src/lib/equipment.ts).
 * Templates use {n}, {title}, {min} placeholders — see fillTemplate() in
 * guided-workout.ts.
 */
export const en = {
  // Workouts screen + player
  "workout.block": "Block",
  "workout.roundLabel": "Round",
  "workout.warmUpNote": "Easy movement — arm circles, leg swings, light jog in place",
  "workout.coolDownNote": "Slow stretching — hold each stretch, breathe",
  "workout.intervals": "Intervals",
  "workout.workLabel": "Work",
  "workout.doneTimes": "done {n}×",
  "workout.planBadge": "plan",
  "workout.focusLabel": "focus",
  "workout.askForToday": "Make me a workout for today",
  "workout.untitled": "Workout",
  "workout.readyToast": "Workout ready: {title} (~{min} min)",
  "workout.left": "left",
  "workout.right": "right",
  "player.undoFailed": "Couldn't undo — check History later.",

  // Preset library — titles
  "preset.tabataTitle": "Tabata",
  "preset.coreTitle": "Runner's Core",
  "preset.hipsTitle": "Hips & Glutes",
  "preset.calvesTitle": "Calves & Ankles",
  "preset.fullbodyTitle": "Full-Body Strength",
  "preset.hangboardTitle": "Hangboard Repeaters",
  "preset.antagonistTitle": "Antagonist Push",
  "preset.shouldersTitle": "Shoulder Stability",
  "preset.climbcoreTitle": "Climber's Core",

  // Preset library — descriptions
  "preset.tabataDesc": "The classic: 8 × 20s all-out / 10s rest. 4 brutal minutes.",
  "preset.coreDesc": "15 min of trunk stability — the difference in the last 5k.",
  "preset.hipsDesc": "15 min for the muscles that keep your stride honest.",
  "preset.calvesDesc": "10 min of lower-leg armor against shin splints and achilles niggles.",
  "preset.fullbodyDesc": "20 min, no equipment — strength endurance for the whole chassis.",
  "preset.hangboardDesc": "4 sets of 6 × 7s/3s on a comfortable edge. Experienced climbers only — fingers first.",
  "preset.antagonistDesc": "15 min of pushing — the insurance policy against climber's elbow and hunched shoulders.",
  "preset.shouldersDesc": "12 min for the cuff and scapula — what keeps gaston moves honest.",
  "preset.climbcoreDesc": "15 min of tension — hollow body and hips that keep your feet on.",

  // Preset library — focus
  "preset.focusConditioning": "conditioning",
  "preset.focusCore": "core",
  "preset.focusHipsGlutes": "hips & glutes",
  "preset.focusCalvesAnkles": "calves & ankles",
  "preset.focusFullBody": "full body",
  "preset.focusFingers": "fingers",
  "preset.focusAntagonists": "antagonists",
  "preset.focusShoulders": "shoulders",

  // Preset library — block labels
  "preset.blockTabata": "Tabata",
  "preset.blockCircuit": "Circuit",
  "preset.blockRepeaters": "Repeaters",

  // Preset library — exercise names
  "preset.exPlank": "Plank",
  "preset.exSidePlank": "Side plank",
  "preset.exDeadBug": "Dead bug",
  "preset.exGluteBridge": "Glute bridge",
  "preset.exClamshells": "Clamshells",
  "preset.exSingleLegGluteBridge": "Single-leg glute bridge",
  "preset.exFireHydrants": "Fire hydrants",
  "preset.exLateralLunges": "Lateral lunges",
  "preset.exCalfRaisesStraight": "Calf raises (straight knee)",
  "preset.exCalfRaisesBent": "Calf raises (bent knee)",
  "preset.exSingleLegBalanceAlphabet": "Single-leg balance — write the alphabet",
  "preset.exSquats": "Squats",
  "preset.exPushUps": "Push-ups",
  "preset.exReverseLunges": "Reverse lunges",
  "preset.exPlankShoulderTaps": "Plank shoulder taps",
  "preset.exSupermanHold": "Superman hold",
  "preset.exHang": "Hang",
  "preset.exPikePushUps": "Pike push-ups",
  "preset.exTricepDipsChair": "Tricep dips (chair)",
  "preset.exReverseWristCurls": "Reverse wrist curls",
  "preset.exScapularPushUps": "Scapular push-ups",
  "preset.exYtwRaises": "YTW raises",
  "preset.exWallSlides": "Wall slides",
  "preset.exHollowBodyHold": "Hollow body hold",

  // Preset library — form cues
  "preset.noteAllOut": "All-out effort — pick one move and go",
  "preset.noteStraightLine": "Straight line from head to heels",
  "preset.noteHipsHighDontSag": "Hips high, don't sag",
  "preset.noteLowerBackFloor": "Lower back pressed into the floor",
  "preset.noteSqueezeTop": "Squeeze at the top",
  "preset.noteSlowControlled": "Slow and controlled",
  "preset.noteHipsLevel": "Hips level",
  "preset.noteAlternateSidesHip": "Alternate sides, sit back into the hip",
  "preset.noteFullRangeSlowDown": "Full range, slow down phase",
  "preset.noteSoleus": "Targets the soleus — runners' favorite",
  "preset.noteAlphabetLeft": "Trace letters with your free foot, continuing from where you stopped last round. Eyes forward, barefoot if possible",
  "preset.noteAlphabetRight": "Same again on the other leg. Eyes forward, barefoot if possible",
  "preset.noteChestUpHeels": "Chest up, weight in heels",
  "preset.noteKneesDownFine": "Knees down is fine — full range beats ego",
  "preset.noteAlternateLegsKnee": "Alternate legs, knee tracks over toes",
  "preset.noteHipsQuiet": "Hips quiet, no rocking",
  "preset.noteSqueezeGlutesMidBack": "Squeeze glutes and mid-back",
  "preset.noteHangCrimp": "Open hand or half crimp — NEVER full crimp here",
  "preset.noteHangShoulders": "Shoulders engaged, elbows soft",
  "preset.noteBreathe": "Breathe",
  "preset.noteHangFoot": "Drop a foot to assist if failing",
  "preset.noteQualityOverCompletion": "Quality over completion",
  "preset.noteLastShakeOut": "Last one — then shake out",
  "preset.noteFullRangeKnees": "Full range — knees down beats half reps",
  "preset.noteHipsHighHead": "Hips high, head between arms",
  "preset.noteShouldersAwayEars": "Shoulders away from ears",
  "preset.noteLightSlowExtensors": "Light and slow — forearm extensors",
  "preset.noteArmsStraightBlades": "Arms straight, just the shoulder blades",
  "preset.noteFaceDownThumbs": "Face down, thumbs up, squeeze the mid-back",
  "preset.noteForearmsWall": "Forearms on the wall, slide slow",
  "preset.noteTopArmCeiling": "Top arm reaching to the ceiling",
  "preset.noteLowerBackTension": "Lower back pressed down — the body-tension position",
  "preset.noteStraightLineGlutes": "Straight line, glutes on",
  "preset.noteHipsHigh": "Hips high",
  "preset.noteOtherHalfTension": "The other half of body tension",

  // Equipment suggestions
  "equipment.resistanceBands": "Resistance bands",
  "equipment.balanceBoard": "Balance board",
  "equipment.kettlebell": "Kettlebell",
  "equipment.dumbbells": "Dumbbells",
  "equipment.barbellPlates": "Barbell + plates",
  "equipment.pullUpBar": "Pull-up bar",
  "equipment.foamRoller": "Foam roller",
  "equipment.yogaMat": "Yoga mat",
  "equipment.skippingRope": "Skipping rope",
  "equipment.boxStep": "Box / step",
  "equipment.medicineBall": "Medicine ball",
  "equipment.trx": "TRX / suspension trainer",
  "equipment.turboTrainer": "Turbo trainer",
  "equipment.treadmill": "Treadmill",
  "equipment.massageGun": "Massage gun",
  "equipment.gymMembership": "Gym membership",
} as const;

export const de: Partial<Record<keyof typeof en, string>> = {
  "workout.block": "Block",
  "workout.roundLabel": "Runde",
  "workout.warmUpNote": "Lockere Bewegung — Armkreisen, Beinschwingen, leichtes Laufen auf der Stelle",
  "workout.coolDownNote": "Langsames Dehnen — jede Dehnung halten, atmen",
  "workout.intervals": "Intervalle",
  "workout.workLabel": "Belastung",
  "workout.doneTimes": "{n}× gemacht",
  "workout.planBadge": "Plan",
  "workout.focusLabel": "Fokus",
  "workout.askForToday": "Bau mir ein Workout für heute",
  "workout.untitled": "Workout",
  "workout.readyToast": "Workout bereit: {title} (~{min} Min)",
  "workout.left": "links",
  "workout.right": "rechts",
  "player.undoFailed": "Rückgängig machen hat nicht geklappt — schau später in der Historie nach.",

  "preset.tabataTitle": "Tabata",
  "preset.coreTitle": "Läufer-Core",
  "preset.hipsTitle": "Hüfte & Gesäß",
  "preset.calvesTitle": "Waden & Sprunggelenke",
  "preset.fullbodyTitle": "Ganzkörperkraft",
  "preset.hangboardTitle": "Hangboard-Repeaters",
  "preset.antagonistTitle": "Antagonisten-Push",
  "preset.shouldersTitle": "Schulterstabilität",
  "preset.climbcoreTitle": "Kletterer-Core",

  "preset.tabataDesc": "Der Klassiker: 8 × 20 s Vollgas / 10 s Pause. 4 brutale Minuten.",
  "preset.coreDesc": "15 Min Rumpfstabilität — der Unterschied auf den letzten 5 km.",
  "preset.hipsDesc": "15 Min für die Muskeln, die deinen Schritt sauber halten.",
  "preset.calvesDesc": "10 Min Panzerung für den Unterschenkel — gegen Schienbeinkantensyndrom und Achillessehnen-Zwicken.",
  "preset.fullbodyDesc": "20 Min, ohne Geräte — Kraftausdauer für das ganze Chassis.",
  "preset.hangboardDesc": "4 Sätze à 6 × 7 s/3 s an einer bequemen Leiste. Nur für erfahrene Kletterer — Finger zuerst.",
  "preset.antagonistDesc": "15 Min Drücken — die Versicherung gegen Kletterellbogen und Rundrücken.",
  "preset.shouldersDesc": "12 Min für Rotatorenmanschette und Schulterblatt — das hält Gaston-Züge sauber.",
  "preset.climbcoreDesc": "15 Min Körperspannung — Hollow Body und Hüften, die deine Füße an der Wand halten.",

  "preset.focusConditioning": "Kondition",
  "preset.focusCore": "Core",
  "preset.focusHipsGlutes": "Hüfte & Gesäß",
  "preset.focusCalvesAnkles": "Waden & Sprunggelenke",
  "preset.focusFullBody": "Ganzkörper",
  "preset.focusFingers": "Finger",
  "preset.focusAntagonists": "Antagonisten",
  "preset.focusShoulders": "Schultern",

  "preset.blockTabata": "Tabata",
  "preset.blockCircuit": "Zirkel",
  "preset.blockRepeaters": "Repeaters",

  "preset.exPlank": "Plank",
  "preset.exSidePlank": "Seitstütz",
  "preset.exDeadBug": "Dead Bug",
  "preset.exGluteBridge": "Beckenheben",
  "preset.exClamshells": "Clamshells",
  "preset.exSingleLegGluteBridge": "Einbeiniges Beckenheben",
  "preset.exFireHydrants": "Fire Hydrants",
  "preset.exLateralLunges": "Seitliche Ausfallschritte",
  "preset.exCalfRaisesStraight": "Wadenheben (gestrecktes Knie)",
  "preset.exCalfRaisesBent": "Wadenheben (gebeugtes Knie)",
  "preset.exSingleLegBalanceAlphabet": "Einbeinstand — das Alphabet schreiben",
  "preset.exSquats": "Kniebeugen",
  "preset.exPushUps": "Liegestütze",
  "preset.exReverseLunges": "Ausfallschritte rückwärts",
  "preset.exPlankShoulderTaps": "Plank mit Schultertippen",
  "preset.exSupermanHold": "Superman-Halten",
  "preset.exHang": "Hängen",
  "preset.exPikePushUps": "Pike-Liegestütze",
  "preset.exTricepDipsChair": "Trizeps-Dips (Stuhl)",
  "preset.exReverseWristCurls": "Umgekehrte Handgelenkcurls",
  "preset.exScapularPushUps": "Skapula-Liegestütze",
  "preset.exYtwRaises": "YTW-Heben",
  "preset.exWallSlides": "Wall Slides",
  "preset.exHollowBodyHold": "Hollow Body Hold",

  "preset.noteAllOut": "Alles geben — such dir eine Übung aus und los",
  "preset.noteStraightLine": "Gerade Linie von Kopf bis Ferse",
  "preset.noteHipsHighDontSag": "Hüfte hoch, nicht durchhängen",
  "preset.noteLowerBackFloor": "Unteren Rücken in den Boden drücken",
  "preset.noteSqueezeTop": "Oben anspannen",
  "preset.noteSlowControlled": "Langsam und kontrolliert",
  "preset.noteHipsLevel": "Hüfte gerade halten",
  "preset.noteAlternateSidesHip": "Seiten abwechseln, in die Hüfte zurücksetzen",
  "preset.noteFullRangeSlowDown": "Volle Bewegung, langsam absenken",
  "preset.noteSoleus": "Trifft den Soleus — der Liebling der Läufer",
  "preset.noteAlphabetLeft": "Zeichne mit dem freien Fuß Buchstaben — mach dort weiter, wo du in der letzten Runde aufgehört hast. Blick nach vorn, wenn möglich barfuß",
  "preset.noteAlphabetRight": "Dasselbe auf dem anderen Bein. Blick nach vorn, wenn möglich barfuß",
  "preset.noteChestUpHeels": "Brust raus, Gewicht auf den Fersen",
  "preset.noteKneesDownFine": "Auf den Knien ist okay — volle Bewegung schlägt Ego",
  "preset.noteAlternateLegsKnee": "Beine abwechseln, Knie über den Zehen",
  "preset.noteHipsQuiet": "Hüfte ruhig, nicht schaukeln",
  "preset.noteSqueezeGlutesMidBack": "Gesäß und mittleren Rücken anspannen",
  "preset.noteHangCrimp": "Offene Hand oder Halbkrimp — hier NIEMALS voll aufgestellt",
  "preset.noteHangShoulders": "Schultern aktiv, Ellbogen weich",
  "preset.noteBreathe": "Atmen",
  "preset.noteHangFoot": "Wenn es nicht mehr geht, einen Fuß zur Hilfe absetzen",
  "preset.noteQualityOverCompletion": "Qualität vor Vollständigkeit",
  "preset.noteLastShakeOut": "Die letzte — dann ausschütteln",
  "preset.noteFullRangeKnees": "Volle Bewegung — auf den Knien schlägt halbe Wiederholungen",
  "preset.noteHipsHighHead": "Hüfte hoch, Kopf zwischen den Armen",
  "preset.noteShouldersAwayEars": "Schultern weg von den Ohren",
  "preset.noteLightSlowExtensors": "Leicht und langsam — Unterarmstrecker",
  "preset.noteArmsStraightBlades": "Arme gestreckt, nur die Schulterblätter",
  "preset.noteFaceDownThumbs": "Bauchlage, Daumen nach oben, mittleren Rücken anspannen",
  "preset.noteForearmsWall": "Unterarme an der Wand, langsam gleiten",
  "preset.noteTopArmCeiling": "Oberer Arm zur Decke gestreckt",
  "preset.noteLowerBackTension": "Unteren Rücken runterdrücken — die Körperspannungsposition",
  "preset.noteStraightLineGlutes": "Gerade Linie, Gesäß angespannt",
  "preset.noteHipsHigh": "Hüfte hoch",
  "preset.noteOtherHalfTension": "Die andere Hälfte der Körperspannung",

  "equipment.resistanceBands": "Widerstandsbänder",
  "equipment.balanceBoard": "Balance Board",
  "equipment.kettlebell": "Kettlebell",
  "equipment.dumbbells": "Kurzhanteln",
  "equipment.barbellPlates": "Langhantel + Scheiben",
  "equipment.pullUpBar": "Klimmzugstange",
  "equipment.foamRoller": "Faszienrolle",
  "equipment.yogaMat": "Yogamatte",
  "equipment.skippingRope": "Springseil",
  "equipment.boxStep": "Box / Stepper",
  "equipment.medicineBall": "Medizinball",
  "equipment.trx": "TRX / Schlingentrainer",
  "equipment.turboTrainer": "Rollentrainer",
  "equipment.treadmill": "Laufband",
  "equipment.massageGun": "Massagepistole",
  "equipment.gymMembership": "Fitnessstudio-Mitgliedschaft",
};

export const es: Partial<Record<keyof typeof en, string>> = {
  "workout.block": "Bloque",
  "workout.roundLabel": "Ronda",
  "workout.warmUpNote": "Movimiento suave — círculos de brazos, balanceos de pierna, trote ligero en el sitio",
  "workout.coolDownNote": "Estiramientos lentos — mantén cada estiramiento, respira",
  "workout.intervals": "Intervalos",
  "workout.workLabel": "Trabajo",
  "workout.doneTimes": "hecho {n}×",
  "workout.planBadge": "plan",
  "workout.focusLabel": "enfoque",
  "workout.askForToday": "Hazme un entrenamiento para hoy",
  "workout.untitled": "Entrenamiento",
  "workout.readyToast": "Entrenamiento listo: {title} (~{min} min)",
  "workout.left": "izquierda",
  "workout.right": "derecha",
  "player.undoFailed": "No se pudo deshacer — revisa el Historial más tarde.",

  "preset.tabataTitle": "Tabata",
  "preset.coreTitle": "Core para corredores",
  "preset.hipsTitle": "Caderas y glúteos",
  "preset.calvesTitle": "Gemelos y tobillos",
  "preset.fullbodyTitle": "Fuerza de cuerpo entero",
  "preset.hangboardTitle": "Repeaters en hangboard",
  "preset.antagonistTitle": "Empuje antagonista",
  "preset.shouldersTitle": "Estabilidad de hombro",
  "preset.climbcoreTitle": "Core para escaladores",

  "preset.tabataDesc": "El clásico: 8 × 20 s a tope / 10 s de descanso. 4 minutos brutales.",
  "preset.coreDesc": "15 min de estabilidad de tronco — la diferencia en los últimos 5 km.",
  "preset.hipsDesc": "15 min para los músculos que mantienen tu zancada firme.",
  "preset.calvesDesc": "10 min de blindaje para la pierna baja contra la periostitis y las molestias de aquiles.",
  "preset.fullbodyDesc": "20 min, sin material — resistencia de fuerza para todo el chasis.",
  "preset.hangboardDesc": "4 series de 6 × 7 s/3 s en una regleta cómoda. Solo escaladores con experiencia — los dedos primero.",
  "preset.antagonistDesc": "15 min de empuje — el seguro contra el codo de escalador y los hombros encorvados.",
  "preset.shouldersDesc": "12 min para el manguito y la escápula — lo que mantiene firmes los gastons.",
  "preset.climbcoreDesc": "15 min de tensión — hollow body y caderas que mantienen tus pies en la pared.",

  "preset.focusConditioning": "acondicionamiento",
  "preset.focusCore": "core",
  "preset.focusHipsGlutes": "caderas y glúteos",
  "preset.focusCalvesAnkles": "gemelos y tobillos",
  "preset.focusFullBody": "cuerpo entero",
  "preset.focusFingers": "dedos",
  "preset.focusAntagonists": "antagonistas",
  "preset.focusShoulders": "hombros",

  "preset.blockTabata": "Tabata",
  "preset.blockCircuit": "Circuito",
  "preset.blockRepeaters": "Repeaters",

  "preset.exPlank": "Plancha",
  "preset.exSidePlank": "Plancha lateral",
  "preset.exDeadBug": "Dead bug",
  "preset.exGluteBridge": "Puente de glúteos",
  "preset.exClamshells": "Almejas",
  "preset.exSingleLegGluteBridge": "Puente de glúteos a una pierna",
  "preset.exFireHydrants": "Hidrantes",
  "preset.exLateralLunges": "Zancadas laterales",
  "preset.exCalfRaisesStraight": "Elevación de talones (rodilla recta)",
  "preset.exCalfRaisesBent": "Elevación de talones (rodilla flexionada)",
  "preset.exSingleLegBalanceAlphabet": "Equilibrio a una pierna — escribe el abecedario",
  "preset.exSquats": "Sentadillas",
  "preset.exPushUps": "Flexiones",
  "preset.exReverseLunges": "Zancadas hacia atrás",
  "preset.exPlankShoulderTaps": "Plancha con toques de hombro",
  "preset.exSupermanHold": "Superman isométrico",
  "preset.exHang": "Colgada",
  "preset.exPikePushUps": "Flexiones pike",
  "preset.exTricepDipsChair": "Fondos de tríceps (silla)",
  "preset.exReverseWristCurls": "Curl de muñeca inverso",
  "preset.exScapularPushUps": "Flexiones escapulares",
  "preset.exYtwRaises": "Elevaciones YTW",
  "preset.exWallSlides": "Deslizamientos en pared",
  "preset.exHollowBodyHold": "Hollow body hold",

  "preset.noteAllOut": "A tope — elige un ejercicio y dale",
  "preset.noteStraightLine": "Línea recta de la cabeza a los talones",
  "preset.noteHipsHighDontSag": "Cadera alta, no la dejes caer",
  "preset.noteLowerBackFloor": "Zona lumbar pegada al suelo",
  "preset.noteSqueezeTop": "Aprieta arriba",
  "preset.noteSlowControlled": "Lento y controlado",
  "preset.noteHipsLevel": "Cadera nivelada",
  "preset.noteAlternateSidesHip": "Alterna lados, siéntate hacia atrás en la cadera",
  "preset.noteFullRangeSlowDown": "Rango completo, baja despacio",
  "preset.noteSoleus": "Trabaja el sóleo — el favorito de los corredores",
  "preset.noteAlphabetLeft": "Dibuja letras con el pie libre, siguiendo donde lo dejaste la ronda anterior. Mirada al frente, descalzo si puedes",
  "preset.noteAlphabetRight": "Lo mismo con la otra pierna. Mirada al frente, descalzo si puedes",
  "preset.noteChestUpHeels": "Pecho arriba, peso en los talones",
  "preset.noteKneesDownFine": "De rodillas está bien — el rango completo vale más que el ego",
  "preset.noteAlternateLegsKnee": "Alterna piernas, la rodilla sobre los dedos del pie",
  "preset.noteHipsQuiet": "Cadera quieta, sin balanceo",
  "preset.noteSqueezeGlutesMidBack": "Aprieta glúteos y espalda media",
  "preset.noteHangCrimp": "Mano abierta o semiarqueo — aquí NUNCA arqueo completo",
  "preset.noteHangShoulders": "Hombros activos, codos suaves",
  "preset.noteBreathe": "Respira",
  "preset.noteHangFoot": "Si fallas, apoya un pie para ayudarte",
  "preset.noteQualityOverCompletion": "Calidad antes que completar",
  "preset.noteLastShakeOut": "La última — luego sacude las manos",
  "preset.noteFullRangeKnees": "Rango completo — de rodillas vale más que medias repeticiones",
  "preset.noteHipsHighHead": "Cadera alta, cabeza entre los brazos",
  "preset.noteShouldersAwayEars": "Hombros lejos de las orejas",
  "preset.noteLightSlowExtensors": "Ligero y lento — extensores del antebrazo",
  "preset.noteArmsStraightBlades": "Brazos rectos, solo las escápulas",
  "preset.noteFaceDownThumbs": "Boca abajo, pulgares arriba, aprieta la espalda media",
  "preset.noteForearmsWall": "Antebrazos en la pared, desliza despacio",
  "preset.noteTopArmCeiling": "El brazo de arriba apunta al techo",
  "preset.noteLowerBackTension": "Zona lumbar pegada — la posición de tensión corporal",
  "preset.noteStraightLineGlutes": "Línea recta, glúteos activos",
  "preset.noteHipsHigh": "Cadera alta",
  "preset.noteOtherHalfTension": "La otra mitad de la tensión corporal",

  "equipment.resistanceBands": "Bandas elásticas",
  "equipment.balanceBoard": "Tabla de equilibrio",
  "equipment.kettlebell": "Kettlebell",
  "equipment.dumbbells": "Mancuernas",
  "equipment.barbellPlates": "Barra + discos",
  "equipment.pullUpBar": "Barra de dominadas",
  "equipment.foamRoller": "Rodillo de espuma",
  "equipment.yogaMat": "Esterilla de yoga",
  "equipment.skippingRope": "Cuerda de saltar",
  "equipment.boxStep": "Cajón / step",
  "equipment.medicineBall": "Balón medicinal",
  "equipment.trx": "TRX / entrenador en suspensión",
  "equipment.turboTrainer": "Rodillo de bici",
  "equipment.treadmill": "Cinta de correr",
  "equipment.massageGun": "Pistola de masaje",
  "equipment.gymMembership": "Suscripción al gimnasio",
};
