/**
 * Dictionary partial — "workout" area. Merged into src/lib/dict.ts.
 * Every key needs all three languages; scripts/check-i18n.ts enforces it.
 *
 * "workout.*" / "player.*" — the Workouts screen and the player.
 * "preset.*" — the built-in workout library (titles, focus, block labels,
 *   exercise names, form cues); resolved in guided-workout.ts.
 * "equipment.*" — the suggested-kit chips (src/lib/equipment.ts).
 * Templates use {n}, {title}, {min} placeholders — see fillTemplate() in
 * guided-workout.ts.
 */
export const en = {
  // Workouts screen + player
  "workout.block": "Block",
  "workout.roundLabel": "Round",
  "workout.warmUpNote": "Easy movement — arm circles, leg swings, light jog in place",
  "workout.coolDownNote": "Slow stretching — hold each stretch, breathe",
  "workout.intervals": "Intervals",
  "workout.workLabel": "Work",
  "workout.doneTimes": "done {n}×",
  "workout.planBadge": "plan",
  "workout.focusLabel": "focus",
  "workout.askForToday": "Make me a workout for today",
  "workout.untitled": "Workout",
  "workout.readyToast": "Workout ready: {title} (~{min} min)",
  "workout.left": "left",
  "workout.right": "right",
  "player.undoFailed": "Couldn't undo — check History later.",

  // Preset library — titles
  "preset.tabataTitle": "Tabata",
  "preset.coreTitle": "Runner's Core",
  "preset.hipsTitle": "Hips & Glutes",
  "preset.calvesTitle": "Calves & Ankles",
  "preset.fullbodyTitle": "Full-Body Strength",
  "preset.hangboardTitle": "Hangboard Repeaters",
  "preset.antagonistTitle": "Antagonist Push",
  "preset.shouldersTitle": "Shoulder Stability",
  "preset.climbcoreTitle": "Climber's Core",

  // Preset library — descriptions
  "preset.tabataDesc": "The classic: 8 × 20s all-out / 10s rest. 4 brutal minutes.",
  "preset.coreDesc": "15 min of trunk stability — the difference in the last 5k.",
  "preset.hipsDesc": "15 min for the muscles that keep your stride honest.",
  "preset.calvesDesc": "10 min of lower-leg armor against shin splints and achilles niggles.",
  "preset.fullbodyDesc": "20 min, no equipment — strength endurance for the whole chassis.",
  "preset.hangboardDesc": "4 sets of 6 × 7s/3s on a comfortable edge. Experienced climbers only — fingers first.",
  "preset.antagonistDesc": "15 min of pushing — the insurance policy against climber's elbow and hunched shoulders.",
  "preset.shouldersDesc": "12 min for the cuff and scapula — what keeps gaston moves honest.",
  "preset.climbcoreDesc": "15 min of tension — hollow body and hips that keep your feet on.",

  // Preset library — focus
  "preset.focusConditioning": "conditioning",
  "preset.focusCore": "core",
  "preset.focusHipsGlutes": "hips & glutes",
  "preset.focusCalvesAnkles": "calves & ankles",
  "preset.focusFullBody": "full body",
  "preset.focusFingers": "fingers",
  "preset.focusAntagonists": "antagonists",
  "preset.focusShoulders": "shoulders",

  // Preset library — block labels
  "preset.blockTabata": "Tabata",
  "preset.blockCircuit": "Circuit",
  "preset.blockRepeaters": "Repeaters",

  // Preset library — exercise names
  "preset.exPlank": "Plank",
  "preset.exSidePlank": "Side plank",
  "preset.exDeadBug": "Dead bug",
  "preset.exGluteBridge": "Glute bridge",
  "preset.exClamshells": "Clamshells",
  "preset.exSingleLegGluteBridge": "Single-leg glute bridge",
  "preset.exFireHydrants": "Fire hydrants",
  "preset.exLateralLunges": "Lateral lunges",
  "preset.exCalfRaisesStraight": "Calf raises (straight knee)",
  "preset.exCalfRaisesBent": "Calf raises (bent knee)",
  "preset.exSingleLegBalanceAlphabet": "Single-leg balance — write the alphabet",
  "preset.exSquats": "Squats",
  "preset.exPushUps": "Push-ups",
  "preset.exReverseLunges": "Reverse lunges",
  "preset.exPlankShoulderTaps": "Plank shoulder taps",
  "preset.exSupermanHold": "Superman hold",
  "preset.exHang": "Hang",
  "preset.exPikePushUps": "Pike push-ups",
  "preset.exTricepDipsChair": "Tricep dips (chair)",
  "preset.exReverseWristCurls": "Reverse wrist curls",
  "preset.exScapularPushUps": "Scapular push-ups",
  "preset.exYtwRaises": "YTW raises",
  "preset.exWallSlides": "Wall slides",
  "preset.exHollowBodyHold": "Hollow body hold",

  // Preset library — form cues
  "preset.noteAllOut": "All-out effort — pick one move and go",
  "preset.noteStraightLine": "Straight line from head to heels",
  "preset.noteHipsHighDontSag": "Hips high, don't sag",
  "preset.noteLowerBackFloor": "Lower back pressed into the floor",
  "preset.noteSqueezeTop": "Squeeze at the top",
  "preset.noteSlowControlled": "Slow and controlled",
  "preset.noteHipsLevel": "Hips level",
  "preset.noteAlternateSidesHip": "Alternate sides, sit back into the hip",
  "preset.noteFullRangeSlowDown": "Full range, slow down phase",
  "preset.noteSoleus": "Targets the soleus — runners' favorite",
  "preset.noteAlphabetLeft": "Trace letters with your free foot, continuing from where you stopped last round. Eyes forward, barefoot if possible",
  "preset.noteAlphabetRight": "Same again on the other leg. Eyes forward, barefoot if possible",
  "preset.noteChestUpHeels": "Chest up, weight in heels",
  "preset.noteKneesDownFine": "Knees down is fine — full range beats ego",
  "preset.noteAlternateLegsKnee": "Alternate legs, knee tracks over toes",
  "preset.noteHipsQuiet": "Hips quiet, no rocking",
  "preset.noteSqueezeGlutesMidBack": "Squeeze glutes and mid-back",
  "preset.noteHangCrimp": "Open hand or half crimp — NEVER full crimp here",
  "preset.noteHangShoulders": "Shoulders engaged, elbows soft",
  "preset.noteBreathe": "Breathe",
  "preset.noteHangFoot": "Drop a foot to assist if failing",
  "preset.noteQualityOverCompletion": "Quality over completion",
  "preset.noteLastShakeOut": "Last one — then shake out",
  "preset.noteFullRangeKnees": "Full range — knees down beats half reps",
  "preset.noteHipsHighHead": "Hips high, head between arms",
  "preset.noteShouldersAwayEars": "Shoulders away from ears",
  "preset.noteLightSlowExtensors": "Light and slow — forearm extensors",
  "preset.noteArmsStraightBlades": "Arms straight, just the shoulder blades",
  "preset.noteFaceDownThumbs": "Face down, thumbs up, squeeze the mid-back",
  "preset.noteForearmsWall": "Forearms on the wall, slide slow",
  "preset.noteTopArmCeiling": "Top arm reaching to the ceiling",
  "preset.noteLowerBackTension": "Lower back pressed down — the body-tension position",
  "preset.noteStraightLineGlutes": "Straight line, glutes on",
  "preset.noteHipsHigh": "Hips high",
  "preset.noteOtherHalfTension": "The other half of body tension",

  // Equipment suggestions
  "equipment.resistanceBands": "Resistance bands",
  "equipment.balanceBoard": "Balance board",
  "equipment.kettlebell": "Kettlebell",
  "equipment.dumbbells": "Dumbbells",
  "equipment.barbellPlates": "Barbell + plates",
  "equipment.pullUpBar": "Pull-up bar",
  "equipment.foamRoller": "Foam roller",
  "equipment.yogaMat": "Yoga mat",
  "equipment.skippingRope": "Skipping rope",
  "equipment.boxStep": "Box / step",
  "equipment.medicineBall": "Medicine ball",
  "equipment.trx": "TRX / suspension trainer",
  "equipment.turboTrainer": "Turbo trainer",
  "equipment.treadmill": "Treadmill",
  "equipment.massageGun": "Massage gun",
  "equipment.gymMembership": "Gym membership",

  // Yoga: tabs, flow player, the flow library, pose names and breath cues
  "workout.tabSc": "S&C",
  "workout.tabYoga": "Yoga",
  "workout.askForYogaToday": "Make me a yoga flow for today",
  "workout.askBroccoYoga": "Ask Brocco for a flow",
  "workout.askBroccoYogaSub": "Tell it your time and what feels tight — get a guided flow",
  "workout.yourFlows": "Your flows",
  "workout.nothingSavedYoga": "Nothing saved yet — ask Brocco for a flow and it lands here.",
  "workout.pose": "pose",
  "workout.posesPlural": "poses",
  "player.settleIn": "Settle in",
  "player.flowComplete": "Flow complete",
  "player.chime": "🔔 Chime",
  "player.breath": "🌬 Breath",
  "player.breatheIn": "Breathe in",
  "player.breatheOut": "Breathe out",
  "player.poseOf": "Pose",
  "preset.yogaMorningTitle": "Morning mobility",
  "preset.yogaMorningDesc": "10 min to unstick the spine and hips before the day starts.",
  "preset.yogaPostRunTitle": "Post-run stretch",
  "preset.yogaPostRunDesc": "12 min for calves, hip flexors and hamstrings — right after the shoes come off.",
  "preset.yogaHipsTitle": "Hip openers",
  "preset.yogaHipsDesc": "15 min of deep, patient holds for hips that sit all day and run all weekend.",
  "preset.yogaEveningTitle": "Evening wind-down",
  "preset.yogaEveningDesc": "20 min of slow floor poses to hand the day over to sleep.",
  "preset.yogaClimberTitle": "Climber's shoulders & thoracic",
  "preset.yogaClimberDesc": "12 min to open what pulling closes: chest, shoulders and the mid-back.",
  "preset.yogaYinTitle": "Recovery / yin",
  "preset.yogaYinDesc": "25 min of long, still holds — 2–3 minutes each. Props welcome, effort not.",
  "preset.yogaSunTitle": "Sun-salutation warm-up",
  "preset.yogaSunDesc": "8 min, three rounds of a flowing sequence — short holds, keep moving with the breath.",
  "preset.focusMobility": "mobility",
  "preset.focusRecovery": "recovery",
  "preset.focusHips": "hips",
  "preset.focusWindDown": "wind-down",
  "preset.focusShouldersThoracic": "shoulders & thoracic",
  "preset.focusWarmUp": "warm-up",
  "preset.blockFlow": "Flow",
  "preset.blockSunSalutation": "Sun salutation",
  "yoga.poseChildsPose": "Child's pose",
  "yoga.poseCat": "Cat pose",
  "yoga.poseCow": "Cow pose",
  "yoga.poseThreadTheNeedle": "Thread the needle",
  "yoga.poseDownwardDog": "Downward dog",
  "yoga.poseLowLunge": "Low lunge",
  "yoga.poseStandingForwardFold": "Standing forward fold",
  "yoga.poseMountain": "Mountain pose",
  "yoga.poseChair": "Chair pose",
  "yoga.poseTree": "Tree pose",
  "yoga.poseGarland": "Garland (deep squat)",
  "yoga.posePuppy": "Puppy pose",
  "yoga.poseSphinx": "Sphinx",
  "yoga.poseHalfSplit": "Half split",
  "yoga.poseLizard": "Lizard",
  "yoga.poseKneelingHipFlexor": "Kneeling hip flexor stretch",
  "yoga.posePigeon": "Pigeon",
  "yoga.poseReclinedFigureFour": "Reclined figure four",
  "yoga.poseSeatedForwardFold": "Seated forward fold",
  "yoga.poseSupineTwist": "Supine twist",
  "yoga.poseButterfly": "Butterfly",
  "yoga.poseHappyBaby": "Happy baby",
  "yoga.poseSeatedTwist": "Seated twist",
  "yoga.poseLegsUpTheWall": "Legs up the wall",
  "yoga.poseSavasana": "Savasana",
  "yoga.poseCobra": "Cobra",
  "yoga.poseCamel": "Camel",
  "yoga.poseLocust": "Locust",
  "yoga.posePlank": "Plank",
  "yoga.cueChildsPose": "Hips back to the heels, forehead down, long slow breaths into the back",
  "yoga.cueCat": "Exhale, round the spine, tuck the chin",
  "yoga.cueCow": "Inhale, drop the belly, lift the gaze",
  "yoga.cueThreadTheNeedle": "Slide the arm under, shoulder to the floor, breathe into the upper back",
  "yoga.cueDownwardDog": "Hips high, heels heavy, let the head hang",
  "yoga.cueDownwardDogPedal": "Pedal the heels slowly — one calf, then the other",
  "yoga.cueLowLunge": "Back knee down, hips forward, chest tall",
  "yoga.cueStandingForwardFold": "Soft knees, let the head hang, breathe into the hamstrings",
  "yoga.cueMountain": "Feet grounded, crown tall, breathe slowly",
  "yoga.cueChair": "Sit back, weight in the heels, arms reaching up",
  "yoga.cueTree": "Foot to calf or thigh, never the knee — find one still point",
  "yoga.cueGarland": "Heels down if you can, elbows press the knees wide",
  "yoga.cuePuppy": "Hips over the knees, chest melts to the floor",
  "yoga.cueSphinx": "Elbows under the shoulders, legs heavy, soft belly",
  "yoga.cueHalfSplit": "Front leg straight, hips back, fold from the hips",
  "yoga.cueLizard": "Both hands inside the front foot, sink low, breathe",
  "yoga.cueKneelingHipFlexor": "Tuck the tailbone, push the hip gently forward",
  "yoga.cuePigeon": "Square the hips, fold forward, soften a little more with each exhale",
  "yoga.cueReclinedFigureFour": "Ankle on the opposite knee, draw the thigh in, shoulders down",
  "yoga.cueSeatedForwardFold": "Long spine first, then fold — chase length, not depth",
  "yoga.cueSupineTwist": "Knees drop to one side, both shoulders stay down, gaze the other way",
  "yoga.cueButterfly": "Soles together, let the knees hang heavy, breathe into the hips",
  "yoga.cueHappyBaby": "Hold the feet, knees wide toward the armpits, rock gently",
  "yoga.cueSeatedTwist": "Inhale to grow tall, exhale to turn a little more",
  "yoga.cueLegsUpTheWall": "Hips close to the wall, arms open, nothing to do",
  "yoga.cueSavasana": "Let everything go heavy. Breathe without shaping it.",
  "yoga.cueCobra": "Hips stay down, chest lifts, elbows soft",
  "yoga.cueCamel": "Hands to the heels or lower back, lift the chest to the ceiling",
  "yoga.cueLocust": "Lift chest and legs together, squeeze between the shoulder blades",
  "yoga.cuePlank": "One straight line, breathe steadily",
  "yoga.cueSunFlow": "Move on the breath — one movement per inhale or exhale",
  "yoga.cueYinEdge": "Find your edge, then back off a little — settle in for the long hold",
} as const;

export const de: Partial<Record<keyof typeof en, string>> = {
  "workout.block": "Block",
  "workout.roundLabel": "Runde",
  "workout.warmUpNote": "Lockere Bewegung — Armkreisen, Beinschwingen, leichtes Laufen auf der Stelle",
  "workout.coolDownNote": "Langsames Dehnen — jede Dehnung halten, atmen",
  "workout.intervals": "Intervalle",
  "workout.workLabel": "Belastung",
  "workout.doneTimes": "{n}× gemacht",
  "workout.planBadge": "Plan",
  "workout.focusLabel": "Fokus",
  "workout.askForToday": "Bau mir ein Workout für heute",
  "workout.untitled": "Workout",
  "workout.readyToast": "Workout bereit: {title} (~{min} Min)",
  "workout.left": "links",
  "workout.right": "rechts",
  "player.undoFailed": "Rückgängig machen hat nicht geklappt — schau später in der Historie nach.",

  "preset.tabataTitle": "Tabata",
  "preset.coreTitle": "Läufer-Core",
  "preset.hipsTitle": "Hüfte & Gesäß",
  "preset.calvesTitle": "Waden & Sprunggelenke",
  "preset.fullbodyTitle": "Ganzkörperkraft",
  "preset.hangboardTitle": "Hangboard-Repeaters",
  "preset.antagonistTitle": "Antagonisten-Push",
  "preset.shouldersTitle": "Schulterstabilität",
  "preset.climbcoreTitle": "Kletterer-Core",

  "preset.tabataDesc": "Der Klassiker: 8 × 20 s Vollgas / 10 s Pause. 4 brutale Minuten.",
  "preset.coreDesc": "15 Min Rumpfstabilität — der Unterschied auf den letzten 5 km.",
  "preset.hipsDesc": "15 Min für die Muskeln, die deinen Schritt sauber halten.",
  "preset.calvesDesc": "10 Min Panzerung für den Unterschenkel — gegen Schienbeinkantensyndrom und Achillessehnen-Zwicken.",
  "preset.fullbodyDesc": "20 Min, ohne Geräte — Kraftausdauer für das ganze Chassis.",
  "preset.hangboardDesc": "4 Sätze à 6 × 7 s/3 s an einer bequemen Leiste. Nur für erfahrene Kletterer — Finger zuerst.",
  "preset.antagonistDesc": "15 Min Drücken — die Versicherung gegen Kletterellbogen und Rundrücken.",
  "preset.shouldersDesc": "12 Min für Rotatorenmanschette und Schulterblatt — das hält Gaston-Züge sauber.",
  "preset.climbcoreDesc": "15 Min Körperspannung — Hollow Body und Hüften, die deine Füße an der Wand halten.",

  "preset.focusConditioning": "Kondition",
  "preset.focusCore": "Core",
  "preset.focusHipsGlutes": "Hüfte & Gesäß",
  "preset.focusCalvesAnkles": "Waden & Sprunggelenke",
  "preset.focusFullBody": "Ganzkörper",
  "preset.focusFingers": "Finger",
  "preset.focusAntagonists": "Antagonisten",
  "preset.focusShoulders": "Schultern",

  "preset.blockTabata": "Tabata",
  "preset.blockCircuit": "Zirkel",
  "preset.blockRepeaters": "Repeaters",

  "preset.exPlank": "Plank",
  "preset.exSidePlank": "Seitstütz",
  "preset.exDeadBug": "Dead Bug",
  "preset.exGluteBridge": "Beckenheben",
  "preset.exClamshells": "Clamshells",
  "preset.exSingleLegGluteBridge": "Einbeiniges Beckenheben",
  "preset.exFireHydrants": "Fire Hydrants",
  "preset.exLateralLunges": "Seitliche Ausfallschritte",
  "preset.exCalfRaisesStraight": "Wadenheben (gestrecktes Knie)",
  "preset.exCalfRaisesBent": "Wadenheben (gebeugtes Knie)",
  "preset.exSingleLegBalanceAlphabet": "Einbeinstand — das Alphabet schreiben",
  "preset.exSquats": "Kniebeugen",
  "preset.exPushUps": "Liegestütze",
  "preset.exReverseLunges": "Ausfallschritte rückwärts",
  "preset.exPlankShoulderTaps": "Plank mit Schultertippen",
  "preset.exSupermanHold": "Superman-Halten",
  "preset.exHang": "Hängen",
  "preset.exPikePushUps": "Pike-Liegestütze",
  "preset.exTricepDipsChair": "Trizeps-Dips (Stuhl)",
  "preset.exReverseWristCurls": "Umgekehrte Handgelenkcurls",
  "preset.exScapularPushUps": "Skapula-Liegestütze",
  "preset.exYtwRaises": "YTW-Heben",
  "preset.exWallSlides": "Wall Slides",
  "preset.exHollowBodyHold": "Hollow Body Hold",

  "preset.noteAllOut": "Alles geben — such dir eine Übung aus und los",
  "preset.noteStraightLine": "Gerade Linie von Kopf bis Ferse",
  "preset.noteHipsHighDontSag": "Hüfte hoch, nicht durchhängen",
  "preset.noteLowerBackFloor": "Unteren Rücken in den Boden drücken",
  "preset.noteSqueezeTop": "Oben anspannen",
  "preset.noteSlowControlled": "Langsam und kontrolliert",
  "preset.noteHipsLevel": "Hüfte gerade halten",
  "preset.noteAlternateSidesHip": "Seiten abwechseln, in die Hüfte zurücksetzen",
  "preset.noteFullRangeSlowDown": "Volle Bewegung, langsam absenken",
  "preset.noteSoleus": "Trifft den Soleus — der Liebling der Läufer",
  "preset.noteAlphabetLeft": "Zeichne mit dem freien Fuß Buchstaben — mach dort weiter, wo du in der letzten Runde aufgehört hast. Blick nach vorn, wenn möglich barfuß",
  "preset.noteAlphabetRight": "Dasselbe auf dem anderen Bein. Blick nach vorn, wenn möglich barfuß",
  "preset.noteChestUpHeels": "Brust raus, Gewicht auf den Fersen",
  "preset.noteKneesDownFine": "Auf den Knien ist okay — volle Bewegung schlägt Ego",
  "preset.noteAlternateLegsKnee": "Beine abwechseln, Knie über den Zehen",
  "preset.noteHipsQuiet": "Hüfte ruhig, nicht schaukeln",
  "preset.noteSqueezeGlutesMidBack": "Gesäß und mittleren Rücken anspannen",
  "preset.noteHangCrimp": "Offene Hand oder Halbkrimp — hier NIEMALS voll aufgestellt",
  "preset.noteHangShoulders": "Schultern aktiv, Ellbogen weich",
  "preset.noteBreathe": "Atmen",
  "preset.noteHangFoot": "Wenn es nicht mehr geht, einen Fuß zur Hilfe absetzen",
  "preset.noteQualityOverCompletion": "Qualität vor Vollständigkeit",
  "preset.noteLastShakeOut": "Die letzte — dann ausschütteln",
  "preset.noteFullRangeKnees": "Volle Bewegung — auf den Knien schlägt halbe Wiederholungen",
  "preset.noteHipsHighHead": "Hüfte hoch, Kopf zwischen den Armen",
  "preset.noteShouldersAwayEars": "Schultern weg von den Ohren",
  "preset.noteLightSlowExtensors": "Leicht und langsam — Unterarmstrecker",
  "preset.noteArmsStraightBlades": "Arme gestreckt, nur die Schulterblätter",
  "preset.noteFaceDownThumbs": "Bauchlage, Daumen nach oben, mittleren Rücken anspannen",
  "preset.noteForearmsWall": "Unterarme an der Wand, langsam gleiten",
  "preset.noteTopArmCeiling": "Oberer Arm zur Decke gestreckt",
  "preset.noteLowerBackTension": "Unteren Rücken runterdrücken — die Körperspannungsposition",
  "preset.noteStraightLineGlutes": "Gerade Linie, Gesäß angespannt",
  "preset.noteHipsHigh": "Hüfte hoch",
  "preset.noteOtherHalfTension": "Die andere Hälfte der Körperspannung",

  "equipment.resistanceBands": "Widerstandsbänder",
  "equipment.balanceBoard": "Balance Board",
  "equipment.kettlebell": "Kettlebell",
  "equipment.dumbbells": "Kurzhanteln",
  "equipment.barbellPlates": "Langhantel + Scheiben",
  "equipment.pullUpBar": "Klimmzugstange",
  "equipment.foamRoller": "Faszienrolle",
  "equipment.yogaMat": "Yogamatte",
  "equipment.skippingRope": "Springseil",
  "equipment.boxStep": "Box / Stepper",
  "equipment.medicineBall": "Medizinball",
  "equipment.trx": "TRX / Schlingentrainer",
  "equipment.turboTrainer": "Rollentrainer",
  "equipment.treadmill": "Laufband",
  "equipment.massageGun": "Massagepistole",
  "equipment.gymMembership": "Fitnessstudio-Mitgliedschaft",

  // Yoga: tabs, flow player, the flow library, pose names and breath cues
  "workout.tabSc": "S&C",
  "workout.tabYoga": "Yoga",
  "workout.askForYogaToday": "Bau mir einen Yoga-Flow für heute",
  "workout.askBroccoYoga": "Frag Brocco nach einem Flow",
  "workout.askBroccoYogaSub": "Sag ihm, wie viel Zeit du hast und was sich steif anfühlt — du bekommst einen geführten Flow",
  "workout.yourFlows": "Deine Flows",
  "workout.nothingSavedYoga": "Noch nichts gespeichert — frag Brocco nach einem Flow und er landet hier.",
  "workout.pose": "Pose",
  "workout.posesPlural": "Posen",
  "player.settleIn": "Ankommen",
  "player.flowComplete": "Flow geschafft",
  "player.chime": "🔔 Klang",
  "player.breath": "🌬 Atem",
  "player.breatheIn": "Einatmen",
  "player.breatheOut": "Ausatmen",
  "player.poseOf": "Pose",
  "preset.yogaMorningTitle": "Morgen-Mobility",
  "preset.yogaMorningDesc": "10 Min, um Wirbelsäule und Hüfte zu lösen, bevor der Tag beginnt.",
  "preset.yogaPostRunTitle": "Dehnen nach dem Lauf",
  "preset.yogaPostRunDesc": "12 Min für Waden, Hüftbeuger und hintere Oberschenkel — direkt nachdem die Schuhe aus sind.",
  "preset.yogaHipsTitle": "Hüftöffner",
  "preset.yogaHipsDesc": "15 Min tiefe, geduldige Haltungen für Hüften, die den ganzen Tag sitzen und am Wochenende laufen.",
  "preset.yogaEveningTitle": "Abend-Entspannung",
  "preset.yogaEveningDesc": "20 Min langsame Bodenposen, um den Tag an den Schlaf zu übergeben.",
  "preset.yogaClimberTitle": "Kletterer-Schultern & Brustwirbelsäule",
  "preset.yogaClimberDesc": "12 Min, um zu öffnen, was das Ziehen verschließt: Brust, Schultern und mittlerer Rücken.",
  "preset.yogaYinTitle": "Regeneration / Yin",
  "preset.yogaYinDesc": "25 Min lange, ruhige Haltungen — je 2–3 Minuten. Hilfsmittel willkommen, Anstrengung nicht.",
  "preset.yogaSunTitle": "Sonnengruß-Aufwärmen",
  "preset.yogaSunDesc": "8 Min, drei Runden einer fließenden Sequenz — kurze Haltungen, mit dem Atem in Bewegung bleiben.",
  "preset.focusMobility": "Mobility",
  "preset.focusRecovery": "Regeneration",
  "preset.focusHips": "Hüfte",
  "preset.focusWindDown": "Entspannung",
  "preset.focusShouldersThoracic": "Schultern & BWS",
  "preset.focusWarmUp": "Aufwärmen",
  "preset.blockFlow": "Flow",
  "preset.blockSunSalutation": "Sonnengruß",
  "yoga.poseChildsPose": "Kindhaltung",
  "yoga.poseCat": "Katze",
  "yoga.poseCow": "Kuh",
  "yoga.poseThreadTheNeedle": "Nadelöhr",
  "yoga.poseDownwardDog": "Herabschauender Hund",
  "yoga.poseLowLunge": "Tiefer Ausfallschritt",
  "yoga.poseStandingForwardFold": "Stehende Vorbeuge",
  "yoga.poseMountain": "Berghaltung",
  "yoga.poseChair": "Stuhlhaltung",
  "yoga.poseTree": "Baumhaltung",
  "yoga.poseGarland": "Girlande (tiefe Hocke)",
  "yoga.posePuppy": "Welpenhaltung",
  "yoga.poseSphinx": "Sphinx",
  "yoga.poseHalfSplit": "Halber Spagat",
  "yoga.poseLizard": "Eidechse",
  "yoga.poseKneelingHipFlexor": "Kniende Hüftbeuger-Dehnung",
  "yoga.posePigeon": "Taube",
  "yoga.poseReclinedFigureFour": "Liegende Vier",
  "yoga.poseSeatedForwardFold": "Sitzende Vorbeuge",
  "yoga.poseSupineTwist": "Liegende Drehung",
  "yoga.poseButterfly": "Schmetterling",
  "yoga.poseHappyBaby": "Glückliches Baby",
  "yoga.poseSeatedTwist": "Sitzende Drehung",
  "yoga.poseLegsUpTheWall": "Beine an der Wand",
  "yoga.poseSavasana": "Savasana",
  "yoga.poseCobra": "Kobra",
  "yoga.poseCamel": "Kamel",
  "yoga.poseLocust": "Heuschrecke",
  "yoga.posePlank": "Plank",
  "yoga.cueChildsPose": "Hüfte zu den Fersen, Stirn ab, lange langsame Atemzüge in den Rücken",
  "yoga.cueCat": "Ausatmen, Rücken runden, Kinn zur Brust",
  "yoga.cueCow": "Einatmen, Bauch sinken lassen, Blick heben",
  "yoga.cueThreadTheNeedle": "Arm durchschieben, Schulter zum Boden, in den oberen Rücken atmen",
  "yoga.cueDownwardDog": "Hüfte hoch, Fersen schwer, Kopf hängen lassen",
  "yoga.cueDownwardDogPedal": "Fersen langsam treten — eine Wade, dann die andere",
  "yoga.cueLowLunge": "Hinteres Knie ab, Hüfte nach vorn, Brust aufrecht",
  "yoga.cueStandingForwardFold": "Knie weich, Kopf hängen lassen, in die hinteren Oberschenkel atmen",
  "yoga.cueMountain": "Füße geerdet, Scheitel hoch, langsam atmen",
  "yoga.cueChair": "Zurücksetzen, Gewicht auf den Fersen, Arme nach oben",
  "yoga.cueTree": "Fuß an Wade oder Oberschenkel, nie ans Knie — einen ruhigen Punkt fixieren",
  "yoga.cueGarland": "Fersen runter, wenn möglich, Ellbogen drücken die Knie auseinander",
  "yoga.cuePuppy": "Hüfte über den Knien, Brust zum Boden sinken lassen",
  "yoga.cueSphinx": "Ellbogen unter den Schultern, Beine schwer, Bauch weich",
  "yoga.cueHalfSplit": "Vorderes Bein gestreckt, Hüfte zurück, aus der Hüfte beugen",
  "yoga.cueLizard": "Beide Hände innen neben dem vorderen Fuß, tief sinken, atmen",
  "yoga.cueKneelingHipFlexor": "Steißbein einrollen, Hüfte sanft nach vorn schieben",
  "yoga.cuePigeon": "Hüfte gerade, nach vorn beugen, mit jedem Ausatmen etwas weicher werden",
  "yoga.cueReclinedFigureFour": "Knöchel aufs andere Knie, Oberschenkel heranziehen, Schultern unten",
  "yoga.cueSeatedForwardFold": "Erst langer Rücken, dann beugen — Länge zählt, nicht Tiefe",
  "yoga.cueSupineTwist": "Knie zur Seite sinken lassen, beide Schultern bleiben unten, Blick zur anderen Seite",
  "yoga.cueButterfly": "Fußsohlen zusammen, Knie schwer hängen lassen, in die Hüfte atmen",
  "yoga.cueHappyBaby": "Füße greifen, Knie weit zu den Achseln, sanft schaukeln",
  "yoga.cueSeatedTwist": "Einatmen und aufrichten, ausatmen und etwas weiter drehen",
  "yoga.cueLegsUpTheWall": "Hüfte nah an der Wand, Arme offen, nichts zu tun",
  "yoga.cueSavasana": "Alles schwer werden lassen. Atmen, ohne es zu formen.",
  "yoga.cueCobra": "Hüfte bleibt unten, Brust hebt sich, Ellbogen weich",
  "yoga.cueCamel": "Hände zu den Fersen oder an den unteren Rücken, Brust zur Decke heben",
  "yoga.cueLocust": "Brust und Beine zusammen heben, Schulterblätter zusammenziehen",
  "yoga.cuePlank": "Eine gerade Linie, ruhig weiteratmen",
  "yoga.cueSunFlow": "Mit dem Atem bewegen — eine Bewegung pro Ein- oder Ausatmen",
  "yoga.cueYinEdge": "Deine Grenze finden, dann etwas zurücknehmen — für die lange Haltung einrichten",
};

export const es: Partial<Record<keyof typeof en, string>> = {
  "workout.block": "Bloque",
  "workout.roundLabel": "Ronda",
  "workout.warmUpNote": "Movimiento suave — círculos de brazos, balanceos de pierna, trote ligero en el sitio",
  "workout.coolDownNote": "Estiramientos lentos — mantén cada estiramiento, respira",
  "workout.intervals": "Intervalos",
  "workout.workLabel": "Trabajo",
  "workout.doneTimes": "hecho {n}×",
  "workout.planBadge": "plan",
  "workout.focusLabel": "enfoque",
  "workout.askForToday": "Hazme un entrenamiento para hoy",
  "workout.untitled": "Entrenamiento",
  "workout.readyToast": "Entrenamiento listo: {title} (~{min} min)",
  "workout.left": "izquierda",
  "workout.right": "derecha",
  "player.undoFailed": "No se pudo deshacer — revisa el Historial más tarde.",

  "preset.tabataTitle": "Tabata",
  "preset.coreTitle": "Core para corredores",
  "preset.hipsTitle": "Caderas y glúteos",
  "preset.calvesTitle": "Gemelos y tobillos",
  "preset.fullbodyTitle": "Fuerza de cuerpo entero",
  "preset.hangboardTitle": "Repeaters en hangboard",
  "preset.antagonistTitle": "Empuje antagonista",
  "preset.shouldersTitle": "Estabilidad de hombro",
  "preset.climbcoreTitle": "Core para escaladores",

  "preset.tabataDesc": "El clásico: 8 × 20 s a tope / 10 s de descanso. 4 minutos brutales.",
  "preset.coreDesc": "15 min de estabilidad de tronco — la diferencia en los últimos 5 km.",
  "preset.hipsDesc": "15 min para los músculos que mantienen tu zancada firme.",
  "preset.calvesDesc": "10 min de blindaje para la pierna baja contra la periostitis y las molestias de aquiles.",
  "preset.fullbodyDesc": "20 min, sin material — resistencia de fuerza para todo el chasis.",
  "preset.hangboardDesc": "4 series de 6 × 7 s/3 s en una regleta cómoda. Solo escaladores con experiencia — los dedos primero.",
  "preset.antagonistDesc": "15 min de empuje — el seguro contra el codo de escalador y los hombros encorvados.",
  "preset.shouldersDesc": "12 min para el manguito y la escápula — lo que mantiene firmes los gastons.",
  "preset.climbcoreDesc": "15 min de tensión — hollow body y caderas que mantienen tus pies en la pared.",

  "preset.focusConditioning": "acondicionamiento",
  "preset.focusCore": "core",
  "preset.focusHipsGlutes": "caderas y glúteos",
  "preset.focusCalvesAnkles": "gemelos y tobillos",
  "preset.focusFullBody": "cuerpo entero",
  "preset.focusFingers": "dedos",
  "preset.focusAntagonists": "antagonistas",
  "preset.focusShoulders": "hombros",

  "preset.blockTabata": "Tabata",
  "preset.blockCircuit": "Circuito",
  "preset.blockRepeaters": "Repeaters",

  "preset.exPlank": "Plancha",
  "preset.exSidePlank": "Plancha lateral",
  "preset.exDeadBug": "Dead bug",
  "preset.exGluteBridge": "Puente de glúteos",
  "preset.exClamshells": "Almejas",
  "preset.exSingleLegGluteBridge": "Puente de glúteos a una pierna",
  "preset.exFireHydrants": "Hidrantes",
  "preset.exLateralLunges": "Zancadas laterales",
  "preset.exCalfRaisesStraight": "Elevación de talones (rodilla recta)",
  "preset.exCalfRaisesBent": "Elevación de talones (rodilla flexionada)",
  "preset.exSingleLegBalanceAlphabet": "Equilibrio a una pierna — escribe el abecedario",
  "preset.exSquats": "Sentadillas",
  "preset.exPushUps": "Flexiones",
  "preset.exReverseLunges": "Zancadas hacia atrás",
  "preset.exPlankShoulderTaps": "Plancha con toques de hombro",
  "preset.exSupermanHold": "Superman isométrico",
  "preset.exHang": "Colgada",
  "preset.exPikePushUps": "Flexiones pike",
  "preset.exTricepDipsChair": "Fondos de tríceps (silla)",
  "preset.exReverseWristCurls": "Curl de muñeca inverso",
  "preset.exScapularPushUps": "Flexiones escapulares",
  "preset.exYtwRaises": "Elevaciones YTW",
  "preset.exWallSlides": "Deslizamientos en pared",
  "preset.exHollowBodyHold": "Hollow body hold",

  "preset.noteAllOut": "A tope — elige un ejercicio y dale",
  "preset.noteStraightLine": "Línea recta de la cabeza a los talones",
  "preset.noteHipsHighDontSag": "Cadera alta, no la dejes caer",
  "preset.noteLowerBackFloor": "Zona lumbar pegada al suelo",
  "preset.noteSqueezeTop": "Aprieta arriba",
  "preset.noteSlowControlled": "Lento y controlado",
  "preset.noteHipsLevel": "Cadera nivelada",
  "preset.noteAlternateSidesHip": "Alterna lados, siéntate hacia atrás en la cadera",
  "preset.noteFullRangeSlowDown": "Rango completo, baja despacio",
  "preset.noteSoleus": "Trabaja el sóleo — el favorito de los corredores",
  "preset.noteAlphabetLeft": "Dibuja letras con el pie libre, siguiendo donde lo dejaste la ronda anterior. Mirada al frente, descalzo si puedes",
  "preset.noteAlphabetRight": "Lo mismo con la otra pierna. Mirada al frente, descalzo si puedes",
  "preset.noteChestUpHeels": "Pecho arriba, peso en los talones",
  "preset.noteKneesDownFine": "De rodillas está bien — el rango completo vale más que el ego",
  "preset.noteAlternateLegsKnee": "Alterna piernas, la rodilla sobre los dedos del pie",
  "preset.noteHipsQuiet": "Cadera quieta, sin balanceo",
  "preset.noteSqueezeGlutesMidBack": "Aprieta glúteos y espalda media",
  "preset.noteHangCrimp": "Mano abierta o semiarqueo — aquí NUNCA arqueo completo",
  "preset.noteHangShoulders": "Hombros activos, codos suaves",
  "preset.noteBreathe": "Respira",
  "preset.noteHangFoot": "Si fallas, apoya un pie para ayudarte",
  "preset.noteQualityOverCompletion": "Calidad antes que completar",
  "preset.noteLastShakeOut": "La última — luego sacude las manos",
  "preset.noteFullRangeKnees": "Rango completo — de rodillas vale más que medias repeticiones",
  "preset.noteHipsHighHead": "Cadera alta, cabeza entre los brazos",
  "preset.noteShouldersAwayEars": "Hombros lejos de las orejas",
  "preset.noteLightSlowExtensors": "Ligero y lento — extensores del antebrazo",
  "preset.noteArmsStraightBlades": "Brazos rectos, solo las escápulas",
  "preset.noteFaceDownThumbs": "Boca abajo, pulgares arriba, aprieta la espalda media",
  "preset.noteForearmsWall": "Antebrazos en la pared, desliza despacio",
  "preset.noteTopArmCeiling": "El brazo de arriba apunta al techo",
  "preset.noteLowerBackTension": "Zona lumbar pegada — la posición de tensión corporal",
  "preset.noteStraightLineGlutes": "Línea recta, glúteos activos",
  "preset.noteHipsHigh": "Cadera alta",
  "preset.noteOtherHalfTension": "La otra mitad de la tensión corporal",

  "equipment.resistanceBands": "Bandas elásticas",
  "equipment.balanceBoard": "Tabla de equilibrio",
  "equipment.kettlebell": "Kettlebell",
  "equipment.dumbbells": "Mancuernas",
  "equipment.barbellPlates": "Barra + discos",
  "equipment.pullUpBar": "Barra de dominadas",
  "equipment.foamRoller": "Rodillo de espuma",
  "equipment.yogaMat": "Esterilla de yoga",
  "equipment.skippingRope": "Cuerda de saltar",
  "equipment.boxStep": "Cajón / step",
  "equipment.medicineBall": "Balón medicinal",
  "equipment.trx": "TRX / entrenador en suspensión",
  "equipment.turboTrainer": "Rodillo de bici",
  "equipment.treadmill": "Cinta de correr",
  "equipment.massageGun": "Pistola de masaje",
  "equipment.gymMembership": "Suscripción al gimnasio",

  // Yoga: tabs, flow player, the flow library, pose names and breath cues
  "workout.tabSc": "S&C",
  "workout.tabYoga": "Yoga",
  "workout.askForYogaToday": "Hazme un flow de yoga para hoy",
  "workout.askBroccoYoga": "Pídele un flow a Brocco",
  "workout.askBroccoYogaSub": "Dile cuánto tiempo tienes y qué sientes cargado — recibe un flow guiado",
  "workout.yourFlows": "Tus flows",
  "workout.nothingSavedYoga": "Nada guardado todavía — pídele un flow a Brocco y aparecerá aquí.",
  "workout.pose": "postura",
  "workout.posesPlural": "posturas",
  "player.settleIn": "Acomódate",
  "player.flowComplete": "Flow completado",
  "player.chime": "🔔 Campanilla",
  "player.breath": "🌬 Respiración",
  "player.breatheIn": "Inhala",
  "player.breatheOut": "Exhala",
  "player.poseOf": "Postura",
  "preset.yogaMorningTitle": "Movilidad matinal",
  "preset.yogaMorningDesc": "10 min para soltar columna y caderas antes de que empiece el día.",
  "preset.yogaPostRunTitle": "Estiramiento post-carrera",
  "preset.yogaPostRunDesc": "12 min para gemelos, flexores de cadera e isquios — justo al quitarte las zapatillas.",
  "preset.yogaHipsTitle": "Apertura de caderas",
  "preset.yogaHipsDesc": "15 min de posturas profundas y pacientes para caderas que pasan el día sentadas y el fin de semana corriendo.",
  "preset.yogaEveningTitle": "Relajación nocturna",
  "preset.yogaEveningDesc": "20 min de posturas lentas en el suelo para entregarle el día al sueño.",
  "preset.yogaClimberTitle": "Hombros y dorsal del escalador",
  "preset.yogaClimberDesc": "12 min para abrir lo que cierra el tirar: pecho, hombros y espalda media.",
  "preset.yogaYinTitle": "Recuperación / yin",
  "preset.yogaYinDesc": "25 min de posturas largas y quietas — 2–3 minutos cada una. Los apoyos son bienvenidos, el esfuerzo no.",
  "preset.yogaSunTitle": "Calentamiento con saludos al sol",
  "preset.yogaSunDesc": "8 min, tres rondas de una secuencia fluida — posturas cortas, sigue moviéndote con la respiración.",
  "preset.focusMobility": "movilidad",
  "preset.focusRecovery": "recuperación",
  "preset.focusHips": "caderas",
  "preset.focusWindDown": "relajación",
  "preset.focusShouldersThoracic": "hombros y dorsal",
  "preset.focusWarmUp": "calentamiento",
  "preset.blockFlow": "Flow",
  "preset.blockSunSalutation": "Saludo al sol",
  "yoga.poseChildsPose": "Postura del niño",
  "yoga.poseCat": "Postura del gato",
  "yoga.poseCow": "Postura de la vaca",
  "yoga.poseThreadTheNeedle": "Enhebrar la aguja",
  "yoga.poseDownwardDog": "Perro boca abajo",
  "yoga.poseLowLunge": "Zancada baja",
  "yoga.poseStandingForwardFold": "Flexión hacia delante de pie",
  "yoga.poseMountain": "Postura de la montaña",
  "yoga.poseChair": "Postura de la silla",
  "yoga.poseTree": "Postura del árbol",
  "yoga.poseGarland": "Guirnalda (sentadilla profunda)",
  "yoga.posePuppy": "Postura del cachorro",
  "yoga.poseSphinx": "Esfinge",
  "yoga.poseHalfSplit": "Medio split",
  "yoga.poseLizard": "Lagarto",
  "yoga.poseKneelingHipFlexor": "Estiramiento de flexores de cadera de rodillas",
  "yoga.posePigeon": "Paloma",
  "yoga.poseReclinedFigureFour": "Cuatro tumbado",
  "yoga.poseSeatedForwardFold": "Flexión hacia delante sentado",
  "yoga.poseSupineTwist": "Torsión tumbado",
  "yoga.poseButterfly": "Mariposa",
  "yoga.poseHappyBaby": "Bebé feliz",
  "yoga.poseSeatedTwist": "Torsión sentado",
  "yoga.poseLegsUpTheWall": "Piernas en la pared",
  "yoga.poseSavasana": "Savasana",
  "yoga.poseCobra": "Cobra",
  "yoga.poseCamel": "Camello",
  "yoga.poseLocust": "Langosta",
  "yoga.posePlank": "Plancha",
  "yoga.cueChildsPose": "Caderas hacia los talones, frente al suelo, respiraciones largas y lentas hacia la espalda",
  "yoga.cueCat": "Exhala, redondea la columna, mete la barbilla",
  "yoga.cueCow": "Inhala, deja caer el vientre, eleva la mirada",
  "yoga.cueThreadTheNeedle": "Desliza el brazo por debajo, hombro al suelo, respira hacia la espalda alta",
  "yoga.cueDownwardDog": "Caderas altas, talones pesados, deja colgar la cabeza",
  "yoga.cueDownwardDogPedal": "Pedalea despacio con los talones — un gemelo, luego el otro",
  "yoga.cueLowLunge": "Rodilla trasera al suelo, caderas hacia delante, pecho erguido",
  "yoga.cueStandingForwardFold": "Rodillas suaves, deja colgar la cabeza, respira hacia los isquios",
  "yoga.cueMountain": "Pies enraizados, coronilla alta, respira despacio",
  "yoga.cueChair": "Siéntate hacia atrás, peso en los talones, brazos hacia arriba",
  "yoga.cueTree": "Pie en la pantorrilla o el muslo, nunca en la rodilla — fija un punto quieto",
  "yoga.cueGarland": "Talones abajo si puedes, los codos abren las rodillas",
  "yoga.cuePuppy": "Caderas sobre las rodillas, el pecho se funde con el suelo",
  "yoga.cueSphinx": "Codos bajo los hombros, piernas pesadas, vientre suave",
  "yoga.cueHalfSplit": "Pierna delantera recta, caderas atrás, flexiona desde la cadera",
  "yoga.cueLizard": "Ambas manos por dentro del pie delantero, baja, respira",
  "yoga.cueKneelingHipFlexor": "Mete el coxis, empuja la cadera suavemente hacia delante",
  "yoga.cuePigeon": "Caderas cuadradas, flexiona hacia delante, suelta un poco más con cada exhalación",
  "yoga.cueReclinedFigureFour": "Tobillo sobre la rodilla contraria, acerca el muslo, hombros abajo",
  "yoga.cueSeatedForwardFold": "Primero columna larga, luego flexiona — busca longitud, no profundidad",
  "yoga.cueSupineTwist": "Las rodillas caen a un lado, ambos hombros quedan abajo, mirada al otro lado",
  "yoga.cueButterfly": "Plantas juntas, deja caer las rodillas, respira hacia las caderas",
  "yoga.cueHappyBaby": "Sujeta los pies, rodillas abiertas hacia las axilas, mécete suavemente",
  "yoga.cueSeatedTwist": "Inhala para crecer, exhala para girar un poco más",
  "yoga.cueLegsUpTheWall": "Caderas cerca de la pared, brazos abiertos, nada que hacer",
  "yoga.cueSavasana": "Deja que todo se vuelva pesado. Respira sin dirigirla.",
  "yoga.cueCobra": "Caderas abajo, el pecho se eleva, codos suaves",
  "yoga.cueCamel": "Manos a los talones o a la zona lumbar, eleva el pecho hacia el techo",
  "yoga.cueLocust": "Eleva pecho y piernas a la vez, aprieta entre los omóplatos",
  "yoga.cuePlank": "Una línea recta, respira de forma constante",
  "yoga.cueSunFlow": "Muévete con la respiración — un movimiento por inhalación o exhalación",
  "yoga.cueYinEdge": "Encuentra tu límite y retrocede un poco — acomódate para la postura larga",
};
